### ISSUE TITLE
FreeBSD issue

### ISSUE THREAD

**Issue by tsaridas** [sshuttle/sshuttle#100]
Hello,

I get the below error when trying to run sshuttle from a FreeBSD server 

```
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.11
firewall manager: ready method name pf.
IPv6 enabled: False
UDP enabled: False
DNS enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
Starting client with Python version 2.7.11
c : connecting to server...
Starting server with Python version 2.7.6
 s: latency control setting = True
 s: available routes:
 s:   2/10.92.115.0/24
c : Connected.
firewall manager: setting up.
>> pfctl -s all
firewall manager: undoing changes.
>> pfctl -a sshuttle -F all
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 9, in <module>
    load_entry_point('sshuttle==0.78.0', 'console_scripts', 'sshuttle')()
  File "/usr/local/lib/python2.7/site-packages/sshuttle/cmdline.py", line 25, in main
    return firewall.main(opt.method, opt.syslog)
  File "/usr/local/lib/python2.7/site-packages/sshuttle/firewall.py", line 196, in main
    socket.AF_INET, subnets_v4, udp)
  File "/usr/local/lib/python2.7/site-packages/sshuttle/methods/pf.py", line 394, in setup_firewall
    pf.add_anchors()
  File "/usr/local/lib/python2.7/site-packages/sshuttle/methods/pf.py", line 159, in add_anchors
    self._add_anchor_rule(self.PF_RDR, b'sshuttle')
  File "/usr/local/lib/python2.7/site-packages/sshuttle/methods/pf.py", line 169, in _add_anchor_rule
    super(FreeBsd, self)._add_anchor_rule(type, name, pr=pr)
  File "/usr/local/lib/python2.7/site-packages/sshuttle/methods/pf.py", line 117, in _add_anchor_rule
    ioctl(pf_get_dev(), pf.DIOCCHANGERULE, pr)
IOError: [Errno 19] Operation not supported by device
c : fatal: cleanup: ['/usr/local/bin/python2.7', '/usr/local/bin/sshuttle', '-v', '--method', 'pf', '--firewall'] returned 1
```

FreeBSD release 

```
10.3-RELEASE-p3 FreeBSD 10.3-RELEASE-p3
amd64
```

**Comment by vieira** [comment]
I am testing `sshuttle -vvv -r user@server 188.0.0.0/8` in 10.2 and it works. I will update to 10.3 and try to reproduce. Maybe they changed some ioctls from 10.2 to 10.3. 😞

**Comment by vieira** [comment]
I am now on `10.3-RELEASE-p4` and it continues to work. Could you please share the arguments that you are using to run sshuttle? Thanks!

**Comment by tsaridas** [comment]
hi @vieira 

```
sshuttle -r 8.8.8.8 10.92.115.0/24 -vv
```
Shouldn't be an issue with the options though since I tried plenty.

Probably maybe because I'm running pfsense ? What are the packages the sshuttle needs and what version so I can check with my pfsense box ?

Thanks

**Comment by vieira** [comment]
Yeah, it shouldn't be an issue with the options, I am testing essentially with the same options as you.

I don't have a box with pfSense right now and I am not very familiar with it but I think they ship their own version of pf now. No idea how much effort would be required to add support in sshuttle for their version of pf. FreeBSD was relatively easy but OpenBSD gave me some serious headaches.

A quick search does not return any documentation about the pf in pfSense, so there would be a lot of trial and error involved... 😩

**Comment by tsaridas** [comment]
You are probably right and it concerns version of pf or other libraries being used by pfsense.

I would go and check if older versions of pfsense work but not in my priorities.

For the reference I'm using pfsense 2.3.
