### ISSUE TITLE
Is there a delay when using --dns?

### ISSUE THREAD

**Issue by yobyot** [sshuttle/sshuttle#103]
Love sshuttle and appreciate the work that's gone into it.

I have a question about using `--dns` when sending all traffic over the tunnel (using 0/0). Is there a delay of some kind built into sshuttle before DNS requests are forwarded over the tunnel? I've noticed that once the tunnel is running, I can access any machine in the remote network by IP instantly. But I seem to have to wait for DNS entries to work.

Thanks.

**Comment by brianmay** [comment]
No, there should not be any delay in using --dns. If however the server's ``/etc/resolv.conf`` has a dead DNS server this could increase the time required to try and find a good server for each query.

**Comment by brianmay** [comment]
If you want more help, please provide additional information. Such as if all DNS servers in the ``/etc/resolv.conf`` on your server are reachable or not. Closing for now. Thanks.
