### ISSUE TITLE
sshuttle 0.78 in Ubuntu 16.04 - UDP problems 

### ISSUE THREAD

**Issue by DiagonalArg** [sshuttle/sshuttle#104]
I have installed 0.78 into Ubuntu 16.04 Gnome, using the .deb from the debian repos.  (I'll note that I tried 0.77 before, and it failed to install.)  All seems to work fine for tcp proxying; indeed one server that had previously not worked on 0.76 (which is the one in the ubuntu repos) is now working.  So I have now been trying to get udp to work, but with little luck.  I execute:

    sudo ip route add local default dev lo table 100
    sudo ip rule add fwmark 1 lookup 100
    sudo SSH_AUTH_SOCK="$SSH_AUTH_SOCK" su
    sshuttle --method=tproxy --disable-ipv6 -vv --pidfile=/tmp/sshuttle.pid -r me@server 0/0 -x <server_ip> 

sshuttle seems to connect fine, but then after about 30 seconds, it fails.  Python3.5 exists on both ends. I tried both with and without --dns. Here is the -vv output (without --dns): [sshuttleout.txt](https://github.com/sshuttle/sshuttle/files/349145/sshuttleout.txt).

Please let me know if I can provide anything else.  I'd be ecstatic to get this working!

**Comment by DiagonalArg** [comment]
Hmmm.  I see that in my kernel config I have CONFIG_NETFILTER_XT_TARGET_TPROXY, but no CONFIG_NETFILTER_TPROXY.  This is the stock kernel - I haven't done anything special.  Could this be the issue?

**Comment by brianmay** [comment]
The error you got looks suspicously like an program error:

TypeError: a bytes-like object is required, not 'str'

Are you able to try with the latest git version? I suspect this problem
is already fixed.

I am guessing you would need ``CONFIG_NETFILTER_TPROXY`` set, however it doesn't explain this error you got.

**Comment by DiagonalArg** [comment]
Forgive me, but I know zero python.  I edited `sshuttle-master/run` to change `exec python3.5 -m "sshuttle" "$@"` to `exec python3.5 -m "/path/to/shuttle-master/sshuttle" "$@"`.  Then I tried as su:

    ./run --method=tproxy ...

It responds:

    No module named /home/dev/Downloads/sshuttle-master/sshuttle

Sorry to need to ask for training wheels.

**Comment by DiagonalArg** [comment]
In the suggestion on the list, you pointed out that sshuttle does report whether UDP is being forwarded:

    IPv6 enabled: False 
    UDP enabled: True 
    DNS enabled: False 

Since it says "True", does that mean tproxy was being used for a short period of time, before the crash?  If so, then it seems we know that lack of CONFIG_NETFILTER_TPROXY is not the issue (?)

**Comment by brianmay** [comment]
There shouldn't be any need to edit the run command. What happens if you try to execute it without editing it? Maybe try:

```
PYTHONPATH=$PWD ./run
```

Although I haven't needed this myself, so am I bit surprised if you need it.

**Comment by DiagonalArg** [comment]
Brian - I did as you said with `PYTHONPATH`.  As long as you are sure the result was to run the version I DL'd from github, rather than the one I have installed on my system (`gdebi -i sshuttle....deb`), then the error looks very similar, with a very quick crash: [sshuttleout.txt](https://github.com/sshuttle/sshuttle/files/351951/sshuttleout.txt)

**Comment by brianmay** [comment]
If you want to be sure that you are running the version from github, as opposed to the version installed, then you should uninstall the installed version...

Also what does ``./run -V`` show you?

**Comment by vieira** [comment]
@brianmay Do you think we might be missing a ```decode("ASCII")``` in [server.py#308](https://github.com/sshuttle/sshuttle/blob/master/sshuttle/server.py#L308) like we have in [server.py#287](https://github.com/sshuttle/sshuttle/blob/master/sshuttle/server.py#L287)? I can try to reproduce this when I get home.

**Comment by DiagonalArg** [comment]
I assume this means I was right:

    root@XXX#  ./run -V
    Python 3.5.1+
    unknown
    root@XXX# sshuttle -V
    0.78.0

**Comment by brianmay** [comment]
Just merged #105. So hopefully this will be fixed. You will need to be able to work out how to run the latest git version however.

**Comment by DiagonalArg** [comment]
Ok, it's running!  Unfortunately though, it's not working.  I'll open another issue.
