### ISSUE TITLE
Can OpenSSH on Windows be a target for sshuttle

### ISSUE THREAD

**Issue by yobyot** [sshuttle/sshuttle#109]
Love this VPN/port-forwarder!

I'm experimenting with the newish OpenSSH server on Windows Server 2012 R2 (https://github.com/PowerShell/Win32-OpenSSH) and haven't been able to get sshuttle working through it.

Is this something I should give up on? :-)

Thx.

**Comment by thshdw** [comment]
native widows support is going to be difficult if not impossible. However you can get it working with the assistance of a vm. 
see #32 and #64

**Comment by brianmay** [comment]
Nothing we can do here; closing.

**Comment by brianmay** [comment]
Fixed by #918.
