### ISSUE TITLE
Sample Installation needs root permission on OS X

### ISSUE THREAD

**Issue by wuisawesome** [sshuttle/sshuttle#111]
This is an extremely minor issue, but in the sample README, the setup python script needs to be `sudo ./setup.py` or else you get `error: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/easy-install.pth'
` 

Very minor but it may save others a bit of time in the future.

**Comment by brianmay** [comment]
Pull requests to fix this appreciated. Although maybe that section needs to be expanded too. On Debian testing/unstable the preferred installation method is "sudo apt-get install sshuttle".
