### ISSUE TITLE
How to share sshuttle internet

### ISSUE THREAD

**Issue by lokeshh** [sshuttle/sshuttle#114]
I cannot share my internet connection (that I got though doing sshuttle) via hotspot. Is there any way I can share the transparent internet I've got using sshuttle through a hotspot for my other devices such as Android?

It would be immensely helpful.

**Comment by brianmay** [comment]
Sshuttle support on Android would be really great! Unfortunately, I won't have anytime in the foreseeable future to work on this.

Patches welcome.

I guess the first step for anybody inspiring to do this would be to check the standard and manufacturer specific Android kernels have the appropriate options compiled to allow sshuttle to work - either with NAT or TPROXY.

**Comment by brianmay** [comment]
It is possible I misunderstood this request. Where are you running sshuttle? On the Android system, or somewhere else?

**Comment by lokeshh** [comment]
I'm running sshutle on Linux and trying to share it to Android via hotspot

**Comment by brianmay** [comment]
Do you mean you have a 3G connection on Linux and want to share it?

**Comment by lokeshh** [comment]
No, I'm behind a proxy server and use sshuttle to connect a server in the
LAN that has direct access to the Internet.

**Comment by CzEMC** [comment]
Some laptops, like mine, have hot spotting capability built-in to the Wifi Card. If your laptop has this, any program, free or proprietary, will be able to hotspot the connection. However, some cards can only be in one mode at a time. (Hotspot Host or Wifi Client) So you may need Ethernet connection.

**Comment by brianmay** [comment]
Sorry, not really in a position to be able to provide support for sshuttle. Closing.
