### ISSUE TITLE
Move pytest-runner to tests_require

### ISSUE THREAD

**Issue by jonathanunderwood** [sshuttle/sshuttle#115]
Presently pytest-runner is part of the setup_requires list, whereas in actuality it's needed only for testing - it would be preferable to move that to the list tests_requires instead:

https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=tests_requires

**Comment by brianmay** [comment]
Tested pull requests welcome :-)

**Comment by brianmay** [comment]
This was fixed in #123.
