### ISSUE TITLE
Command line handling of subnets with subnet file broken

### ISSUE THREAD

**Issue by desbma** [sshuttle/sshuttle#116]
Hi,

I am using sshuttle 0.78.1 from [the official Arch Linux package](https://www.archlinux.org/packages/community/any/sshuttle/).

The package installs a systemd service with two config files, one with the subnets for sshuttle one with the hostname of the other end of the tunnel for ssh.

The service then starts sshuttle with the following command line: 
`/usr/bin/sshuttle --dns --listen 0.0.0.0 --remote sshuttle_tunnel -s /etc/sshuttle/prefixes.conf -e "ssh -F /etc/sshuttle/tunnel.conf"`

Which raises the following exception:

    Traceback (most recent call last):
      File "/usr/bin/sshuttle", line 9, in <module>
        load_entry_point('sshuttle==0.78.1', 'console_scripts', 'sshuttle')()
      File "/usr/lib/python3.5/site-packages/sshuttle/cmdline.py", line 12, in main
        opt = parser.parse_args()
      File "/usr/lib/python3.5/argparse.py", line 1726, in parse_args
        args, argv = self.parse_known_args(args, namespace)
      File "/usr/lib/python3.5/argparse.py", line 1758, in parse_known_args
        namespace, args = self._parse_known_args(args, namespace)
      File "/usr/lib/python3.5/argparse.py", line 1964, in _parse_known_args
        start_index = consume_optional(start_index)
      File "/usr/lib/python3.5/argparse.py", line 1904, in consume_optional
        take_action(action, args, option_string)
      File "/usr/lib/python3.5/argparse.py", line 1832, in take_action
        action(self, namespace, argument_values, option_string)
      File "/usr/lib/python3.5/site-packages/sshuttle/options.py", line 110, in __call__
        setattr(namespace, self.dest, curr_value + values)
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

At first glances, it seems this code tries to concatenate the subnets from the files with those passed from the command line, but they are none so that fails.

**Comment by brianmay** [comment]
subnets is a required parameter, this should trigger an error; maybe a bug in the command line processing?

**Comment by desbma** [comment]
I see, I'll open a bug for the Arch package maintainer then, because that command line can't work.

The error could be more explicit though (like what argpase outputs).

Also the command lines help says:

     -s PATH, --subnets PATH
                          file where the subnets are stored, instead of on the
                          command line`

which should maybe be changed to reflect that it does not replace but merely complements the positional subnet parameter.

**Comment by vieira** [comment]
Yes, this is a bug. All below should work:
```
ip1 ip2
ip1 ip2 -s subnets_file1 -s subnets_file2
-s subnets_file1
```
but the last one is producing the error reported. 

`argparse` is giving me a hard time merging the list of subnets from the `-s` argument and the ones from the positional arguments (e.g. ip1 ip2) when there are no positional arguments.

If there is no way to make it work this way I will make each write to their own list (something like `subnets` and `subnets_file`) and merge them myself at the end.

Any thoughts?

**Comment by desbma** [comment]
@vieira I think whith argparse positional arguments are always mandatory (which is why `required` does not exist for them), so there is no 'clean' way to make your last example work with standard argparse.

I have run into weird errors with argparse when not passing a positional argument make the module consume another optional parameter to fill the missing argument, which then outputs hard to understand errors.

**Comment by vieira** [comment]
@desbma they can be made optional with `nargs='*'`. If you can, please help test #117 and let me know if you find any problems. Many thanks!

@brianmay Looks good to you?

**Comment by desbma** [comment]
#117 fixes it for me, thanks.

**Comment by ccwufu** [comment]
**File "/root/sshu0782/sshuttle-0.78.2.dev10+ng0ed5ef9-py2.7.egg/sshuttle/cmdline.py", line 29, in main
TypeError: can only concatenate list (not "NoneType") to list**

root@lede:~/sshu0782# ./sshuttle --version
0.78.2.dev10+ng0ed5ef9

root@lede:~/sshu0782# ./sshuttle -v 0/0
Traceback (most recent call last):
  File "./sshuttle", line 11, in <module>
    load_entry_point('sshuttle==0.78.2.dev10+ng0ed5ef9', 'console_scripts', 'sshuttle')()
  File "/root/sshu0782/sshuttle-0.78.2.dev10+ng0ed5ef9-py2.7.egg/sshuttle/cmdline.py", line 29, in main
TypeError: can only concatenate list (not "NoneType") to list
root@lede:~/sshu0782# python --version
Python 2.7.12
root@lede:~/sshu0782# opkg list-installed | grep python
python - 2.7.12-2
python-base - 2.7.12-2
python-codecs - 2.7.12-2
python-compiler - 2.7.12-2
python-ctypes - 2.7.12-2
python-db - 2.7.12-2
python-decimal - 2.7.12-2
python-distutils - 2.7.12-2
python-email - 2.7.12-2
python-gdbm - 2.7.12-2
python-light - 2.7.12-2
python-logging - 2.7.12-2
python-multiprocessing - 2.7.12-2
python-ncurses - 2.7.12-2
python-openssl - 2.7.12-2
python-pydoc - 2.7.12-2
python-setuptools - 27.2.0-1
python-sqlite3 - 2.7.12-2
python-unittest - 2.7.12-2
python-xml - 2.7.12-2
```

root@lede:~/sshu0782# cat /etc/banner
     _________
    /        /\      _    ___ ___  ___
   /  LE    /  \    | |  | __|   \| __|
  /    DE  /    \   | |__| _|| |) | _|
 /________/  LE  \  |____|___|___/|___|                      lede-project.org
 \        \   DE /
  \    LE  \    /  -----------------------------------------------------------
   \  DE    \  /    Reboot (HEAD, r1730)
    \________\/    -----------------------------------------------------------

root@lede:~/sshu0782#
root@lede:~/sshu0782# uname -a
Linux lede 4.4.23 #0 Fri Sep 30 21:39:28 2016 mips GNU/Linux
root@lede:~/sshu0782# cat /proc/cpuinfo
system type             : Atheros AR9330 rev 1
machine                 : GL-CONNECT INET v1
processor               : 0
cpu model               : MIPS 24Kc V7.4
BogoMIPS                : 265.42
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 16
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available
```

**Comment by ccwufu** [comment]
installed in LEDE in  qemu (malta)

root@lede:~/sshuttle# ./setup.py install
./setup.py install
warning: build_py: byte-compiling is disabled, skipping.
warning: install_lib: byte-compiling is disabled, skipping.
Installed /tmp/easy_install-TmDX6L/pytest-runner-2.9/.eggs/setuptools_scm-1.13.0-py2.7.egg
warning: build_py: byte-compiling is disabled, skipping.
warning: install_lib: byte-compiling is disabled, skipping.
zip_safe flag not set; analyzing archive contents...
Installed /root/sshuttle/.eggs/pytest_runner-2.9-py2.7.egg
Searching for setuptools_scm
Reading https://pypi.python.org/simple/setuptools_scm/
Downloading https://pypi.python.org/packages/81/fb/16f8dd7d260edabe9d4c51a79200ac2de8ff04cfc9c609eb854dc332c8e4/setuptools_scm-1.13.0.tar.gz#md5=655a7002b7b4b0e0949baf63ee6648bd
Best match: setuptools-scm 1.13.0
Processing setuptools_scm-1.13.0.tar.gz
Writing /tmp/easy_install-NlxuHs/setuptools_scm-1.13.0/setup.cfg
Running setuptools_scm-1.13.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-NlxuHs/setuptools_scm-1.13.0/egg-dist-tmp-13apcE
warning: build_py: byte-compiling is disabled, skipping.
warning: install_lib: byte-compiling is disabled, skipping.
Moving setuptools_scm-1.13.0-py2.7.egg to /root/sshuttle/.eggs
Installed /root/sshuttle/.eggs/setuptools_scm-1.13.0-py2.7.egg
running install
running bdist_egg
running egg_info
creating sshuttle.egg-info
writing sshuttle.egg-info/PKG-INFO
writing top-level names to sshuttle.egg-info/top_level.txt
writing dependency_links to sshuttle.egg-info/dependency_links.txt
writing entry points to sshuttle.egg-info/entry_points.txt
writing manifest file 'sshuttle.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'docs/conf.py'
warning: no previously-included files matching '*' found under directory 'docs/_build'
writing manifest file 'sshuttle.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-mips/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/sshuttle
copying sshuttle/version.py -> build/lib/sshuttle
copying sshuttle/stresstest.py -> build/lib/sshuttle
copying sshuttle/ssyslog.py -> build/lib/sshuttle
copying sshuttle/ssnet.py -> build/lib/sshuttle
copying sshuttle/ssh.py -> build/lib/sshuttle
copying sshuttle/server.py -> build/lib/sshuttle
copying sshuttle/options.py -> build/lib/sshuttle
copying sshuttle/linux.py -> build/lib/sshuttle
copying sshuttle/hostwatch.py -> build/lib/sshuttle
copying sshuttle/helpers.py -> build/lib/sshuttle
copying sshuttle/firewall.py -> build/lib/sshuttle
copying sshuttle/cmdline.py -> build/lib/sshuttle
copying sshuttle/client.py -> build/lib/sshuttle
copying sshuttle/assembler.py -> build/lib/sshuttle
copying sshuttle/__main__.py -> build/lib/sshuttle
copying sshuttle/__init__.py -> build/lib/sshuttle
creating build/lib/sshuttle/methods
copying sshuttle/methods/tproxy.py -> build/lib/sshuttle/methods
copying sshuttle/methods/pf.py -> build/lib/sshuttle/methods
copying sshuttle/methods/nat.py -> build/lib/sshuttle/methods
copying sshuttle/methods/__init__.py -> build/lib/sshuttle/methods
warning: build_py: byte-compiling is disabled, skipping.

creating build/bdist.linux-mips
creating build/bdist.linux-mips/egg
creating build/bdist.linux-mips/egg/sshuttle
creating build/bdist.linux-mips/egg/sshuttle/methods
copying build/lib/sshuttle/methods/__init__.py -> build/bdist.linux-mips/egg/sshuttle/methods
copying build/lib/sshuttle/methods/nat.py -> build/bdist.linux-mips/egg/sshuttle/methods
copying build/lib/sshuttle/methods/pf.py -> build/bdist.linux-mips/egg/sshuttle/methods
copying build/lib/sshuttle/methods/tproxy.py -> build/bdist.linux-mips/egg/sshuttle/methods
copying build/lib/sshuttle/__init__.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/__main__.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/assembler.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/client.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/cmdline.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/firewall.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/helpers.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/hostwatch.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/linux.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/options.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/server.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/ssh.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/ssnet.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/ssyslog.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/stresstest.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/version.py -> build/bdist.linux-mips/egg/sshuttle
warning: install_lib: byte-compiling is disabled, skipping.

creating build/bdist.linux-mips/egg/EGG-INFO
copying sshuttle.egg-info/PKG-INFO -> build/bdist.linux-mips/egg/EGG-INFO
copying sshuttle.egg-info/SOURCES.txt -> build/bdist.linux-mips/egg/EGG-INFO
copying sshuttle.egg-info/dependency_links.txt -> build/bdist.linux-mips/egg/EGG-INFO
copying sshuttle.egg-info/entry_points.txt -> build/bdist.linux-mips/egg/EGG-INFO
copying sshuttle.egg-info/top_level.txt -> build/bdist.linux-mips/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/sshuttle-0.78.2.dev10+ng0ed5ef9-py2.7.egg' and adding 'build/bdist.linux-mips/egg' to it
removing 'build/bdist.linux-mips/egg' (and everything under it)
Processing sshuttle-0.78.2.dev10+ng0ed5ef9-py2.7.egg
Copying sshuttle-0.78.2.dev10+ng0ed5ef9-py2.7.egg to /usr/lib/python2.7/site-packages
Adding sshuttle 0.78.2.dev10+ng0ed5ef9 to easy-install.pth file
Installing sshuttle script to /usr/bin

Installed /usr/lib/python2.7/site-packages/sshuttle-0.78.2.dev10+ng0ed5ef9-py2.7.egg
Processing dependencies for sshuttle==0.78.2.dev10+ng0ed5ef9
Finished processing dependencies for sshuttle==0.78.2.dev10+ng0ed5ef9
root@lede:~/sshuttle#

root@lede:/usr/bin# sshuttle -v 0/0
sshuttle -v 0/0
Traceback (most recent call last):
  File "/usr/bin/sshuttle", line 11, in <module>
    load_entry_point('sshuttle==0.78.2.dev10+ng0ed5ef9', 'console_scripts', 'sshuttle')()
  File "/usr/lib/python2.7/site-packages/sshuttle-0.78.2.dev10+ng0ed5ef9-py2.7.egg/sshuttle/cmdline.py", line 29, in main
TypeError: can only concatenate list (not "NoneType") to list
root@lede:/usr/bin#

root@lede:~/sshuttle# sshuttle --help
sshuttle --help

usage: sshuttle [-l [ip:]port] [-r [user@]sshserver[:port]] <subnets...>

positional arguments:
  IP/MASK [IP/MASK...]  capture and forward traffic to these subnets
                        (whitespace separated)

optional arguments:
  -h, --help            show this help message and exit
  -l [IP:]PORT, --listen [IP:]PORT
                        transproxy to this ip address and port number
  -H, --auto-hosts      continuously scan for remote hostnames and update
                        local /etc/hosts as they are found
  -N, --auto-nets       automatically determine subnets to route
  --dns                 capture local DNS requests and forward to the remote
                        DNS server
  --ns-hosts IP[,IP]    capture and forward DNS requests made to the following
                        servers
  --method TYPE         auto, nat, tproxy, pf
  --python PATH         path to python interpreter on the remote server
  -r [USERNAME@]ADDR[:PORT], --remote [USERNAME@]ADDR[:PORT]
                        ssh hostname (and optional username) of remote
                        sshuttle server
  -x IP/MASK, --exclude IP/MASK
                        exclude this subnet (can be used more than once)
  -X PATH, --exclude-from PATH
                        exclude the subnets in a file (whitespace separated)
  -v, --verbose         increase debug message verbosity
  -V, --version         print the sshuttle version number and exit
  -e CMD, --ssh-cmd CMD
                        the command to use to connect to the remote [ssh]
  --seed-hosts HOSTNAME[,HOSTNAME]
                        comma-separated list of hostnames for initial scan
                        (may be used with or without --auto-hosts)
  --no-latency-control  sacrifice latency to improve bandwidth benchmarks
  --wrap NUM            restart counting channel numbers after this number
                        (for testing)
  --disable-ipv6        disable IPv6 support
  -D, --daemon          run in the background as a daemon
  -s PATH, --subnets PATH
                        file where the subnets are stored, instead of on the
                        command line
  --syslog              send log messages to syslog (default if you use
                        --daemon)
  --pidfile PATH        pidfile name (only if using --daemon) [./sshuttle.pid]
  --firewall            (internal use only)
  --hostwatch           (internal use only)
root@lede:~/sshuttle#

**Comment by vieira** [comment]
@ccwufu Oops, I introduced that problem on #117, sorry for that. #119 should fix the issue, can you confirm? Thanks!

**Comment by ccwufu** [comment]
@vieira   thanks!
#119 should fix the "cmdline.py", line 29, in main TypeError: can only concatenate list (not "NoneType") to list"

but another problem happen 
  File "/usr/lib/python2.7/site-packages/sshuttle-0.78.2.dev10+ng0ed5ef9.d20161007-py2.7.egg/sshuttle/ssh.py", line 29, in readfile
**ImportError: No module named sshuttle**

root@lede:~/sshuttle# sshuttle --version
sshuttle --version
0.78.2.dev10+ng0ed5ef9.d20161007
root@lede:/usr/lib/python2.7/site-packages# sshuttle -v 0/0
sshuttle -v 0/0
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.12
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
Starting client with Python version 2.7.12
c : connecting to server...
Traceback (most recent call last):
  File "/usr/bin/sshuttle", line 11, in <module>
    load_entry_point('sshuttle==0.78.2.dev10+ng0ed5ef9.d20161007', 'console_scripts', 'sshuttle')()
  File "/usr/lib/python2.7/site-packages/sshuttle-0.78.2.dev10+ng0ed5ef9.d20161007-py2.7.egg/sshuttle/cmdline.py", line 74, in main
  File "/usr/lib/python2.7/site-packages/sshuttle-0.78.2.dev10+ng0ed5ef9.d20161007-py2.7.egg/sshuttle/client.py", line 726, in main
  File "/usr/lib/python2.7/site-packages/sshuttle-0.78.2.dev10+ng0ed5ef9.d20161007-py2.7.egg/sshuttle/client.py", line 422, in _main
  File "/usr/lib/python2.7/site-packages/sshuttle-0.78.2.dev10+ng0ed5ef9.d20161007-py2.7.egg/sshuttle/ssh.py", line 88, in connect
  File "/usr/lib/python2.7/site-packages/sshuttle-0.78.2.dev10+ng0ed5ef9.d20161007-py2.7.egg/sshuttle/ssh.py", line 29, in readfile
ImportError: No module named sshuttle

root@lede:~/sshuttle# ./setup.py install
./setup.py install
warning: build_py: byte-compiling is disabled, skipping.

warning: install_lib: byte-compiling is disabled, skipping.


Installed /tmp/easy_install-zbKihd/pytest-runner-2.9/.eggs/setuptools_scm-1.13.0-py2.7.egg
warning: build_py: byte-compiling is disabled, skipping.

warning: install_lib: byte-compiling is disabled, skipping.

zip_safe flag not set; analyzing archive contents...

Installed /root/sshuttle/.eggs/pytest_runner-2.9-py2.7.egg
Searching for setuptools_scm
Reading https://pypi.python.org/simple/setuptools_scm/
Downloading https://pypi.python.org/packages/81/fb/16f8dd7d260edabe9d4c51a79200ac2de8ff04cfc9c609eb854dc332c8e4/setuptools_scm-1.13.0.tar.gz#md5=655a7002b7b4b0e0949baf63ee6648bd
Best match: setuptools-scm 1.13.0
Processing setuptools_scm-1.13.0.tar.gz
Writing /tmp/easy_install-473PYx/setuptools_scm-1.13.0/setup.cfg
Running setuptools_scm-1.13.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-473PYx/setuptools_scm-1.13.0/egg-dist-tmp-DocCqV
warning: build_py: byte-compiling is disabled, skipping.

warning: install_lib: byte-compiling is disabled, skipping.

Moving setuptools_scm-1.13.0-py2.7.egg to /root/sshuttle/.eggs

Installed /root/sshuttle/.eggs/setuptools_scm-1.13.0-py2.7.egg
running install
running bdist_egg
running egg_info
creating sshuttle.egg-info
writing sshuttle.egg-info/PKG-INFO
writing top-level names to sshuttle.egg-info/top_level.txt
writing dependency_links to sshuttle.egg-info/dependency_links.txt
writing entry points to sshuttle.egg-info/entry_points.txt
writing manifest file 'sshuttle.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'docs/conf.py'
warning: no previously-included files matching '*' found under directory 'docs/_build'
writing manifest file 'sshuttle.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-mips/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/sshuttle
copying sshuttle/version.py -> build/lib/sshuttle
copying sshuttle/options.py -> build/lib/sshuttle
copying sshuttle/stresstest.py -> build/lib/sshuttle
copying sshuttle/ssyslog.py -> build/lib/sshuttle
copying sshuttle/ssnet.py -> build/lib/sshuttle
copying sshuttle/ssh.py -> build/lib/sshuttle
copying sshuttle/server.py -> build/lib/sshuttle
copying sshuttle/linux.py -> build/lib/sshuttle
copying sshuttle/hostwatch.py -> build/lib/sshuttle
copying sshuttle/helpers.py -> build/lib/sshuttle
copying sshuttle/firewall.py -> build/lib/sshuttle
copying sshuttle/cmdline.py -> build/lib/sshuttle
copying sshuttle/client.py -> build/lib/sshuttle
copying sshuttle/assembler.py -> build/lib/sshuttle
copying sshuttle/__main__.py -> build/lib/sshuttle
copying sshuttle/__init__.py -> build/lib/sshuttle
creating build/lib/sshuttle/methods
copying sshuttle/methods/tproxy.py -> build/lib/sshuttle/methods
copying sshuttle/methods/pf.py -> build/lib/sshuttle/methods
copying sshuttle/methods/nat.py -> build/lib/sshuttle/methods
copying sshuttle/methods/__init__.py -> build/lib/sshuttle/methods
warning: build_py: byte-compiling is disabled, skipping.

creating build/bdist.linux-mips
creating build/bdist.linux-mips/egg
creating build/bdist.linux-mips/egg/sshuttle
creating build/bdist.linux-mips/egg/sshuttle/methods
copying build/lib/sshuttle/methods/__init__.py -> build/bdist.linux-mips/egg/sshuttle/methods
copying build/lib/sshuttle/methods/nat.py -> build/bdist.linux-mips/egg/sshuttle/methods
copying build/lib/sshuttle/methods/pf.py -> build/bdist.linux-mips/egg/sshuttle/methods
copying build/lib/sshuttle/methods/tproxy.py -> build/bdist.linux-mips/egg/sshuttle/methods
copying build/lib/sshuttle/__init__.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/__main__.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/assembler.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/client.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/cmdline.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/firewall.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/helpers.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/hostwatch.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/linux.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/server.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/ssh.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/ssnet.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/ssyslog.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/stresstest.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/options.py -> build/bdist.linux-mips/egg/sshuttle
copying build/lib/sshuttle/version.py -> build/bdist.linux-mips/egg/sshuttle
warning: install_lib: byte-compiling is disabled, skipping.

creating build/bdist.linux-mips/egg/EGG-INFO
copying sshuttle.egg-info/PKG-INFO -> build/bdist.linux-mips/egg/EGG-INFO
copying sshuttle.egg-info/SOURCES.txt -> build/bdist.linux-mips/egg/EGG-INFO
copying sshuttle.egg-info/dependency_links.txt -> build/bdist.linux-mips/egg/EGG-INFO
copying sshuttle.egg-info/entry_points.txt -> build/bdist.linux-mips/egg/EGG-INFO
copying sshuttle.egg-info/top_level.txt -> build/bdist.linux-mips/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/sshuttle-0.78.2.dev10+ng0ed5ef9.d20161007-py2.7.egg' and adding 'build/bdist.linux-mips/egg' to it
removing 'build/bdist.linux-mips/egg' (and everything under it)
Processing sshuttle-0.78.2.dev10+ng0ed5ef9.d20161007-py2.7.egg
Copying sshuttle-0.78.2.dev10+ng0ed5ef9.d20161007-py2.7.egg to /usr/lib/python2.7/site-packages
Adding sshuttle 0.78.2.dev10+ng0ed5ef9.d20161007 to easy-install.pth file
Installing sshuttle script to /usr/bin

Installed /usr/lib/python2.7/site-packages/sshuttle-0.78.2.dev10+ng0ed5ef9.d20161007-py2.7.egg
Processing dependencies for sshuttle==0.78.2.dev10+ng0ed5ef9.d20161007
Finished processing dependencies for sshuttle==0.78.2.dev10+ng0ed5ef9.d20161007

root@lede:~# python
python
Python 2.7.12 (default, Oct  7 2016, 00:39:25)
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> help('modules')
help('modules')

Please wait a moment while I gather a list of all available modules...

BaseHTTPServer      audiodev            ihooks              sched

_MozillaCookieJar   collections         md5                 sshuttle

asyncore            htmllib             robotparser         zipimport
atexit              httplib             runpy               zlib

Enter any module name to get more help.  Or, type "modules spam" to search
for modules whose descriptions contain the word "spam".

>>>
>>> help('sshuttle')
help('sshuttle')
Help on package sshuttle:

NAME
    sshuttle

FILE
    /usr/lib/python2.7/site-packages/sshuttle-0.78.2.dev10+ng0ed5ef9.d20161007-py2.7.egg/sshuttle/__init__.py

PACKAGE CONTENTS
    __main__
    assembler
    client
    cmdline
    firewall
    helpers
    hostwatch
    linux
    methods (package)
    options
    server
    ssh
    ssnet
    ssyslog
    stresstest
-- more --
    version
-- more --

-- more --
DATA
-- more --
    __loader__ = <zipimporter object "/usr/lib/python2.7/site-pac...ttle-0...
-- more --
    __version__ = '0.78.2.dev10+ng0ed5ef9.d20161007'
-- more --

-- more --
VERSION
-- more --
    0.78.2.dev10+ng0ed5ef9.d20161007
-- more --

-- more --


>>>

**Comment by vieira** [comment]
Hi @ccwufu 
That seems unrelated, is it possible that the situation described here is happening to you? https://github.com/sshuttle/sshuttle/issues/106#issuecomment-242932280
