### ISSUE TITLE
how to run ssh command or pass ENV variable?

### ISSUE THREAD

**Issue by cole-brokamp** [sshuttle/sshuttle#126]
Is there a way to run an initial SSH command or pass an ENV variable when starting sshuttle?  I need to be able to set a proxy variable.  I have tried using `~.ssh/rc`, but it doesn't seem to work with sshuttle, not sure if this is something specific to the server or not.  Thanks.

**Comment by vieira** [comment]
Have you tried `sshuttle --ssh-cmd="ssh -o ..."`?

**Comment by cole-brokamp** [comment]
yes, I did. However, I think I have narrowed it down to something with the server, not sshuttle.  Thanks for the help!
