### ISSUE TITLE
what's the official repository?

### ISSUE THREAD

**Issue by GildedHonour** [sshuttle/sshuttle#127]
what's the official repository: this one or https://github.com/apenwarr/sshuttle?

**Comment by brianmay** [comment]
This respository contains the latest code.

**Comment by GildedHonour** [comment]
How is it related to https://github.com/apenwarr/sshuttle?

**Comment by brianmay** [comment]
That was the repository by the original author, before he lost interest.

**Comment by GildedHonour** [comment]
Ok, but in that repository it doesn't point to yours. Also, which one is used in Linux when it's installed via apt-get: yours or his?

**Comment by brianmay** [comment]
Not sure what you mean "that repository it doesn't point to yours".

The package in Debian unstable is based on this repository. I can't speak for other distributions.

**Comment by GildedHonour** [comment]
I mean, in the original repository there's no methion about yours being de-facto or suggestion to use it instead. Why not?

**Comment by brianmay** [comment]
I don't have write access to the original repository.

**Comment by GildedHonour** [comment]
You don't have to.
