### ISSUE TITLE
Why it not works correctly?

### ISSUE THREAD

**Issue by hardconf** [sshuttle/sshuttle#128]
On my ubunu 14.04 server i run samba server. Then i run on it sshuttle -r username@sshserver 0.0.0.0/0 it works, but now i not able to conect to my samba server from local network. Whet i stop sshuttle i m now able to connect to my samba server. How to fix it?

**Comment by brianmay** [comment]
Sorry, not sure what you are trying to achieve with sshuttle. If you use ``0.0.0.0/0`` it will redirect all traffic, including the traffic to your samba server. Maybe exclude the IP address range of your local network?

**Comment by brianmay** [comment]
This does not appear to be a bug, and no response. Closing.
