### ISSUE TITLE
Document how to use /etc/sshuttle files

### ISSUE THREAD

**Issue by kwill** [sshuttle/sshuttle#137]
I've installed `sshuttle` 0.78.1-1 on Ubuntu 16.10. From the terminal I can successfully run:

    sshuttle --auto-hosts --daemon --remote=remote_user@host:port ip

I'd like to make this connection:

* always start when my computer starts (i.e. run as a daemon/service)
* uses the local user ssh key for the ssh connection (`/home/local_user/.ssh/key_rsa`)

this is so that:

* I don't have to remember to connect every time I start my machine
* I don't have to enter my sudo or ssh password every time

As far as I can tell I should be doing this with `/etc/sshuttle/tunnel.conf` and `/etc/sshuttle/prefixes.conf` but it's not clear to me:
* how to map sshtunnel command-line values to ssh_config values
* how I would define more than one sshtunnel connection in these files
* what kind of files I would put in `/etc/sshuttle/pre-start.d/` and `/etc/sshuttle/post-stop.d/`

Some documentation or an example would be helpful.

(As an alternative, I've also tried defining a .desktop file that invokes sshuttle using gksudo or pkexec, but this effectively runs sshuttle as root which skips the ssh key file.)

**Comment by brianmay** [comment]
The files that you are looking at are not supplied as part of this project, rather they are supplied as part of the Debian packaging which then is used by the Ubuntu packaging.

I have never needed or used this functionality myself. However have you seen the ``/usr/share/doc/sshuttle/sshuttle.conf`` file? Not sure about Ubuntu, but it is in the Debian package.

**Comment by kwill** [comment]
Thanks! The doc folder also contains a README.Debian (below), which confirms that any queries about using these files to set up a service should be [directed to Debian](https://tracker.debian.org/pkg/sshuttle).

> The sshuttle package in Debian does not provide, on purpose, any service to
start up a VPN tunnel. Users of sshuttle (with administrative privileges in the
local system) have to manually startup sshuttle.
>
> For your convenience, there is an example configuration file under
/usr/share/doc/sshuttle/sshuttle.conf 
>
> You can adjust the above file and drop it in your /etc/init/ configuration
directory to have the system automatically start sstunnel as a service
