### ISSUE TITLE
[query] What is the client IP address in the host context?

### ISSUE THREAD

**Issue by kwill** [sshuttle/sshuttle#138]
Some applications restrict access based on the IP address of the incoming connection. From the perspective of the host(s), what is the IP address of the machine I am sshuttling from?

For example, I am on `localmachine` and I run:

    local_user@localmachine:~$ sshuttle --remote=remote_user@remotemachine:22 123.0.0.1
    local_user@localmachine:~$ nmap -p 5432 123.0.0.1

This confirms I can access the PostgreSQL port on `remotemachine`. But I need to configure PostgreSQL to accept incoming connections from `localmachine`.

If I run `ifconfig` on `localmachine` I can see my IP address is `192.168.1.1` on my WLAN and `a.b.c.d` on the global internet. Which one does `remotemachine` see (or do I have different IP address in the sshuttle context)?

**Comment by brianmay** [comment]
So you are sshing (using sshuttle) to remotemachine (123.0.0.1), and then trying to access a postgresql service (also 123.0.0.1)? Most likely the IP address would be 123.0.0.1. All that sshuttle does is create a TCP connection from *remotemachine* to 123.0.0.1. sshuttle doesn't attempt to forward TCP connections or IP packets over the ssh connection, it only forwards the TCP data.

Does this help?

**Comment by kwill** [comment]
Yes, I set up PostgreSQL to accept connections from 123.0.0.1 and it worked as you suggested. Thanks!
