### ISSUE TITLE
"sshuttle -D" silently fails if pid file exists

### ISSUE THREAD

**Issue by jamshid** [sshuttle/sshuttle#140]
Using 0.78.1 on macos. (Thanks, sshuttle comes in really handy for making a docker container network accessible outside of docker.)

I use below command to start a "vpn" to the REAL_SERVER ip address, via ssh to a machine that has access to REAL_SERVER.
```
$ sshuttle -D --remote ${SSH_PROXY_USER}@${SSH_PROXY_HOST}:${SSH_PROXY_PORT} ${REAL_SERVER}
```

I couldn't figure out why this would sometimes silently fail to do anything. I expected a "sudo" prompt and the network routes to be created. Turns out it is failing when I have already started an unrelated sshuttle session. 

**Seems failures before daemonization should log to console, not only to syslog.** And is there a way to disable syslog, log to stderr instead? Finally, since it seems multiple sessions are allowed and work fine, maybe the pid file should be uniquely named and maybe put into a shared directory so it's easy to find and kill these sessions.

PS: I shouldn't say "silent" fails because this message _does_ go to syslog (the Utilities => Console app in macos), but it's easy to miss
```
/Users/.../sshuttle.pid: sshuttle is already running (pid=4601)
```

**Comment by brianmay** [comment]
We were just talking about the demonization process - and the fact we don't do it very well -  in #139.

**Comment by vieira** [comment]
As `--syslog` can be used without without `--daemon` tying what goes to syslog to daemon would be inconsistent. As it is now your logs are all on the same place, either syslog or stderr depending on your options.

BTW, You can use something like the command below to run multiple instances as daemons:
```
$ sshuttle -D --pidfile=/var/run/sshuttle-$(date +%s).pid --remote ${SSH_PROXY_USER}@${SSH_PROXY_HOST}:${SSH_PROXY_PORT} ${REAL_SERVER}
```

Hope it helps!

**Comment by brianmay** [comment]
Reading this again, not convinced there is anything we need to do. The point of the pid file is to prevent multiple copies running at the same time. If this really is desired, then use multiple pid files. Closing...
