### ISSUE TITLE
sshuttle continues to fail in OSX Mavericks ... IndexError: list index out of range

### ISSUE THREAD

**Issue by rsyncnet** [sshuttle/sshuttle#141]
I cloned the latest sshuttle on 2017-04-03  (0.78.2.dev24+ngaf9ebd0)  and attempted to run it on OSX Mavericks:

./run --dns --method pf -r shuttle@1.2.3.4:40 0/0

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 37, in <module>
  File "sshuttle.server", line 269, in main
  File "sshuttle.server", line 115, in list_routes
  File "sshuttle.server", line 96, in _list_routes
  File "sshuttle.server", line 71, in _route_netstat
IndexError: list index out of range
client: fatal: server died with error code 1

Is mavericks not a supported OS for sshuttle ?  

Thank you.

**Comment by vieira** [comment]
The server is also running OS X?

**Comment by rsyncnet** [comment]
No - server is FreeBSD 10.3.

**Comment by vieira** [comment]
The problem is probably with the server. I will try to reproduce.

**Comment by vieira** [comment]
I was able to reproduce this with a Linux client connecting to a FreeBSD 10.3 server. The problem was that we were not expecting non tabular output and BSD's netstat prints some non tabular headers (like `Routing tables` and `Internet:`, full output below) that we are now skipping.

```
$ netstat -4rn
Routing tables

Internet:
Destination        Gateway            Flags      Netif Expire
default            138.68.176.1       UGS      vtnet0
10.16.0.0/16       link#1             U        vtnet0
10.16.0.5          link#1             UHS         lo0
127.0.0.1          link#3             UH          lo0
138.68.176.0/20    link#1             U        vtnet0
138.68.178.43      link#1             UHS         lo0
```

**Comment by rsyncnet** [comment]
Thank you very much - I will wait for a new build when this issue is marked fixed.  Appreciated.
