### ISSUE TITLE
Windows as a server not working

### ISSUE THREAD

**Issue by BlackDex** [sshuttle/sshuttle#145]
Hello there,

I'm wondering if i can use windows as a server for the receiving connection?
I have python 3.5 installed on windows and together with mobassh i have ssh running on the system.
I can execute python 3.5 but i get an error when the server-side-script is started.

> Starting sshuttle proxy.
> firewall manager: Starting firewall with Python version 3.5.2
> firewall manager: ready method name nat.
> IPv6 enabled: False
> UDP enabled: False
> DNS enabled: False
> TCP redirector listening on ('127.0.0.1', 12300).
> Starting client with Python version 3.5.2
> c : connecting to server...
> warning: [Errno 2] No such file or directory: '/dev/null'
> Traceback (most recent call last):
>   File "sshuttle.hostwatch", line 24, in <module>
> FileNotFoundError: [Errno 2] No such file or directory: '/dev/null'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "assembler.py", line 24, in <module>
>   File "sshuttle.hostwatch", line 28, in <module>
>   File "C:\Program Files\Python35-32\lib\os.py", line 1027, in popen
>     raise ValueError("invalid mode %r" % mode)
> ValueError: invalid mode 'wb'
> c : fatal: server died with error code 1

Can i try something to get this fixed?
I'm trying to use this because i need to use a windows only vpn client, but i want to use my native linux desktop. The Windows is running within a VM.

**Comment by brianmay** [comment]
Looks like we should be using ``os.devnull`` not hard coding ``'/dev/null'``. No idea why it doesn't like 'wb' - possibly when the first problem is fixed this one will disappear also.

Pull requests appreciated :-)

**Comment by BlackDex** [comment]
Ah, okay, i have changed that now on a freshly git-clone. And i'm now getting the following error.

> c : Connected.
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "assembler.py", line 37, in <module>
>   File "sshuttle.server", line 282, in main
>   File "C:\Program Files\Python35-32\lib\socket.py", line 450, in fromfd
>     nfd = dup(fd)
> OSError: [WinError 10038] An operation was attempted on something that is not a socket
> c : fatal: server died with error code 1

If any ideas let me know :)

**Comment by brianmay** [comment]
Have you seen https://sshuttle.readthedocs.io/en/stable/windows.html ? In any case, I can't really help with Windows issues. Closing.

**Comment by brianmay** [comment]
Fixed by #918.
