### ISSUE TITLE
Allow subnets to be specified with domain names

### ISSUE THREAD

**Issue by DavidBuchanan314** [sshuttle/sshuttle#146]
I would be happy to make a PR for this.

IMHO the current implementation of subnet parsing is a mess. It could be massively simplified with the use of socket.getaddrinfo(), which can handle domain resolution, IPv4 and IPv6 addresses all at once - No need to reinvent the wheel, with regex.

**Comment by brianmay** [comment]
Pull requests are always appreciated. Just keep a watch for #144 that you don't step on @vieira's toes in the process.

**Comment by vieira** [comment]
That would be awesome. :+1:  
Can we work together on this so we don't have to write the tests and update the documentation twice? 

Also I think we can parse a subnet port string but not a subnet port range string as requested on #97 and implemented on #144. 

In any case, even if for parsing just addresses it would be very nice... I'll do some tests.

**Comment by DavidBuchanan314** [comment]
One slight hitch is that most domains resolve to both an IPv4 and IPv6 address (and maybe more than one of each). The simplest solution would be to only use the first IPv4 address, or the first IPv6 address if there are none, although that does seem a bit of a hack.

I notice `nmap` lets you do things like `nmap example.com/24`, so I'm going to take a look at how they handle things.

**Comment by DavidBuchanan314** [comment]
Here's a draft: https://github.com/DavidBuchanan314/sshuttle/commit/50ef55c5c91cd84892da43c19877b650d6468884

**Comment by vieira** [comment]
@DavidBuchanan314 Thanks! :+1:  I will pull those changes from you. I might have to slightly change it because of the new port/port-range support, but at the first sight looks good to me.

**Comment by brianmay** [comment]
What is the status of this issue?

**Comment by vieira** [comment]
Hello @brianmay 

This was merged, including the changes proposed by @DavidBuchanan314.

**Comment by brianmay** [comment]
Ok, closing this then.

**Comment by drewwells** [comment]
How does this work, did this get documented?
