### ISSUE TITLE
Remote server requires interaction before proxying

### ISSUE THREAD

**Issue by joesonw** [sshuttle/sshuttle#148]
I'm trying to use sshuttle to proxy through a jump server. However the jump server requires user interaction (keyboard input to select a machine to log in, like an url redirection). Will this be supported in the near future

**Comment by brianmay** [comment]
Pull requests appreciated.

**Comment by brianmay** [comment]
Implementing this is not going to be easy. Trouble is we use stdin/stdout to communicate with the python process on the remote machine, meaning stdin/stdout are not available for interactive use.

**Comment by normanr** [comment]
You could have ssh.connect's pyscript write its own synchronization header, and until it's received by connect, s2 would be proxied to stdin/stdout. Only once the pyscript synchronization header is received would content be sent to s2.

There's still an issue that the jump server might require a pseudo-tty, and I'm not sure how that might affect sshuttle's comms if ssh does allocate it.
