### ISSUE TITLE
Can't add FQDN via /etc/hosts

### ISSUE THREAD

**Issue by rubenfonseca** [sshuttle/sshuttle#151]
Hi, thank you so much for your awesome project!

I was trying to try to see if I could use sshuttle for connecting to my staging environment. So in my server machine, I've setup `/etc/hosts` with lines like:

```
api.foo.com 123.123.123.123
admin.foo.com 123.123.123.124
...
```

I was hopping that by `sshuttle -HNr server` I could than route request to `api.foo.com` and `admin.foo.com`. However, it seems that only `api` and `admin` hostnames are routed through the tunnel.

Is it possible to setup full qualified domain names instead of just hostnames?

Thank you very much in advance.

**Comment by vieira** [comment]
Hello @rubenfonseca,

While I can kind of imagine some use cases, I rarely use hostwatch and have no idea if this is something people usually need, or, on the other hand, something that will get on the way of some other users.

#173 should resolve this issue but I will let you and @brianmay decide if this is something worth merging.

**Comment by rubenfonseca** [comment]
Yes I think #173 fixes it. Thanks!
