### ISSUE TITLE
UDP support for pf

### ISSUE THREAD

**Issue by DanielO** [sshuttle/sshuttle#155]
Hi,
Is it possible to add support for UDP in the pf method?

If it's impossible what would need to be changed in pf to have it work?

Thanks.

**Comment by brianmay** [comment]
Patches welcome :-)

**Comment by DanielO** [comment]
I would be happy to although I was hoping for some hints :)
i.e. what are the missing parts? I did read somewhere (I forget exactly where now..) that there was an issue with PF not supplying enough information with UDP packets or some such.

**Comment by brianmay** [comment]
You need to be able to work out how to intercept UDP packets. You also need to be able to send responses back with the correct source IP address. Closing, as nothing I can do here.
