### ISSUE TITLE
Localhost requests getting picked up by sshuttle

### ISSUE THREAD

**Issue by skarip** [sshuttle/sshuttle#159]
Might be missing something obvious but in the version upgrade from 0.78.1 to 0.78.2 my requests to services on localhost are now getting proxied by sshuttle. Before I could listen with nc on a port and curl it locally, but after the upgrade, I just get an immediate empty response when I curl the port that I have nc running on and nc doesn't catch any requests.

It doesn't look like the exclude flags are affecting this either. Here's the command I use to sshuttle:
```sshuttle --dns -vvr SSH_HOST -x 127.0.0.1 0/0```

Is this expected? And if so, how can I proxy all my traffic excluding localhost over sshuttle?

**Comment by vieira** [comment]
Hello @skarip,

I was able to reproduce the problem with `sshuttle --dns -vvr SSH_HOST 0/0` (but not with the exclude flag, where it works as expected). I would swear that I tested this case some weeks ago and it was working properly but now it isn't.

What OS are you using? I am testing on Linux.

**Comment by jdstrunk** [comment]
I believe I'm also having this same issue on MacOS.  Currently running Yosemite.

This seemed to have started after commit ef83a5c5736341573c21b39e347f39f5387b6faa [ef83a5c]

Still trying to pin this down exactly what changed and what is the problem but I believe just like the original commenter, Localhost services are getting tunneled through sshuttle.  When I try to access any services like 1Password Mini service for example or other localhost services they are blocked.  I also don't' see any change or correction to that issue by adding in an exclude for 127.0.0.1 either as mentioned above.

**Comment by skarip** [comment]
@vieira Same as @jdstrunk I'm running on MacOS

**Comment by vieira** [comment]
I was able to reproduce this on El Capitan. #162 should fix it. Thanks!

**Comment by mr-bat** [comment]
Actually, I built the program via the latest commit so it means your PR is also included.

**Comment by mr-bat** [comment]
It's still present here.

**Comment by frantzmiccoli** [comment]
Using 0.78.4, I have observed this problem on Manjaro Linux (kernel 4.9.114) but not on MacOS 10.13.6.
