### ISSUE TITLE
DNS entries in /etc/hosts are still used

### ISSUE THREAD

**Issue by theilluminaughti** [sshuttle/sshuttle#161]
Version: 0.78.3

When using DNS tunneling via a SOCKS tunnel, the entries in /etc/hosts are ignored

However when doing DNS tunneling via sshuttle, the entries in /etc/hosts are NOT ignored. Does this mean that DNS queries are not being tunneled at all?

Ie. when connected via sshuttle, a /etc/hosts entry of
`0.0.0.0 www.facebook.com`
will still be obeyed

**Comment by brianmay** [comment]
Can you please provide more details? Are you using ``--auto-hosts``?

**Comment by theilluminaughti** [comment]
I'm not, no. Just using  --dns -r

**Comment by brianmay** [comment]
theilluminaughti <notifications@github.com> writes:

> I'm not, no. Just using  --dns -r

Can you please give more details?

Sshuttle itself doesn't use /etc/hosts unless you specify --auto-hosts.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by vieira** [comment]
Hello @theilluminaughti @brianmay 

I believe sshuttle will only intercept and redirect traffic going out (via firewall rules). 

If there is any traffic going out to some UDP/53 port it will get intercepted and tunneled. However when using `/etc/hosts` the name resolution is happening locally, there is no DNS traffic going out to any UDP/53 port so there is nothing to intercept and tunnel. Note that all other names (not explicitely defined in `/etc/hosts`) will be tunneled.

About DNS tunneling via SOCKS ignoring the `/etc/hosts` file, maybe that is a setting of the application you are using. For instance in Firefox, you can enable that in `about:config`, `network.proxy.socks_remote_dns`.

The only thing I can think of right now to do something like this is to backup `/etc/hosts` file when sshuttle starts, clear it, and restore on exit. This is similar to what is already done when `--auto-hosts` is used. However I cannot see any advantages of doing this. What do you have in mind?

**Comment by brianmay** [comment]
I am not convinced this is a sshuttle problem. `/etc/hosts` is being read by the client program, not by sshuttle, as per standard convention. Closing...
