### ISSUE TITLE
Point to this repo in the apenwarr & brianmay repos

### ISSUE THREAD

**Issue by stigkj** [sshuttle/sshuttle#165]
To make sure people get that this is where stuff happens, add something to the READMEs of these repos.

**Comment by brianmay** [comment]
I could update the brianmay respository.

Unfortunately, I do not have write access to the apenwarr respository.

**Comment by brianmay** [comment]
I just updated the github description for my repository. Please let me know if you don't consider this sufficient.

Closing this ticket, as while unsatisfactory, I do not have write access to the apenwarr repository. Suggestions on how to deal with this also appreciated.
