### ISSUE TITLE
Use SOCKS Proxy for ssh connection?

### ISSUE THREAD

**Issue by FlyWieEinAirplane** [sshuttle/sshuttle#166]
I am not sure if I understand it correctly but as far as I can tell my specific usecase is not supported yet.
I am trying to tunnel all of my traffic from my own pc over my pc at work to my server on the internet.
![network_picture](https://markenpm.com/resources/network_diagram.png)

For many things like browser stuff it is working already.
I am using the system settings for SOCKS proxies but there are applications that do not use the system settings.
So if I'm not wrong i would just need to get sshuttle working over the SOCKS proxy and then every applications traffic is tunneled?
please correct me if I'm beeing studid.

**Comment by brianmay** [comment]
FlyWieEinAirplane <notifications@github.com> writes:

> I am not sure if I understand it correctly but as far as I can tell my specific usecase is not supported yet.
> I am trying to tunnel all of my traffic from my own pc over my pc at work to my server on the internet.
> ![network_picture](https://picload.org/view/rwiolrli/network_diagram.png.html)
>
> For many things like browser stuff it is working already.
> I am using the system settings for SOCKS proxies but there are applications that do not use the system settings.
> So if I'm not wrong i would just need to get sshuttle working over the SOCKS proxy and then every applications traffic is tunneled?
> please correct me if I'm beeing studid.

I think I have understood you requirements.

Ssshuttle uses ssh, and AFAIK ssh doesn't support connection via a SOCKS
proxy. Meaning sshuttle will not work either.

This is not a stupid request, unfortunately I am not able to help you.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by LionsAd** [comment]
Here you go:

https://blog.yimingliu.com/2009/03/05/ssh-subversion-through-socks-proxy-on-mac-os-x/

(links to https://github.com/haad/proxychains)

This allows your SSH to use socks proxy. On Linux the same can be achieved using LD_PRELOAD.

**Comment by brianmay** [comment]
From the page you quoted:

> Due to the complete lack of updates for tsocks, I recommend the use of proxychains over tsocks. It accomplishes the same thing but works out of the box.

Is there any reason you can't/won't use proxychains as recommended?

I believe tsocks is very much legacy.

**Comment by brianmay** [comment]
Oops. Accidentally closed this bug.

If you still want this feature, and you can clarify that this is something sshuttle can address (pull request ideal!), then I will reopen.

**Comment by masters3d** [comment]
Can we reopen this? @brianmay 

ssh does support proxy connections. I am using it to connect to a linode box using a socks5 proxy.
https://github.com/sshuttle/sshuttle/issues/166#issuecomment-325316908

Currently sshuttle does not seem to honor this setting. 

`~/.ssh/config`
```
Host targethost
  ProxyCommand=nc -X 5 -x proxyserverip:port %h %p
```
I got this from here:
http://www.mikeheijmans.com/sysadmin/2014/08/12/proxy-ssh-over-socks/

**Comment by masters3d** [comment]
This is the workaround I found:

Replace the uppercase with your own set up. In this case the ssh server I am using is from Linode.
```
sudo sshuttle -r user@IPMYSSHSERVER 0/0 -e "ssh -o 'ProxyCommand=nc -X 5 -x IPMYPROXY:PORTMYPROXY %h %p'" --ns-hosts IPPROXYWITHDNS --dns

```

**Comment by brianmay** [comment]
I tend to think this is outside the scope of sshuttle. sshuttle itself does not parse ~/.ssh/config nor does it do anything (that I am aware of) to stop ssh from reading ~/.ssh/config. So first I would check that ssh works properly with the ProxyCommand by itself. If this works, then sshuttle should work too.

**Comment by masters3d** [comment]
I agree. The above works but only nc and macOS. I haven’t tested other modes or platforms.

**Comment by flybeach** [comment]
Hello @masters3d and @brianmay , maybe it will be possible to block the network when connection by sshuttle drops?

**Comment by brianmay** [comment]
@flybeach Please either ask on the mailing list <https://groups.google.com/forum/#!forum/sshuttle> or in a new bug report. This issue you added this to is about socks proxies, and is not relevant.
