### ISSUE TITLE
passwordless tunneling

### ISSUE THREAD

**Issue by xhudik** [sshuttle/sshuttle#169]
Hi, I'm accessing a machine via certificate ( ssh option*-i*); no passwords are allowed for the machine:
```
ssh -i machine_example.pem my_user@example.com
```
Can I also use *sshutle* with such passwordless approach, or I always need a proper user with password?
I tried
```
sshuttle -i machine_example.pem -r my_user@example.com 0.0.0.0/0 -vv
```
it failed since unknown `-i` option

**Comment by brianmay** [comment]
Tomas <notifications@github.com> writes:

> Hi, I'm accessing a machine via certificate ( ssh option*-i*); no passwords are allowed for the machine:
> ```
> ssh -i machine_example.pem my_user@example.com
> ```
> Can I also use *sshutle* with such passwordless approach, or I always need a proper user with password?
> I tried
> ```
> sshuttle -i machine_example.pem -r my_user@example.com 0.0.0.0/0 -vv
> ```
> it failed since unknown `-i` option

Use the --ssh-cmd option, e.g. (not tested):

sshuttle -e "ssh -i machine_example.pem" ...
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by xhudik** [comment]
unfortunately, no joy:
```
sshuttle -e "ssh -i machine_example.pem " -r my_user@example.com 0.0.0.0/0 -vvStarting sshuttle proxy.
[local sudo] Password: 

firewall manager: Starting firewall with Python version 3.5.3
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: False
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Starting client with Python version 3.5.3
c : connecting to server...
c : executing: ['ssh', '-i', 'machine_example.pem', '', 'my_user@example.com', '--', 'exec /bin/sh -c \'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=2; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(978), "assembler.py", "exec"))\'"\'"\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
ssh: Could not resolve hostname : No address associated with hostname
c : fatal: failed to establish ssh session (2)

```

**Comment by brianmay** [comment]
Tomas <notifications@github.com> writes:

> sshuttle -e "ssh -i machine_example.pem " -r my_user@example.com 0.0.0.0/0 -vvStarting sshuttle proxy.

Remove the space before the end quote.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by xhudik** [comment]
thank you!!!!
