### ISSUE TITLE
using --no-latency-control throws AssertionError

### ISSUE THREAD

**Issue by naclander** [sshuttle/sshuttle#18]
When I run <code> sudo ./sshuttle --dns --no-latency-control  -vvr user@server 0/0 </code> I see the following error:

<pre>
Starting sshuttle proxy.
UDP support requires tproxy; disabling UDP.
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
Binding DNS: 12300
DNS listening on ('127.0.0.1', 12300).
firewall manager ready method nat.
c : connecting to server...
c : executing: ['ssh', 'user@server', '--', 'P=python2; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys; skip_imports=1; verbosity=2; exec compile(sys.stdin.read(770), "assembler.py", "exec")\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
user@server's password: 
server: assembling 'cmdline_options.py' (39 bytes)
server: assembling 'helpers.py' (786 bytes)
server: assembling 'ssubprocess.py' (13698 bytes)
server: assembling 'ssnet.py' (5466 bytes)
server: assembling 'hostwatch.py' (2241 bytes)
server: assembling 'server.py' (3029 bytes)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 27, in <module>
  File "server.py", line 218, in main
AssertionError
c : fatal: server died with error code 1
</pre>

When searching for this error I found a related bug report [here](https://bugs.archlinux.org/task/45725)

I can confirm that running <code> sudo ./sshuttle --dns  -vvr user@server 0/0 </code> works fine for me.

**Comment by naclander** [comment]
It looks like the specific commit is line 218 in server.py added by Brian May.

**Comment by brianmay** [comment]
Does it work if you delete that line?

**Comment by naclander** [comment]
It does, however I assume line 219 will fail if ever reached when --no-latency-control is set.

**Comment by brianmay** [comment]
I assume you mean the print line. I don't see any reason why it should fail. Please test it, and if you get any errors, post them here. Thanks.

**Comment by naclander** [comment]
Ah, you were right, removing the line doesn't cause any errors after continuous usage. I'll go ahead and make a pull request.

**Comment by brianmay** [comment]
Closed via #19.
