### ISSUE TITLE
subnet parsing behavior changed in 0.78.2

### ISSUE THREAD

**Issue by mattrobenolt** [sshuttle/sshuttle#184]
Before, I used to be able to use shorthand such as:

```
sshuttle -r ... 192.168.208/20
```

Or:

```
sshuttle -r ... 10/8
```

And these would be expanded to `192.168.208.0/20` or `10.0.0.0/8` respectively.

Since https://github.com/sshuttle/sshuttle/commit/c4a41ada09ec6fbfeb1783eb0269cad013842982 it appears that this behavior has changed when piping the address through `socket.getaddrinfo`:

```
>>> socket.getaddrinfo('10', 0, 0, socket.SOCK_STREAM)
[(2, 1, 6, '', ('0.0.0.10', 0))]
```

`socket.getaddrinfo` seems to not zero fill on the right hand side like the old code used to do.

I'm not sure if this is intended/correct behavior, or if it just worked magically before by accident, but it seems like it'd be relatively easy to restore this behavior by padding the string with `.0`'s before passing into `socket.getaddrinfo`. I'll submit a PR to go along with this.

**Comment by mattrobenolt** [comment]
Looking a bit deeper, there's even a test that sorta is intending to test this behavior, but it works by chance:

https://github.com/sshuttle/sshuttle/blob/master/sshuttle/tests/client/test_options.py#L9

This is testing expansion of 10.0 -> 10.0.0.0, which does work, even with the bits flips.

We can demonstrate this better with the change in behavior when testing against `192.168.208/20`, we get expanded to `192.168.0.208` instead of `192.168.208.0` like I'd expect.

**Comment by vieira** [comment]
(Left some comments in #185)

**Comment by mattrobenolt** [comment]
Closing due to the explanation in #185.
