### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by hyandell** [sshuttle/sshuttle#186]
Just wanted to note that the LICENSE file says LGPL 2, the setup.py metadata says GPLv2+, and the source header on the setup.py file says GPLv3+.

Which is the correct licensing please?

**Comment by brianmay** [comment]
I forked this from https://github.com/apenwarr/sshuttle, and I don't own the copyright myself.

I believe the errors are entirely in the `setup.py` file - and probably made by me too. It looks like I copied the file from another project (python-tldap) and didn't notice the project specific stuff which is obviously wrong.

Curiously, apenwarr's repository contains the same errors.

**Comment by brianmay** [comment]
If I wasn't clear, I believe the true license is LGPL 2.

**Comment by brianmay** [comment]
Thanks for the report.

**Comment by brianmay** [comment]
Fix has been merged now. Closing.
