### ISSUE TITLE
Speed throttled ... possibly due to CPU ?

### ISSUE THREAD

**Issue by rsyncnet** [sshuttle/sshuttle#189]
Hello,

My personal Internet connection tests out at 50 down and 11 up.

My ssh endpoint that I use for sshuttle is on a 10gbe line from he.net.  Lots of bandwidth there.

However, when I run sshuttle, my results are 2.x megabits/s download OR if I enable --no-latency-control it rises up to 7.x megabits/s.

When I do this, I see the CPU on my sshuttle client device (a netgate APU) shoot all the way up to 100%.  In 'top' i see a single python process that is using 99% cpu time.

So, am I correct in concluding that I am speed limited due to the CPU on my system ?

Thank you.

**Comment by brianmay** [comment]
I don't think anybody has done any performance testing with sshuttle. I imagine ssh will be the limiting factor. This definitely is an area that needs more work.

Your results would appear to significantly be slower then what I would assume to be reasonable. What sort of system are you running sshuttle on (client and server)?

**Comment by rsyncnet** [comment]
client and server are *both* a pcEngines APU1D4:

http://www.pcengines.ch/apu1d4.htm

"CPU: AMD G series T40E, 1 GHz dual Bobcat core with 64 bit support, 32K data + 32K instruction + 512K L2 cache per core"

Comments ?

**Comment by rsyncnet** [comment]
I wonder if the system specs I mentioned above are interesting in any way ?

It's not a very powerful system but *should* be able to handle more than 7.x megabits/s in SSH traffic.

If that is correct, what would you suggest as the next line of troubleshooting ?

Thanks.

**Comment by brianmay** [comment]
rsyncnet <notifications@github.com> writes:

> If that is correct, what would you suggest as the next line of troubleshooting ?

Maybe test what performance you get from rsync over ssh or sftp/scp?

Regards
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by CzEMC** [comment]
I have noticed that when in double verbose mode, (-vv) speeds are significantly reduced. This is because time is taken to send messages to stdout.

**Comment by rsyncnet** [comment]
OK, I can confirm this is a CPU issue on the "server side" - that is, not the system that sshuttle runs on, but the sshd server that you point it to.

The pcEngines APU1D4 device I run my sshd on, with a "AMD G series T40E, 1 GHz dual Bobcat core with 64 bit support" maxes out at 7mb/s (but typically runs at 2-4 mb/s) and when I am connected, the single python process on the sshd server side maxes out at 100% of a CPU.

I tried pointing to a Celeron(R) CPU  N2807  @ 1.58GHz (1583.37-MHz K8-class CPU) and the results were not that much different, which makes sense as that is a fairly weak, old celeron chip.

But then I pointed to an sshd running on a CPU: Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz (2400.05-MHz K8-class CPU) and the speed increased all the way up to 22mb/s.  The single python process running on the sshd server ramps up to 50% of a CPU when I stress the connection.

So the speed of the CPU on the sshd server side matters quite a bit AND it needs to be a fairly new and powerful CPU - network devices like the APU or little router boards will not work.

My question:

The APU device I use has dual cores and is compiled with an SMP kernel ... but I think python does not support threading for workloads like this ?  I think I could at least double the speed on these weaker devices if there were a way to split the workload between more than one python thread ...

Thanks.

**Comment by brianmay** [comment]
Thanks for this.

It concerns me that the load on the sever is much higher on the server then the client. Both processes should be doing the same thing - listen on select and then copy data between a TCP socket and a ssh socket.

If load is much higher on the server, this might suggest that there is a bug in the code. Some sort of profiling might identify the problem.

Multi-threading is unlikely to help here, as this isn't a workload that can be easily split up. Particularly as we have no idea where the bottleneck is yet either.

Regards

**Comment by brianmay** [comment]
For that matter, the select loop processing is highly complex, and I don't think anybody has actually tested it apart from "it appears to work". So it is very possible it could have performance related bugs.

If I was rewriting this code I would probably try to use asyncio code, but of course this would break Python 2.x support.

**Comment by rsyncnet** [comment]
I can quickly toggle between several different performance classes of CPU ... if you can tell me what to try, or how to debug, I would be happy to do it ...

I also did a few more tests just to make sure I was controlling variables and it seems fairly conclusive - nothing different in the sshd endpoints other than speed of CPU, and that makes a dramatic difference in throughput.

I have always noticed sshuttle throughput drops over time - long running instances get slower and slower the longer they run - so I tested with brand new instances and the speed difference was 7mb/s vs 35mb/s on brand new, restarted instances of sshuttle on the server side ...

**Comment by brianmay** [comment]
Somebody contacted me via private email saying after time they have a large number of sockets in `CLOSE_WAIT` after running sshuttle for a while. Might be related to the current (probably bad) policy of waiting for the Python Garbage collector to clean up closed connections. This might explain why performance drops over time?

**Comment by rsyncnet** [comment]
I have no idea - I think it is a secondary issue in comparison to the throughput issues ... let me know what tests, if any, I can do for you ...

**Comment by rsyncnet** [comment]
As long as we're talking about these items ...

I would like to also point out that sshuttle appears to deal very poorly with load balancing multiple connections.

That is, if one client (or browser tab, or "update" process) is using a lot of bandwidth, there is often *zero* bandwidth available to other processes.  Other processes are not merely slow, they are completely starved for bandwidth - even if they are older than the process that is hogging all the bandwidth.

So for instance, if you are running sshuttle as a network gateway (like I do) you might have 2-3 client systems running Internet traffic through the gateway and as long as nobody needs a lot of bandwidth, they seem to play together nicely.

But then, let's say one of those clients (an apple laptop) decides to do a software update, then you'll see a new connection to aaplimg.com (for instance) using ALL available bandwidth and no other Internet access is possible.  Every other new connection will simply time out until the bandwidth hog is finished.

**Comment by brianmay** [comment]
Moving this to #272.
