### ISSUE TITLE
Adding support for resolving mDNS (.local)

### ISSUE THREAD

**Issue by prankymat** [sshuttle/sshuttle#190]
It'd be nice if a machine can resolve `xxx.local` on the connected remote network with `sshuttle`.

Example usage:
```
> sshuttle --mdns -r pi@remote.network 0/0
client: Connected.

> ping raspberrypi.local
PING raspberrypi.local (192.168.1.22): 56 data bytes
64 bytes from 192.168.1.22: icmp_seq=0 ttl=59 time=20.467 ms
```

Currently `sshuttle` cannot forward mDNS requests / results, so the ping in the example above would simply be time outs since the IP can't be resolved.

**Comment by vieira** [comment]
@prankymat @brianmay Does this work with --method tproxy?

**Comment by brianmay** [comment]
João Vieira <notifications@github.com> writes:

> @prankymat @brianmay Does this work with --method tproxy?

No idea.

I suspect maybe not, I haven't really investigated multicast in anyway,
and I believe mDNS uses multicast queries.

I am not really that familiar with mDNS however, so might be mistaken.

It would be really good to add mDNS support to sshuttle, however I don't
have any time to investigate if this is possible or what it would
require.

It is possible that sshuttle would need to listen to incoming mDNS
requests, somehow filter out which ones it needs to process, and forward
them, like it does for DNS.

Pull requests welcome!
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by brianmay** [comment]
I suspect this might be difficult to implement, because sshuttle only forwards requests in one direction. Where as something like mdns wants to be send data in both directions. Closing for now.
