### ISSUE TITLE
--auth-hosts/--seed-hosts strips domain

### ISSUE THREAD

**Issue by peay** [sshuttle/sshuttle#199]
I am using `--seed-hosts` with domains of the form `some.subdomain.search.domain`. Although this works, it only updates `/etc/hosts`with records of the form

```
1.2.3.4 some
```

instead of including the full original hostname that was resolved.

I've tracked it down to a couple regex statements in `found_host`, and the following patch seems to work:

```diff
diff -ruN sshuttle/client.py sshuttle/client.py
--- sshuttle/client.py   2018-02-02 18:04:20.000000000 +0100
+++ sshuttle/client.py    2018-02-02 18:05:13.000000000 +0100
@@ -286,7 +286,7 @@
             raise Fatal('%r expected STARTED, got %r' % (self.argv, line))

     def sethostip(self, hostname, ip):
-        assert(not re.search(b'[^-\w]', hostname))
+        assert(not re.search(b'[^.-\w]', hostname))
         assert(not re.search(b'[^0-9.]', ip))
         self.pfile.write(b'HOST %s,%s\n' % (hostname, ip))
         self.pfile.flush()
diff -ruN sshuttle/hostwatch.py sshuttle/hostwatch.py
--- sshuttle/hostwatch.py    2018-02-02 18:04:20.000000000 +0100
+++ sshuttle/hostwatch.py 2018-02-02 18:04:50.000000000 +0100
@@ -68,8 +68,6 @@


 def found_host(hostname, ip):
-    hostname = re.sub(r'\..*', '', hostname)
-    hostname = re.sub(r'[^-\w]', '_', hostname)
     if (ip.startswith('127.') or ip.startswith('255.') or
             hostname == 'localhost'):
         return
```

However, I am worrying it'll break other things, and I wonder what the original reason was to only keep the hostname. Is there another workaround I missed? Awesome tool by the way.

cc @apenwarr

**Comment by brianmay** [comment]
Unfortunately, I have no idea why it was done this way, and this isn't a feature I make use of myself.

If you were to make a pull request, I would seriously consider merging it however.

**Comment by twinshadow** [comment]
Commit 29cd75b6 fixed this issue.

**Comment by twinshadow** [comment]
Version from the client:
```
# sshuttle -V
0.78.6.dev8+g71f2248.d20190910
```


On the remote host:
```
# cat .sshuttle.hosts 
gate,192.168.32.1
gate.lan.tshd.ws,192.168.32.1
tutti,192.168.32.5
tutti.lan.tshd.ws,192.168.32.5
```
