### ISSUE TITLE
New Mac build?

### ISSUE THREAD

**Issue by mattfrankly** [sshuttle/sshuttle#205]
Excellent software. I'm using the CLI version, but it would be nice to have an updated Mac GUI client.

How do I build a new version of the GUI client for Mac?

Thanks!
-Matt

**Comment by brianmay** [comment]
Sorry, There currently is no GUI client for Mac. Perhaps there was sometime in the past, but it wasn't getting used or maintained so I removed it. If somebody were willing to maintain it, I would consider a PR to add it again.
