### ISSUE TITLE
I get lots of read error on my tunnel

### ISSUE THREAD

**Issue by arminmacx** [sshuttle/sshuttle#209]
Hey guys.

I have a Mac with makes high sierra installed and I installed shuttle with brew and run the shuttle with this command:

sshuttle --dns -vvvr root@x.x.x.x:1234 0/0

Everything works but i get lots of error in terminal like this :

 read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : Waiting: 31 r=[4, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 24, 25, 26, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46] w=[] x=[] (fullness=15453/0)
c :   Ready: 31 r=[16] w=[] x=[]
c :  > channel=423 cmd=TCP_DATA len=654 (fullness=15453)
c : read: err was: [Errno 35] Resource temporarily unavailable
c : Waiting: 31 r=[4, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 24, 25, 26, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46] w=[9] x=[] (fullness=16107/0)
c :   Ready: 31 r=[] w=[9] x=[]
c : mux wrote: 662/662
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable
c : read: err was: [Errno 35] Resource temporarily unavailable

and one other question and how can i share my sshuttle from mac to my other devices on same network. I know maybe i search less and ask it but can you point me in good direction for this.

if you need any info tell me i will provide it as much as i can # #

**Comment by brianmay** [comment]
The "error" is nothing to worry about, it is just a level 3 debugging message that appears because we use non blocking sockets and we print this when we get `EAGAIN`.

Having said that I am not very familiar with this part of the code.

The other question, as it isn't a bug report, and isn't related to this bug report. It might be better posting this in the sshuttle forum at: https://groups.google.com/forum/#!forum/sshuttle

**Comment by arminmacx** [comment]
Im sorry to reopen this again but i have another question. Is there anyway to use tproxy on mac with sshuttle? if yes how?

**Comment by brianmay** [comment]
It is possible to use on OSX, however I personally have not had any experience with it on OSX.
