### ISSUE TITLE
Mac app sudo prompt isn't working

### ISSUE THREAD

**Issue by kergoth** [sshuttle/sshuttle#21]
I'm on El Capitan, if that matters, but I'm running into an issue where the sudo prompt in the Mac GUI isn't working correctly. I input the correct password for it, but it then hangs, not proceeding to connect. If I drop to a terminal and manually sudo something, then try again, it works since it doesn't need to prompt at that point.

**Comment by thshdw** [comment]
Would you be able to share your command? I use sshuttle every day and have had zero issues with 10.11

~~~
thshdw-pc:~ thshdw$ cd ~/Documents/sshuttle-master/src/
thshdw-pc:src thshdw$ ./sshuttle --dns -H -vvr thshdw@123.6.78.23 0/0
~~~

That is how I run sshuttle on the mac. After I run that I see:

~~~
Starting sshuttle proxy.
UDP support requires tproxy; disabling UDP.
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
Binding DNS: 12300
DNS listening on ('127.0.0.1', 12300).
[local sudo] Password: 
~~~
then 
~~~
firewall manager ready method pf.
c : connecting to server...
c : executing: ['ssh', 'thshdw@123.6.78.23', '--', 'P=python2; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys; skip_imports=1; verbosity=2; exec compile(sys.stdin.read(770), "assembler.py", "exec")\'']
~~~

**Comment by thshdw** [comment]
ah... I re-read your post.. your using the Mac GUI. Try downloading the latest source and run the command from terminal as in my example. I'm not sure the GUI app is working anymore. On the releases page the last binary was dated Jul 6, 2012. If you need a GUI I recommend using http://fitztrev.github.io/shuttle/ this will launch sshuttle in a terminal window.

**Comment by kergoth** [comment]
Yeah, the mac UI. If it's not working, it should likely be marked as such, or removed. That said, it does work fine if you get past the sudo hang.

**Comment by thshdw** [comment]
@brianmay How would you feel about officially dropping support / removing the binaries for the OS X GUI? Seems like the best thing for the project. There are other tools for mac that can launch terminal windows with a given command.

**Comment by brianmay** [comment]
It doesn't bother me either way. I don't use OS X.

My preference however is to deleting broken code if nobody is interested in fixing it, and if somebody does want to fix it in the future, it is available in git and can be resurrected.

**Comment by thshdw** [comment]
Thanks! As an OS X user what matters to me is terminal support. Currently sshuttle is working in 10.11 when launched from terminal. 

As @brianmay does not have OS X to test GUI's; It makes sense that they be removed from the releases page.

**Comment by brianmay** [comment]
Unfortunately, I don't think it is possible to remove old releases from the releases page, as github automatically derives that from the git tags. It doesn't make sense to remove the git tag, as anyone who resurrects will need to find the last release,  and the git tag is the standard way of doing this.

So I can see your concern, not so easy to deal with however. Hopefully it should be obvious to people downloading that version that it is very old.

On the other hand, if there is broken GUI code in the git repository, that can get deleted. Documentation can also get added to the latest release to say that this is not supported.
