### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by Areso** [sshuttle/sshuttle#210]
I have 14.04 LTS 32 bit. On server 14.04 LTS 64 bit
sshuttle 0.78.4 version.
I have a Google Cloud instance with ssh keys.
I can successfully connect via ssh
ssh mylocalusername@googlecloudip
But 
sudo sshuttle -r mylocalusername@googlecloudip 0.0.0.0/0 -vv
returns
Permission denied (publickey)
What did I wrong?

**Comment by brianmay** [comment]
You are using sudo, which means sshuttle is running as root. Remove the sudo call, and sshuttle can call sudo itself and ssh can run as your normal user with full access to your ssh keys.

**Comment by ttpro1995** [comment]
how to use sudo while still have access to ssh key 

`sudo sshuttle -r tthien@139.59.193.235 0.0.0.0/0 -vv`

**Comment by brianmay** [comment]
Drop the sudo. sshuttle will use sudo as it needs (sudo is required for tproxy, but you are not using it).
