### ISSUE TITLE
python: not found on pfsense

### ISSUE THREAD

**Issue by dhia-eddine** [sshuttle/sshuttle#216]
sshuttle connecting to pfsense 2.4.2-RELEASE-p1 gives
`exec: python: not found`
workaround: python 2.7 is already installed but only accessible as python2 or python2.7
`ln -s /usr/local/bin/python2.7 /usr/local/bin/python`

**Comment by CSstefan** [comment]
Ran into same issue and did the same workaround.  If would be great if sshuttle could try using 'python2' (symlink already present on pfSense) if 'python' is not found.

**Comment by CSstefan** [comment]
Another solution is to pass the  --python=python2 parameter to sshuttle.

**Comment by CSstefan** [comment]
the **--python=python** parameter seems to be the best solution for anyone using pfsense.

**Comment by brianmay** [comment]
Ok, sure. If anybody wants to create a pull request to update the documentation, I would be happy to accept. For now closing.
