### ISSUE TITLE
Extraneous sshuttle.egg-info directory with wrong permissions on PyPI tarball

### ISSUE THREAD

**Issue by dan-santana** [sshuttle/sshuttle#217]
The title says it all: the [tarball provided on PyPI](https://files.pythonhosted.org/packages/source/s/sshuttle/sshuttle-0.78.4.tar.gz) contains a  `sshuttle.egg-info` directory with wrong permissions (0600) on its files. 

It seems that this directory should be generated during the `setup.py build` instead of being present in the tarball, as it can break system-wide installations due to the wrong permissions on the egg files (making **every** python application unavailable for users without the ownership of these files, that usually is `root`).

**Comment by brianmay** [comment]
I believe it is standard practise to include the `sshuttle.egg-info`. That is, it isn't something I do, but something that setuptools does that is common for all packages on pypi.

If files have incorrect/broken tools, this seems like setuptools is broken when generating the source; will try to investigate.

**Comment by dan-santana** [comment]
In fact, I didn't check enough packages to confirm my affirmation, but it seems that some packages does (like [Django](https://files.pythonhosted.org/packages/source/D/Django/Django-2.0.3.tar.bz2)), others doesn't (like [numpy](https://files.pythonhosted.org/packages/0b/66/86185402ee2d55865c675c06a5cfef742e39f4635a4ce1b1aefd20711c13/numpy-1.14.2.zip) and [pycups](https://files.pythonhosted.org/packages/source/p/pycups/pycups-1.9.73.tar.bz2)).

So I believe the only problem is with the 600 permissions (instead of 644) on `sshuttle.egg-info/*`.

**Comment by rbtcollins** [comment]
Permissions during installation is up to pip to get right, so I'd verify that @dan-santana is using pip, and then redirect this bug over there. (The reason its pips issue is that pip will make a wheel and install the wheel, and the wheel is a zip, without any permission info.

**Comment by dan-santana** [comment]
I'm not using pip in this setup. Let me provide the exact steps I'm using so you can reproduce the issue:

```sh
mkdir -p /tmp/src /tmp/build
cd /tmp/src

curl -ORL https://files.pythonhosted.org/packages/source/s/sshuttle/sshuttle-0.78.4.tar.gz
tar xf sshuttle-0.78.4.tar.gz
cd sshuttle-0.78.4

python3.6 setup.py build --build-base=build-3.6 install --prefix=/usr --root=/tmp/build/python-sshuttle-0.78.4
ls -l /tmp/build/python-sshuttle-0.78.4/usr/lib/python3.6/site-packages/sshuttle-0.78.4-py3.6.egg-info/
```

This is a simplified version of the package for Void Linux I'm writing for sshuttle ([here is the full source](https://gist.github.com/dan-santana/7bc45f95c266aac6993e3025d9406fa6)). In the last `ls` output of the snippet above, the 0600 permissions are what I believe is wrong (as they will be used on the system-wide installation of the Void package, or even a direct installation if I didn't choose a different `--root`).

**Comment by brianmay** [comment]
I have been told that "packaging permissions are an installation problem, and setup.py
is (no longer) intended for installation".

As a result, I think you will need to correct the permissions yourself after calling setup.py build. Possibly you might also need to ensure that the owner/group is correct too (not sure here).

This is what happens for Debian packages. Debian provides a tool to fix all permissions automatically at build time. I can't comment on Void Linux.

**Comment by jwilk** [comment]
This smells like a bug in setuptools. (I would expect a decent build system to install stuff as world-readable, regardless of what the permissions in source are.)

Anyway, if you want to generate sdists with 644/755 mode, you can use my [distutils644](https://github.com/jwilk/distutils644).

**Comment by brianmay** [comment]
If you think this is a setuptools bug, you are welcome to try and convince them of this: https://github.com/pypa/setuptools/issues.

**Comment by dan-santana** [comment]
> [...] and setup.py is (no longer) intended for installation".

@brianmay idk if I agree on that, as it seems many Linux distros explicitly rely on `setup.py install`
to build Python packages (e.g. [Arch Linux](https://wiki.archlinux.org/index.php/Python_package_guidelines), [Gentoo](https://wiki.gentoo.org/wiki/Project:Python/distutils-r1#distutils-r1_python_install), [Ubuntu & Debian](https://wiki.debian.org/Python/LibraryStyleGuide), and others).

After some Googling I noticed that this kind of issue seems to have apeared from time to time in many projects for **years**. Here are some examples:
  * https://github.com/paxan/python-dateutil/issues/2
  * https://github.com/PyTables/PyTables/issues/488
  * https://github.com/healpy/healpy/issues/220
  * https://www.raspberrypi.org/forums/viewtopic.php?t=175398
  * https://trac.macports.org/ticket/43187

... so I'm impressed that people have had this issue for so long, and yet the issue persists. I couldn't even find many related issues on https://github.com/pypa/setuptools/issues, and the few I found didn't explicitly talk about the situation related here. I can only assume that 1) no one has reported it; 2) this "keep file permissions" thing is by design; or 3) I need to improve my Google-fu.

Anyway, I agree that installation permissions should be solved by setuptools, so I'll report the issue on https://github.com/pypa/setuptools before continuing the discussion here.

**Comment by brianmay** [comment]
Nothing to do here. Closing.
