### ISSUE TITLE
DNS forwarding is really naive

### ISSUE THREAD

**Issue by Pikaro** [sshuttle/sshuttle#218]
DNS forwarding just appears to take your own configured servers and forward requests to them to the remote network. I have a caching DNS server locally, and

iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.8.15.1/32 -p udp --dport 53 --to-ports 12299 -m ttl ! --ttl 42

is bound to lead to some funny results. With some constellation of nets, this could also lead to unfunny results. So please refuse forwarding local servers at least.

Ideally, it would be nice to be able to specify what domains you want to be looked up by the remote machine's resolver, but I'm not sure if that's really possible to do in a clean and transparent way. (E. g. if you're connecting to a network with an internal DNS, that'd be immensely helpful.)

**Comment by brianmay** [comment]
I don't think there is anything to do here. Closing.

**Comment by brianjmurrell** [comment]
I disagree.  You closed #260 in favour of this one and now you close this one leaving no issues open regarding the problems with the naive DNS redirection.

More than one person is reporting issues with the DNS lookup redirection so at least one of these issues should remain open.

**Comment by brianmay** [comment]
This issue appears to be because the user used the `--dns` option incorrectly. There was no response to the question asked anyway. Will followup for #260 in that issue.
