### ISSUE TITLE
Exclusion flags not working

### ISSUE THREAD

**Issue by jcoetzee** [sshuttle/sshuttle#22]
I'm trying to exclude private IPs from being forwarded over sshuttle but I can't seem to get it right. Running sshuttle with `sshuttle -r server -x 10.0.0.0/8 -x 172.16.0.0/12 -x 192.168.0.0/16 0/0` however if I turn debug logging on then `Connecting to 10.144.180.135:443` shows up.

This is on OS X 10.11 which obviously uses PF. I don't know PF so I'm not sure what commands to run to check that it's been setup with the correct exclusions. Let me know if there's any other information needed.

**Comment by brianmay** [comment]
Sorry, I can't help you here as I don't have OS X. Suspect you will need to run pfctl commands to list the tables shuttle creates and check if they look correct.

**Comment by thshdw** [comment]
@brianmay If the community could donate a mac for your testing purposes; would you be open to debugging mac issues?

**Comment by seanzxx** [comment]
@jcoetzee I cannot reproduce your issue on my OS X 10.11.1. 
I ran the sshuttle with ./sshuttle -v -r server -x 10.0.0.0/8 -x 172.16.0.0/12 -x 192.168.0.0/16 0/0

then I opened a new window and ran two nc command:
nc 10.144.180.135 443 
nc 11.144.180.135 443

In the sshuttle log, I can only see:
c : Accept TCP: 10.224.225.101:49927 -> 11.144.180.135:443.
 s: warning: closed channel 1 got cmd=TCP_STOP_SENDING len=0
 s: SW'unknown':Mux#1: deleting (1 remain)
 s: SW#6:11.144.180.135:443: deleting (0 remain)


Did you install the sshuttle through homebrew?  The brewed version doesn't include several patches to fix the exclusion issue.

**Comment by seanzxx** [comment]
@jcoetzee You can try these commands to check the pf rules. 
> sudo pfctl -a sshuttle -s nat 2>/dev/null
rdr pass on lo0 inet proto tcp from any to <forward_subnets> -> 127.0.0.1 port 12300

> sudo pfctl -a sshuttle -s rules 2>/dev/null
pass out route-to lo0 inet proto tcp from any to <forward_subnets> flags S/SA keep state

> sudo pfctl -a sshuttle -s Tables 2>/dev/null
forward_subnets

> sudo pfctl -a sshuttle -t forward_subnets -Tshow 2>/dev/null
   0.0.0.0/0
  !10.0.0.0/8
  !127.0.0.0/8
  !172.16.0.0/12
  !192.168.0.0/16

**Comment by jcoetzee** [comment]
@seanzxx Ah yes, I did install via Homebrew; my sshuttle creates include_subnets and exclude_subnets not forward_subnets. Are there plans to tag a new release with these fixes incorporated?

**Comment by seanzxx** [comment]
@jcoetzee I think the temporary solution is to install HEAD version. 
```brew install --HEAD sshuttle```

**Comment by brianmay** [comment]
Did you want me to tag the master HEAD with sshuttle-0.72?

**Comment by jcoetzee** [comment]
@brianmay Not specifically, was just wondering if there were short term plans to tag a new release, I don't mind tracking HEAD if it solves my problem, just would prefer tracking some sort of beta release schedule.

**Comment by jcoetzee** [comment]
@seanzxx Thanks Sean, tracking HEAD solves my problem for now.

**Comment by brianmay** [comment]
There is no release schedule. Last release was in April, I think we might be overdue for another release. Unless there are any objections, I will tag a new release.

**Comment by jcoetzee** [comment]
@brianmay Schedule was the wrong word, just meant I'd prefer to follow tagged releases. Thanks for helping me out, I'm gonna close this issue out.

**Comment by brianmay** [comment]
Just tagged sshuttle-0.72. So this should be OK now.

**Comment by brianmay** [comment]
@thshdw Just realized I still hadn't answered your question concerning the donation of the Mac. Unfortunately, not having the hardware is just one part of the problem, not having the time is the other hurdle... There are a lot of things that need to happen with sshuttle too, not just OSX specific stuff.

**Comment by thshdw** [comment]
@brianmay Thanks for the reply. I completely understand. If you feel it would help in providing OS X benefits to the project; I'm willing to donate a mac. It's older but is perfect for testing. On my github profile is my email. If your interested, contact me with the the shipping address. 

Regarding OS X specific stuff... I'm perfectly fine with launching from the command line. I fee that the GUI's and installed packages just take more of your time and at unnecessary bloat. I'm not sure how other OS X users feel but for me sshuttle working on OSX is what matters. :smile:
