### ISSUE TITLE
NetworkManager integration

### ISSUE THREAD

**Issue by andreas-h** [sshuttle/sshuttle#220]
I think it would be great if there were a NetworkManager plugin for sshuttle.  Unfortunately, I don't have any experience with writing code for NetworkManager.

Maybe someone here has an idea what would need to be done?  I am happy to do most of the work myself, but would appreciate some pointers on how to get started.

**Comment by brianmay** [comment]
Pull requests to add NetworkManager support appreciated. In the mean time, closing this, as I don't have the resources to do this myself.
