### ISSUE TITLE
regression 0.78.4 on mac 

### ISSUE THREAD

**Issue by davidkarlsen** [sshuttle/sshuttle#221]
0.78.4 is broken for me on my mac:
uname -a
Darwin Davids-Work-MacBook-Pro.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
Davids-Work-MacBook-Pro:sshuttle et2448$ 

let me know what more debug you need.

0.78.3 works fine.

**Comment by davidkarlsen** [comment]
Davids-Work-MacBook-Pro:bin et2448$ sshuttle -v --dns -l 0.0.0.0 --pidfile /tmp/sshuttle.pid -r myuser@remotehost $(cat /etc/cos)
Starting sshuttle proxy.
[local sudo] Password:
firewall manager: Starting firewall with Python version 2.7.10
firewall manager: ready method name pf.
IPv6 enabled: False
UDP enabled: False
DNS enabled: True
User enabled: False
TCP redirector listening on ('0.0.0.0', 12300).
DNS listening on ('0.0.0.0', 12299).
Starting client with Python version 2.7.10
c : connecting to server...
XXXXX password:
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
Starting server with Python version 2.7.5
 s: latency control setting = True
 s: available routes:
 s:   2/10.158.136.64/27
 s:   2/XXXXX/24
 s:   2/XXXX/24
 s:   2/XXXX/27
 s:   2/XXXX/24
c : Connected.
firewall manager: setting up.
>> pfctl -s Interfaces -i lo -v
>> pfctl -s all
>> pfctl -a sshuttle-12300 -f /dev/stdin
>> pfctl -E
c : DNS request from ('127.0.0.1', 65135) to None: 39 bytes
c : DNS request from ('127.0.0.1', 4811) to None: 33 bytes
c : DNS request from ('127.0.0.1', 22076) to None: 34 bytes
c : DNS request from ('127.0.0.1', 22481) to None: 33 bytes

c : DNS request from ('127.0.0.1', 59022) to None: 53 bytes
c : DNS request from ('127.0.0.1', 62244) to None: 40 bytes


but when I ssh:

ssh 153.110.197.211 -vv
OpenSSH_7.6p1, LibreSSL 2.6.2
debug1: Reading configuration data /Users/et2448/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to XXXXX port 22.

nothing appears in the sshuttle log, and I cannot connect.
If I downgrade to 0.78.3 it works fine

**Comment by davidkarlsen** [comment]
@anacrolix Anything else I can provide?

**Comment by anacrolix** [comment]
I was trying to determine if my issue is related to yours.

**Comment by geyanev** [comment]
I stumble across similar issue on my MacOS Mojave. Only DNS request are passing through the sshuttle. I didn't have problems on MacOS Sierra or High Sierra.

I've tried different ssh servers, different client and server python versions. 2.7.15, 3.7.. Different sshuttle versions -  0.75.3, 0.75.4, 0.75.5 -  no success.

For yet unknown reasons to me it worked one time. I was trying different thinks so not sure what exactly fix it and so far I'm unable to reproduce it.

Here's an output:

```sshuttle --dns -r house 0/0 -v
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.7.0
firewall manager: ready method name pf.
IPv6 enabled: True
UDP enabled: False
DNS enabled: True
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening on ('127.0.0.1', 12300).
DNS listening on ('::1', 12300, 0, 0).
DNS listening on ('127.0.0.1', 12300).
Starting client with Python version 3.7.0
c : connecting to server...
Starting server with Python version 2.7.15rc1
 s: latency control setting = True
 s: available routes:
 s:   2/10.10.253.0/24
c : Connected.
firewall manager: setting up.
>> pfctl -s Interfaces -i lo -v
>> pfctl -s all
>> pfctl -a sshuttle6-12300 -f /dev/stdin
>> pfctl -E
>> pfctl -s Interfaces -i lo -v
>> pfctl -s all
>> pfctl -a sshuttle-12300 -f /dev/stdin
>> pfctl -E
c : DNS request from ('192.168.155.47', 57590) to None: 51 bytes
c : DNS request from ('192.168.155.47', 56353) to None: 51 bytes
c : DNS request from ('192.168.155.47', 63701) to None: 76 bytes
c : DNS request from ('192.168.155.47', 61387) to None: 49 bytes
```

```
curl -v https://google.com
* Rebuilt URL to: https://google.com/
*   Trying 172.217.17.206...
* TCP_NODELAY set
```

**Comment by craigwatson** [comment]
I can verify this bug - 0.78.4 gets no traffic, but 0.78.3 works fine.

Logs from 0.78.3:

```sshuttle -vv -r x.x.x.x 10.132.15.0/24
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.7.3
firewall manager: ready method name pf.
IPv6 enabled: True
UDP enabled: False
DNS enabled: False
Binding redirector: 12300
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 12300, 0, 0)>.
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Starting client with Python version 3.7.3
c : connecting to server...
c : executing: ['ssh', 'x.x.x.x', '--', 'exec /bin/sh -c \'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=2; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(978), "assembler.py", "exec"))\'"\'"\'\'']
Warning: Permanently added 'x.x.x,x.x.x.x' (ECDSA) to the list of known hosts.
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling u'sshuttle' (7 bytes)
server: assembling u'sshuttle.cmdline_options' (44 bytes)
server: assembling u'sshuttle.helpers' (950 bytes)
server: assembling u'sshuttle.ssnet' (5624 bytes)
server: assembling u'sshuttle.hostwatch' (2367 bytes)
server: assembling u'sshuttle.server' (3558 bytes)
Starting server with Python version 2.7.15rc1
 s: latency control setting = True
 s: available routes:
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s:  > channel=0 cmd=ROUTES len=0 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 8/8
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=7/0)
c : Connected.
c : Waiting: 2 r=[5, 7, 9] w=[9] x=[] (fullness=7/0)
c :   Ready: 2 r=[9] w=[9] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=0
firewall manager: Got subnets: [(2, 24, False, '10.132.15.0', 0, 0), (2, 32, True, '127.0.0.1', 0, 0), (30, 128, True, '::1', 0, 0)]
firewall manager: Got nslist: []
firewall manager: Got ports: 12300,12300,0,0
firewall manager: Got udp: False
firewall manager: setting up.
firewall manager: setting up IPv6.
>> pfctl -s Interfaces -i lo -v
>> pfctl -s all
>> pfctl -a sshuttle6-12300 -f /dev/stdin
>> pfctl -E
firewall manager: setting up IPv4.
>> pfctl -s Interfaces -i lo -v
>> pfctl -s all
>> pfctl -a sshuttle-12300 -f /dev/stdin
>> pfctl -E
c : mux wrote: 15/15
c : mux wrote: 15/15
c : Waiting: 2 r=[5, 7, 9] w=[] x=[] (fullness=14/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=7)
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=0/0)
c :   Ready: 2 r=[9] w=[] x=[]
c : <  channel=0 cmd=PONG len=7
c : received PING response
c : Waiting: 2 r=[5, 7, 9] w=[] x=[] (fullness=0/0)```

Logs from (broken) 0.78.4:

```
sshuttle -vv -r x.x.x.x 10.132.15.0/24
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.7.3
firewall manager: ready method name pf.
IPv6 enabled: True
UDP enabled: False
DNS enabled: False
User enabled: False
Binding redirector: 12300
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 12300, 0, 0)>.
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Starting client with Python version 3.7.3
c : connecting to server...
c : executing: ['ssh', 'x.x.x.x', '--', 'exec /bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=2; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1082), "assembler.py", "exec"))\'"\'"\'\'']
Warning: Permanently added 'x.x.x,x.x.x.x' (ECDSA) to the list of known hosts.
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling 'sshuttle' (7 bytes)
server: assembling 'sshuttle.cmdline_options' (62 bytes)
server: assembling 'sshuttle.helpers' (944 bytes)
server: assembling 'sshuttle.ssnet' (5647 bytes)
server: assembling 'sshuttle.hostwatch' (2386 bytes)
server: assembling 'sshuttle.server' (3775 bytes)
Starting server with Python version 3.6.7
 s: latency control setting = True
 s: available routes:
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s:  > channel=0 cmd=ROUTES len=0 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 8/8
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=7/0)
c : Connected.
c : Waiting: 2 r=[5, 7, 9] w=[9] x=[] (fullness=7/0)
c :   Ready: 2 r=[9] w=[9] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=0
firewall manager: Got subnets: [(2, 24, False, '10.132.15.0', 0, 0), (2, 32, True, '127.0.0.1', 0, 0), (30, 128, True, '::1', 0, 0)]
firewall manager: Got nslist: []
firewall manager: Got ports: 12300,12300,0,0
firewall manager: Got udp: False, user: None
firewall manager: setting up.
firewall manager: setting up IPv6.
>> pfctl -s Interfaces -i lo -v
>> pfctl -s all
>> pfctl -a sshuttle6-12300 -f /dev/stdin
>> pfctl -E
firewall manager: setting up IPv4.
>> pfctl -s Interfaces -i lo -v
>> pfctl -s all
>> pfctl -a sshuttle-12300 -f /dev/stdin
>> pfctl -E
c : mux wrote: 15/15
c : mux wrote: 15/15
c : Waiting: 2 r=[5, 7, 9] w=[] x=[] (fullness=14/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=7)
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=0/0)
c :   Ready: 2 r=[9] w=[] x=[]
c : <  channel=0 cmd=PONG len=7
c : received PING response
c : Waiting: 2 r=[5, 7, 9] w=[] x=[] (fullness=0/0)
```

**Comment by craigwatson** [comment]
Output diff:

```
diff broken working
8d7
< User enabled: False
16c15
< c : executing: ['ssh', 'x.x.x.x', '--', 'exec /bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=2; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1082), "assembler.py", "exec"))\'"\'"\'\'']
---
> c : executing: ['ssh', 'x.x.x.x', '--', 'exec /bin/sh -c \'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=2; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(978), "assembler.py", "exec"))\'"\'"\'\'']
19,25c18,24
< server: assembling 'sshuttle' (7 bytes)
< server: assembling 'sshuttle.cmdline_options' (62 bytes)
< server: assembling 'sshuttle.helpers' (944 bytes)
< server: assembling 'sshuttle.ssnet' (5647 bytes)
< server: assembling 'sshuttle.hostwatch' (2386 bytes)
< server: assembling 'sshuttle.server' (3775 bytes)
< Starting server with Python version 3.6.7
---
> server: assembling u'sshuttle' (7 bytes)
> server: assembling u'sshuttle.cmdline_options' (44 bytes)
> server: assembling u'sshuttle.helpers' (950 bytes)
> server: assembling u'sshuttle.ssnet' (5624 bytes)
> server: assembling u'sshuttle.hostwatch' (2367 bytes)
> server: assembling u'sshuttle.server' (3558 bytes)
> Starting server with Python version 2.7.15rc1
46c45
< firewall manager: Got udp: False, user: None
---
> firewall manager: Got udp: False
```

**Comment by davidkarlsen** [comment]
Any update?

**Comment by davidkarlsen** [comment]
On catalina and sshuttle 0.78.5 stuff works again.

**Comment by HannaLaptseva** [comment]
Still does not work on catalina and sshuttle 0.78.5

**Comment by craigwatson** [comment]
I can also verify that the issue still exists on Catalina with 0.78.5.
