### ISSUE TITLE
does not exclude established connections

### ISSUE THREAD

**Issue by brianmay** [sshuttle/sshuttle#224]
Copied from http://bugs.debian.org/897231:

> When I create a connection all the assigned traffic gets forwarded including connections that were
> already established.
>
> This has two effects.
>       1. I get disconnected from my already established ssh connections.
>       2. If the remote server is within the IP range the connection fails unless the server itself is excluded from the ip range.
>
> As I've tested in jessie and stretch, only the new connections should
> be forwarded to the remote server. Leaving the established connections
> intact including the sshuttle connection itself.

**Comment by ThomasBrierley** [comment]
This is the first thing that tripped me up on Debian. The simplest usage of sshuttle doesn't work:

```sh
sshuttle -r server 0/0
```

Now requires duplication:

```sh
sshuttle -x server -r server 0/0
```

It would however be nice to keep the ability to foward all existing connections behind a flag... (but with implicit exclusion of remote obviously).

**Comment by ThomasBrierley** [comment]
This might be Debian specific, possibly only testing (buster).

I had thought it was a regression and tried to bisect, but found this reproducable all the way back to v0.54. I've used versions newer than this without issues throughout various Ubuntu LTS, but I have not yet tried in Debian Stable.

**Comment by brianmay** [comment]
I believe it is a Linux kernel specific issue. I think there were more details in another bug report, but can't find it right now.

**Comment by brianmay** [comment]
Moving this to #191.
