### ISSUE TITLE
Latest sshuttle doesn't prompt for password on Mac - simply crashes

### ISSUE THREAD

**Issue by victorhooi** [sshuttle/sshuttle#227]
I previously had the stable version of sshuttle installed via Homebrew on OSX.

If I ran it as a normal user - it would prompt me for a password, presumedly to set the firewall, and then I was able to connect fine.

However, I just installed the latest version from HEAD (`0.1.dev1+gae5bd28`) - and this time, it doesn't prompt me for my password - instead it crashes with:

```
victorhooi@victorhooi-macbookpro ~> sshuttle -r root@192.168.194.122  10.7.78.1/24
fatal: you must be root (or enable su/sudo) to set the firewall
fatal: ['/Users/victorhooi/homebrew/Cellar/sshuttle/HEAD-ae5bd28/libexec/bin/python2.7', '/Users/victorhooi/homebrew/bin/sshuttle', '--method', 'auto', '--firewall'] expected READY, got ''
```

Is this a regression

**Comment by ivan4th** [comment]
The bug is introduced in #226. If you revert that commit, sshuttle starts prompting for password again. Exact place where the breakage got introduced: https://github.com/sshuttle/sshuttle/commit/ae5bd28dcfe92502551da9ae902c26d98c71ec3c#diff-ac0b595db2a1f11bb5eae88c749b89bbL196

**Comment by brianmay** [comment]
Does `platform.platform().startswith('OpenBSD')` return True on OSX? If so, this would explain the breakage.

**Comment by ivan4th** [comment]
@brianmay no, it doesn't. There's just a bug in the code that constructs argv_tries, `%` is applied only to PYTHONPATH part. See my PR #228 for a fix.
