### ISSUE TITLE
IPSEC packages

### ISSUE THREAD

**Issue by amirmasoud** [sshuttle/sshuttle#230]
Can I use sshuttle for routing IPSEC packages through it?
I have a home server with sshuttle and ipsec (https://github.com/hwdsl2/setup-ipsec-vpn) installed. I'm trying to route ipsec packages through sshuttle. (right now with no success)

Thanks

**Comment by brianmay** [comment]
AmirMasoud <notifications@github.com> writes:

> Can I use sshuttle for routing IPSEC packages through it?
> I have a home server with sshuttle and ipsec (https://github.com/hwdsl2/setup-ipsec-vpn) installed. I'm trying to route ipsec packages through sshuttle. (right now with no success)

sshuttle only supports forwarding TCP or (depending on mode of
operation) maybe UDP packets.

IPSEC uses its own protocol, so won't work over sshuttle.

Sorry.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by amirmasoud** [comment]
Thanks,
