### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by inputuserhere** [sshuttle/sshuttle#231]
Hello,

So I installed installed sshuttle on my Ubuntu server and ran `sudo sshuttle -r user@serverip 0/0`

How can I use this with firefox/chrome even mobile? Or is this strictly for linux server/gui and macs? I was recommended this as I was having issues with SSH Tunneling.

Questions:
1.How do I specify a different ssh port used on my server?
2. When uninstalling does it remove the edits done on IPtables etc..?

**Comment by Belval** [comment]
1) Add :PORT after the IP/domain.
2) Yes

**Comment by brianmay** [comment]
inputuserhere <notifications@github.com> writes:

> How can I use this with firefox/chrome even mobile? Or is this strictly for linux server/gui and macs? I was recommended this as I was having issues with SSH Tunneling.

At the moment sshuttle has no support for mobiles. It might be possible
to get this working on Android - however more work is required. Even
more work yet if you want it to work on a non-rooted phone (assuming
this is possible).

I believe sshuttle will work on OSX, but I have not had any experience
with this myself.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by brianmay** [comment]
If sshuttle is not working, you are going to have to provide more details. Such as what behaviour you expected to get vs the behaviour you actually observed. Closing this for now.
