### ISSUE TITLE
systemd service never starts with Type=notify

### ISSUE THREAD

**Issue by desbma** [sshuttle/sshuttle#238]
The documentation [recommends](https://sshuttle.readthedocs.io/en/stable/requirements.html#additional-suggested-software) using the `notify` mode if using a systemd service.

However in that case systemd waits for shuttle to send the notification which never happens and the service is killed because of the start timeout.

Using `Type=simple` in the service file fixes it.

I'm using the [official package on Arch Linux](https://www.archlinux.org/packages/community/any/sshuttle/).
Ironically, I am the one [who asked the Arch package maintainer](https://bugs.archlinux.org/task/56086) to implement the official `Type=notify` recommendation.

**Comment by brianmay** [comment]
desbma <notifications@github.com> writes:

> The documentation [recommends](https://sshuttle.readthedocs.io/en/stable/requirements.html#additional-suggested-software) using the `notify` mode if using a systemd service.
>
> However in that case systemd waits for shuttle to send the notification which never happens and the service is killed because of the start timeout.
>
> Using `Type=simple` in the service file fixes it.
>
> I'm using the [official package on Arch Linux](https://www.archlinux.org/packages/community/any/sshuttle/).
> Ironically, I am the one [who asked the Arch package maintainer](https://bugs.archlinux.org/task/56086) to implement the official `Type=notify` recommendation.

A pull request to fix this would be appreciated.

Thanks.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by desbma** [comment]
I found a fix: the process that notifies systemd that sshuttle is ready in not the first process started by the systemd service, so the service needs the line [`NotifyAccess=all`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#NotifyAccess=).

So it is a bug of the Arch Linux package systemd service file, but I will submit a pull request to mention this in the doc.

**Comment by brianmay** [comment]
Keith Irwin <notifications@github.com> writes:

> I didn't create this service; it must have been built on by the apt install.  I ran into the same timeout issue, and also fixed it by adding `NotifyAccess=all`.  
>
> I couldn't find the service file in this github repo... so I can't pull request.  It could just be that the apt repo needs to be updated.  This is the version I got: 
>
> ```sh
> $ sshuttle --version
> 0.1.dev0
> ```

Where did you get this Debian package from? This version is very old.

Furthermore I am not familiar with any systemd file either, sorry. It is
very possible that that is something specific to the Debian package you
are using.

Debian has 0.54 through to 0.78.4 depending on distribution.

Just to confirm, can you please show the output of:

```
dpkg -l sshuttle
apt-cache policy sshuttle
```

Thanks
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by keith24** [comment]
I lied.  

```sh
$ dpkg -l sshuttle
dpkg-query: no packages found matching sshuttle
```

Reviewing my chrome and bash histories... it looks like I had installed it with `pip install sshuttle`.  

I deleted that version from /usr/local/bin and reinstalled it with apt, which gave me version 0.78.3.
