### ISSUE TITLE
Brainstorming on how to support ICMP in SShuttle

### ISSUE THREAD

**Issue by mathieupythian** [sshuttle/sshuttle#243]
I know it isn't supported at the moment, however assuming we use TPROXY method which already supports UDP/TCP, any thoughts on the best way to implement ICMP support in sshuttle, so that all ICMP/UDP/TCP protocols can work all at once?

**Comment by brianmay** [comment]
If this was possible you would need to be able to tell the kernel to intercept ICMP packets and send ICMP packets with a fake source address. Unfortunately, I don't think this is possible. Pull requests to prove me wrong appreciated. Closing.

**Comment by cpina** [comment]
Perhaps a note about this on the "man sshuttle" might be useful for some users? This confused me while debugging some other problems. I know that the manual talks about TCP only but I had tried some "ping" out of habit.
