### ISSUE TITLE
Help use sshuttle on Windows

### ISSUE THREAD

**Issue by anhduongxanh63** [sshuttle/sshuttle#249]
Hi,
I follow the document: http://sshuttle.readthedocs.io/en/stable/windows.html
But it's not working.
I have Windows (ip 192.168.0.110)
Centos 7 in Vmware, ip: 192.168.0.113
And remote server: 45.77.40.210 (private ip: 10.99.0.1)

I VMWare, I run command:
sshuttle -r root@45.77.40.210 -l 0.0.0.0 -x 10.0.0.0/24 -x 192.168.0.0/16 0/0
And in Windows, I run below command:
route add 0.0.0.0 mask 0.0.0.0 192.168.0.113

Then I ping to 10.99.0.1, but it's not working.
Please help.

**Comment by brianmay** [comment]
Unfortunately I am not in a position to be able to provide support for sshuttle on Windows. Closing.

**Comment by david-mohr** [comment]
Keep in mind that ICMP (e.g. ping) isn't captured by the sshuttle rules, so to test you'll need to use a TCP service.

**Comment by brianmay** [comment]
Good point. I missed that. Thanks.

**Comment by brianmay** [comment]
Fixed by #918.
