### ISSUE TITLE
use sshuttle on windows by DOCKER container to connect external server behind firewall

### ISSUE THREAD

**Issue by robgrzel** [sshuttle/sshuttle#252]
Hi!

How to use sshuttle with docker on windows host as it would be used on normal ubuntu to connect some external server?

**Comment by brianmay** [comment]
Windows is not supported, as it doesn't have a supported firewall. If you think you can fix this, patches are welcome.

**Comment by brianmay** [comment]
Having said that, you might want to see this instructions: http://sshuttle.readthedocs.io/en/stable/windows.html

I have not personally used or tested these instructions.

**Comment by robgrzel** [comment]
<cry>
... 
<stab>
<stab>

**Comment by brianmay** [comment]
Not able to support Windows. Closing.
