### ISSUE TITLE
DNS requests are not forwarded during sshuttle launch

### ISSUE THREAD

**Issue by mission712** [sshuttle/sshuttle#254]
I live in a country where port 53 is poisoned and certain DNS requests are timed out. When I try to launch sshuttle with specific domain names, sshuttle will timeout trying to get the IP address for that domain, which my country blocks:
```
m712@ion ~ % cat ~/.config/sshuttle_hosts | xargs sudo sshuttle --dns --disable-ipv6 --no-latency-control -r my@vps.com
usage: sshuttle [-l [ip:]port] [-r [user@]sshserver[:port]] <subnets...>
sshuttle: error: argument IP/MASK[:PORT[-PORT]]...: Unable to resolve address: domain.that.is.blocked
```
 It would probably be better to do the IP resolves *after* the connection has been established.

**Comment by brianmay** [comment]
Would https://github.com/sshuttle/sshuttle/pull/232 help with your use case?

**Comment by brianmay** [comment]
No response; closing.
