### ISSUE TITLE
Issue to connect to local server while connected to remote server

### ISSUE THREAD

**Issue by HichamAffia** [sshuttle/sshuttle#256]
Hi,
I work a lot on remote calculation servers and I use sshutlle to open a jupyter notebook on the server and accessing it throught my browser.

But when I attempt to connect to the local server we have in outr lab local network the ip adress of the server is not found, same thing if I try to ssh it, ssh cant resolve the host name.

I'm quite sure there is a easy fix but I'm quite a newbie when it comes to networks.

My sshuttle command to connect to the remote server is : sshuttle --dns -Nr username@server

Thanks!

**Comment by brianmay** [comment]
Sorry, I can't really help without more details. It seems like DNS might not be working, but I have no idea why this might be the case.
