### ISSUE TITLE
Fails with error code 255

### ISSUE THREAD

**Issue by kmallajosyulaBOL** [sshuttle/sshuttle#257]
I am trying to sshuttle into an EC2 instance. I am able to ssh into the instance without the pem file by adding my public key to the instance's authorized_keys file.
EC2 os: Amazon Linux 2
Client os: Ubuntu 16 Kernel: 4.15.0-29

When I run `sudo sshuttle -vvvvr kmallajosyula@xx.xx.xx.xx 0/0`, I get the following trace - 
`Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.5.2
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: False
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Starting client with Python version 3.5.2
c : connecting to server...
c : executing: ['ssh', 'kmallajosyula@xx.xx.xx.xx', '--', 'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys; verbosity=4; stdin=getattr(sys.stdin,"buffer",sys.stdin); exec(compile(stdin.read(915), "assembler.py", "exec"))\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
kmallajosyula@xx.xx.xx.xx's password: 
-c:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
server: assembling 'sshuttle' (7 bytes)
server: assembling 'sshuttle.cmdline_options' (27 bytes)
server: assembling 'sshuttle.helpers' (861 bytes)
server: assembling 'sshuttle.ssnet' (5502 bytes)
server: assembling 'sshuttle.hostwatch' (2333 bytes)
server: assembling 'sshuttle.server' (3088 bytes)
Starting server with Python version 3.7.0rc1
 s: latency control setting = True
 s: available routes:
 s:   2/10.0.1.0/24
 s:   2/169.254.169.254/32
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s:  > channel=0 cmd=ROUTES len=35 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=42/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=42/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 43/43
c : Connected.
c : Waiting: 2 r=[7, 8] w=[8] x=[] (fullness=7/0)
c :   Ready: 2 r=[8] w=[8] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=35
firewall manager: Got subnets: [(2, 0, False, '0.0.0.0'), (2, 8, True, '127.0.0.0')]
firewall manager: Got nslist: []
firewall manager: Got ports: 0,12300,0,0
firewall manager: Got udp: False
firewall manager: setting up.
firewall manager: setting up IPv4.
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.0/8 -p tcp
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 0.0.0.0/0 -p tcp --to-ports 12300 -m ttl ! --ttl 42
c : mux wrote: 15/15
c : mux wrote: 15/15
packet_write_wait: Connection to xx.xx.xx.xx port 22: Broken pipe
c : Waiting: 2 r=[7, 8] w=[] x=[] (fullness=14/0)
c :   Ready: 2 r=[8] w=[] x=[]
firewall manager: undoing changes.
firewall manager: undoing IPv4 changes.
>> iptables -t nat -D OUTPUT -j sshuttle-12300
>> iptables -t nat -D PREROUTING -j sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -X sshuttle-12300
firewall manager: undoing /etc/hosts changes.
c : fatal: server died with error code 255`

**Comment by ludwigvon100** [comment]
Hi, same here on this machine:
`Linux VirtualBox 4.15.0-29-generic #31-Ubuntu
`
Linux Mint XFCE 19…

VirtualBox:~$ sshuttle -v --dns --python python -r user@server:443 0/0
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.15rc1
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: True
User enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
DNS listening on ('127.0.0.1', 12299).
Starting client with Python version 2.7.15rc1
c : connecting to server...
Starting server with Python version 2.7.9
 s: latency control setting = True
 s: available routes:
 s:   2/192.168.1.0/24
c : Connected.
firewall manager: setting up.
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 0.0.0.0/0 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 127.0.0.53/32 -p udp --dport 53 --to-ports 12299 -m ttl ! --ttl 42
packet_write_wait: Connection to X.Y.Z.T port 443: Broken pipe
firewall manager: undoing changes.
>> iptables -t nat -D OUTPUT -j sshuttle-12300
>> iptables -t nat -D PREROUTING -j sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -X sshuttle-12300
c : fatal: server died with error code 255

It used to work before on  previous Mint versions like 18 Mate (sshuttle -V : 0.76)

I tried to install sshuttle from the depot apt install sshuttle (=> V 0.78.3) and from pip install sshuttle (=> V 0.78.4), but it fails everytime.
Is it possible to downgrade with the V 0.76 which seems to work on Mint 18, and how to proceed?!…

Thanks

**Comment by KaliszAd** [comment]
I also have this problem...

Starting sshuttle proxy.
[local sudo] Password: 
firewall manager: Starting firewall with Python version 3.6.6
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: True
User enabled: False
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Binding DNS: 12300 12299
DNS listening on ('127.0.0.1', 12299).
DNS listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 12299)>.
Starting client with Python version 3.6.6
c : connecting to server...
c : executing: ['ssh', 'user#targethost@fudo', '--', 'exec /bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=4; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1082), "assembler.py", "exec"))\'"\'"\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
sign_and_send_pubkey: signing failed: agent refused operation
Password: 
server: assembling 'sshuttle' (7 bytes)
server: assembling 'sshuttle.cmdline_options' (62 bytes)
server: assembling 'sshuttle.helpers' (944 bytes)
server: assembling 'sshuttle.ssnet' (5647 bytes)
server: assembling 'sshuttle.hostwatch' (2386 bytes)
server: assembling 'sshuttle.server' (3775 bytes)
Starting server with Python version 3.4.2
 s: latency control setting = True
 s: available routes:
 s:   2/10.10.4.0/24
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s:  > channel=0 cmd=ROUTES len=15 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=22/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=22/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 23/23
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=22/0)
c : Connected.
c : Waiting: 3 r=[5, 7, 9] w=[9] x=[] (fullness=7/0)
c :   Ready: 3 r=[9] w=[9] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=15
firewall manager: Got subnets: [(2, 0, False, '0.0.0.0', 0, 0), (2, 32, True, '127.0.0.1', 0, 0)]
firewall manager: Got partial nslist: [(2, '192.168.1.2')]
firewall manager: Got nslist: [(2, '192.168.1.2')]
firewall manager: Got ports: 0,12300,0,12299
firewall manager: Got udp: False, user: None
firewall manager: setting up.
firewall manager: setting up IPv4.
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 0.0.0.0/0 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.1.2/32 -p udp --dport 53 --to-ports 12299 -m ttl ! --ttl 42
c : mux wrote: 15/15
c : mux wrote: 15/15
c : Waiting: 3 r=[5, 7, 9] w=[] x=[] (fullness=14/0)
packet_write_wait: Connection to <REDACTED-IP> port 5022: Broken pipe
c :   Ready: 3 r=[9] w=[] x=[]
firewall manager: undoing changes.
firewall manager: undoing IPv4 changes.
>> iptables -t nat -D OUTPUT -j sshuttle-12300
>> iptables -t nat -D PREROUTING -j sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -X sshuttle-12300
firewall manager: undoing /etc/hosts changes.
c : fatal: server died with error code 255

**Comment by KaliszAd** [comment]
Ok, thanks, that works. Actually, I was connecting through a transparent SSH proxy (FUDO by Wheel Systems). I just excluded the IP of this intermediate System and it instantly worked. Btw. you can use the usual Hosts in .ssh/config for more complicated ssh options.
$ sshuttle --dns -x <FUDO> -r <USER>#<ACTUAL TARGET SYSTEM>@<FUDO> 0/0

**Comment by brianmay** [comment]
Moved to #191.

**Comment by Meshkati** [comment]
Even -x remote_server caused me losing ssh connection, but adding `-x 0.0.0.0/0` along with `-x host_ip` worked.

**Comment by amirography** [comment]
> Simply add `-x [whatever IP/domain you're connecting to]` to your sshuttle command and it should work fine.
It also helped me as well. May I ask what happened here  how ```-x ip``` mitigates it?

**Comment by KaliszAd** [comment]
@amirography I would guess, that the communication with the remote IP shouldn't travel through the tunnel/ proxy as it is used for the underlying communication, so you would have basically a circular dependency. You resolve this "what came first" issue with the -x option. That is at least my very high level understanding. Of course, the proxy could distinguish between packets used for the underlying tunnel/ proxy communication and the communication itself but it seems this is not the case.
