### ISSUE TITLE
how to use a pkcs11 hardware token for ssh (like epass2003) ?

### ISSUE THREAD

**Issue by sandys** [sshuttle/sshuttle#258]
hi,
we normally do ssh like

```
#Fedora - 
ssh   -o PKCS11Provider=/usr/lib64/opensc-pkcs11.so user@gcp.red.com

#Ubuntu - 
ssh  -o PKCS11Provider=/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so  user@gcp.red.com

#OSX - 
ssh -o PKCS11Provider=/Library/OpenSC/lib/opensc-pkcs11.so user@gcp.red.com
```

how do we enable hardware token access with sshuttle ?

**Comment by brianmay** [comment]
Have you seen the `-e` command line option? Something like -e 'ssh -o ...` should work? Another option might be to edit `.ssh/config` and make this option the default when required.

**Comment by brianmay** [comment]
No response; closing.
