### ISSUE TITLE
make_deb package name should include latest release version and git rev

### ISSUE THREAD

**Issue by jfkw** [sshuttle/sshuttle#26]
I was very glad to see this repo of active work on sshuttle, thank you. Additionally the packaging scripts are convenient and greatly appreciated.

Please consider having make_deb include the most recent revision (on the branch), plus the current git rev, e.g.

```
sshuttle/packaging$ ./make_deb 
dpkg-deb: building package `sshuttle' in `./sshuttle-0+git.deb'.
```

Should read something like `sshuttle-0.72+git-41b8ad4.deb`, with deference to any conventions debian might have for the git revision item.

I see the debian control file which would allow local changes to accomplish this, but it would be nice if the make_deb script could introspect the repo state to do it reliably and automatically.

Thanks again for the continued development of sshuttle.

**Comment by brianmay** [comment]
Thank you for your suggestion.

The packaging does need a lot of work. As a first step, I want to make it a proper PyPI package (if I get time...), then I will work on fixing the Debian packaging.

**Comment by brianmay** [comment]
make_deb has been removed from the packaging sometime ago; this isn't the way to get a good quality Debian package. There is a good quality Debian package in Debian. So I am closing this bug report.
