### ISSUE TITLE
Please add -i parameter to specify Identity file

### ISSUE THREAD

**Issue by DavidRabel-b1** [sshuttle/sshuttle#266]
Hi,

many SSH related tools support specifiying the identity file with a -i parameter. Could you add something like that, too?

Yours
David

**Comment by brianmay** [comment]
David Rabel <notifications@github.com> writes:

> many SSH related tools support specifiying the identity file with a -i
> parameter. Could you add something like that, too?

You can do this already. with something like `-e "ssh -i ..."`.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by DavidRabel-b1** [comment]
Thanks for the hint!
A proper -i parameter would still be great.

**Comment by brianmay** [comment]
Pull requests would be appreciated. Closing.
