### ISSUE TITLE
Not working in sudeors file

### ISSUE THREAD

**Issue by wmantly** [sshuttle/sshuttle#267]
I am using sshuttle in a NodeJS app and the sudo password is becoming annoying...
I have used these instructions, correcting for the paths of my system.

https://github.com/apenwarr/sshuttle/pull/51#issuecomment-326314545

This is my current `/etc/sudoers.d/sshuttle` file and i have version 0.78.3 of sshuttle on Linux Mint 19, basically Ubuntu 18.04

```
Cmnd_Alias SSHUTTLE = /usr/bin/env PYTHONPATH=/usr/lib/python3/dist-packages /usr/bin/python3 /usr/bin/sshuttle

william ALL=NOPASSWD: SSHUTTLE
```

**Comment by brianmay** [comment]
William Mantly Jr <notifications@github.com> writes:

> I am using sshuttle in a NodeJS app and the sudo password is becoming annoying...
> I have used these instructions, correcting for the paths of my system.
>
> https://github.com/apenwarr/sshuttle/pull/51#issuecomment-326314545
>
> This is my current `/etc/sudoers.d/sshuttle` file and i have version 0.78.3 of sshuttle on Linux Mint 19, basically Ubuntu 18.04

Sorry, no idea where on the correct sudoers file spec. If you do happen
to solve this, however pull requests to update the documentation would
be appreciated.

Thanks!
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by wmantly** [comment]
I have somewhat solved this issue, the stat of client.py in 0.78.3 does not allow for use with the sudoers file, 0.78.4 seeks to. Do not close this issue yet, I am working on a script to automate the process and confirm everything.

**Comment by wmantly** [comment]
I have the script working but need help getting it into the package. Please see this PR #269

**Comment by wmantly** [comment]
This is now working in #269. `sshuttle --sudoers` will auto build, verify and update the sudoers.d files.

**Comment by max-lobur** [comment]
Nice! which version has this feature?
I'm on 0.78.5 (mac os) and do not see this flag

**Comment by wmantly** [comment]
Added in #269
