### ISSUE TITLE
Clarify canonical sshuttle fork to improve search results

### ISSUE THREAD

**Issue by jfkw** [sshuttle/sshuttle#27]
I was delighted to find this active repo continuing sshuttle development. Unfortunately, it took a long time before I discovered it. Search engine results mostly point to the original apenwarr/sshuttle repo.

If the other forks (original apenwarr/sshuttle, brianmay/sshuttle, et al) are amenable, it might be useful to commit an update to all repo's READMEs pointing to sshuttle/sshuttle as the canonical repo.

**Comment by brianmay** [comment]
This is a problem with github, it is hard to find out which repo is the "official" one. Which is why it was suggested we create the sshuttle organization.

I am short on time, if you want to create pull requests for the other repositories, feel free to do so :-)

**Comment by brianmay** [comment]
Nothing to do here for this project. Closing.
