### ISSUE TITLE
"Permission denied, please try again."

### ISSUE THREAD

**Issue by wally-yu** [sshuttle/sshuttle#270]
hi,
Thanks for working out such a handy tool.
however when i am trying to use it, i got "Permission denied, please try again."

My local machine is Mac.
Remote server was build on AWS ubuntu 16.04.

could you please give me some suggestion how to debug and find the prob?

thanks in advance.

**Comment by brianmay** [comment]
Wally Yu <notifications@github.com> writes:

> Thanks for working out such a handy tool.
> however when i am trying to use it, i got "Permission denied, please try again."

Sounds like an ssh error. Are you able to ssh to the remote host without
sshuttle?
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by wally-yu** [comment]
yes, i can. i can ssh to remote server with .pem file or directly using username/password.
Do i need to start any other service from server? or ssh is enough?

**Comment by brianmay** [comment]
Wally Yu <notifications@github.com> writes:

> yes, i can. i can ssh to remote server with .pem file or directly using username/password.
> Do i need to start any other service from server? or ssh is enough?

No, just ssh by itself should be fine. If ssh isn't working -
e.g. reporting permission denied - then sshuttle won't work.

sshuttle itself doesn't do any permission checking, it uses ssh.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/
