### ISSUE TITLE
sshuttle continues to run after ssh connection dies

### ISSUE THREAD

**Issue by drewwells** [sshuttle/sshuttle#274]
I leave sshuttle running in daemon mode for long periods of time. If the SSH connection dies, my computer's network goes into a broken state. Others have written projects around sshuttle to solve this problem https://github.com/flashashen/no-YOU-talk-to-the-hand

It may not be simple to relogin to the remote server like PKS providers, so perhaps by default sshuttle should just shut down. A cli arg/config to enable automatic re-login would be nice too 👍

**Comment by brianmay** [comment]
Closing this in favor of #285, which looks like the same thing.
