### ISSUE TITLE
iptables v1.8.0 (legacy): unknown option "--to-ports"

### ISSUE THREAD

**Issue by WhyNotHugo** [sshuttle/sshuttle#286]
I'm getting this error when attempting to sshuttle into a remote host (using `sshuttle -vr ssh.mycompany.com 10.176.0.0/12 192.168.0.0/16`).

```
Starting client with Python version 3.7.1
c : connecting to server...
Starting server with Python version 3.5.2
 s: latency control setting = True
 s: available routes:
 s:   2/10.30.110.0/24
c : Connected.
firewall manager: setting up.
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
iptables v1.8.0 (legacy): unknown option "--to-ports"
Try `iptables -h' or 'iptables --help' for more information.
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.0.0/16 -p tcp --to-ports 12300
iptables v1.8.0 (legacy): unknown option "--to-ports"
Try `iptables -h' or 'iptables --help' for more information.
firewall manager: undoing changes.
>> iptables -t nat -D OUTPUT -j sshuttle-12300
>> iptables -t nat -D PREROUTING -j sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -X sshuttle-12300
fatal: ['iptables', '-t', 'nat', '-A', 'sshuttle-12300', '-j', 'REDIRECT', '--dest', '192.168.0.0/16', '-p', 'tcp', '--to-ports', '12300'] returned 2
c : fatal: cleanup: ['sudo', '-p', '[local sudo] Password: ', '/usr/bin/env', 'PYTHONPATH=/usr/lib/python3.7/site-packages', '/usr/bin/python', '/usr/bin/sshuttle', '-v', '--method', 'auto', '--firewall'] returned 99
```

Any idea what I'm doing wrong? Or is this a bug?

**Comment by WhyNotHugo** [comment]
Nope, no wrapper whatsoever getting called. And I've confirmed it's 1.8.0.

**Comment by gormv** [comment]
Same issue here and I can't find a --to-ports option in ip-tables source code.

https://git.netfilter.org/iptables/tree/iptables/iptables.c#n236

**Comment by brianmay** [comment]
It is part of the REDIRECT target, which I suspect is part of the kernel, not the iptables command. From the iptables-extensions man page:

```
   REDIRECT
       This target is only valid in the nat table, in the  PREROUT‐
       ING  and  OUTPUT  chains,  and user-defined chains which are
       only called from those chains.  It redirects the  packet  to
       the  machine  itself  by  changing the destination IP to the
       primary address of the incoming interface (locally-generated
       packets  are  mapped to the localhost address, 127.0.0.1 for
       IPv4 and ::1 for IPv6).

       --to-ports port[-port]
              This specifies a destination port or range  of  ports
              to  use:  without this, the destination port is never
              altered.  This is only valid if the rule also  speci‐
              fies  one  of the following protocols: tcp, udp, dccp
              or sctp.

       --random
              If option --random is used then port mapping will  be
              randomized (kernel >= 2.6.22).

       IPv6 support available starting Linux kernels >= 3.7.
```

**Comment by gormv** [comment]
Ok thanks! I'm on 4.19.4 kernel (arch linux) so might be some issues with the kernel and --to-ports

@WhyNotHugo You are also on 4.19?

**Comment by WhyNotHugo** [comment]
Yes, I'm currently on `4.19.5-arch1-1-ARCH`. Not sure what version it was when initially reporting this issue, but I can't seem to reproduce it now.

**Comment by ElijahLynn** [comment]
Upgraded to 4.19.9-arch1-1-ARCH and it works now!

**Comment by gormv** [comment]
Upgraded to 4.19.9-arch1-1-ARCH and now it works.
@WhyNotHugo maybe you should close this issue now if it's working.

**Comment by WhyNotHugo** [comment]
Thanks! I'll let you know if I have any more issues, but this looks like it's working now.

**Comment by gormv** [comment]
This issue seems to be back again now , with 4.20.6-arch1-1-ARCH

**Comment by ElijahLynn** [comment]
Still working for me. Kernel version is off by 3 though and iptables is same. 

Linux archlinux 4.20.3-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 16 22:38:58 UTC 2019 x86_64 GNU/Linux
iptables v1.8.2 (legacy)

**Comment by ElijahLynn** [comment]
Just updated to 4.20.7 w/iptables 1.8.2 and still working without this error.

Linux archlinux 4.20.7-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 6 18:42:40 UTC 2019 x86_64 GNU/Linux

**Comment by aquator** [comment]
Don't want to "necrobump" this, but it comes back time to time on Arch after kernel upgrades (like today), re-installing the iptables (or iptables-nft) solves the issue.

**Comment by surki** [comment]
FYI It could happen if kernel upgrade package was installed but the machine is not yet restarted (so module loading would fail leading to this error)

**Comment by xiaxichen** [comment]
Hi I have this question:
`Linux version 5.13.0-30-generic (buildd@lcy02-amd64-003) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022` 
about this error
`iptables v1.8.4 (legacy): unknown option "--to-ports"
Try iptables -h' or 'iptables --help' for more information.`

what should i do?

**Comment by Heath123** [comment]
I'm also getting this now: `iptables v1.8.7 (nf_tables): unknown option "--to-ports"`

`uname -a` output:

`Linux heath-arch 5.17.3-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 14 Apr 2022 01:18:28 +0000 x86_64 GNU/Linux`
