### ISSUE TITLE
deadlock cleaning up iptables rules on exit with large set of routes.

### ISSUE THREAD

**Issue by alext** [sshuttle/sshuttle#292]
When running sshuttle with a large list of routes it's failing to clean them up at exit. I get the following output:

```
$ sshuttle -r user@host.example.com -s /tmp/aws-cidrs.txt
user@host.example.com's password: 
client: Connected.
^CAnother app is currently holding the xtables lock; still -9s 0us time ahead to have a chance to grab the lock...
Another app is currently holding the xtables lock; still -19s 0us time ahead to have a chance to grab the lock...
Another app is currently holding the xtables lock; still -29s 0us time ahead to have a chance to grab the lock...
```

This continues. If I look at `ps` I can see that there are 2 iptables calls. If I `kill -9` the first one, sshuttle then cleans up successfully

I'm running sshuttle 0.78.3 (as shipped with Ubuntu Bionic). my list of routes has 855 entries (everything from https://ip-ranges.amazonaws.com/ip-ranges.json).

I've done a bit of digging, and I think the problem lies in the use of `subprocess.Popen` here: https://github.com/sshuttle/sshuttle/blob/0b1a260/sshuttle/linux.py#L27-L33. When it finds the chain it's looking for the function returns without reading all the output from the iptables call. If the output is larger than the buffer, the iptables command will block. This means that subsequent iptables calls fail to obtain the kernel xtables lock.

I've been testing the following patch locally and it seems to fix the issue for me, although I'm not sure how portable it is to other Python versions:

```diff
--- a/sshuttle/linux.py	2018-12-04 13:57:38.956939197 +0000
+++ b/sshuttle/linux.py	2018-12-04 15:26:02.739084232 +0000
@@ -23,14 +23,12 @@
         'PATH': os.environ['PATH'],
         'LC_ALL': "C",
     }
-    p = ssubprocess.Popen(argv, stdout=ssubprocess.PIPE, env=env)
-    for line in p.stdout:
-        if line.startswith(b'Chain %s ' % name.encode("ASCII")):
+    completed = ssubprocess.run(argv, stdout=ssubprocess.PIPE, env=env, encoding='ASCII')
+    if completed.returncode:
+        raise Fatal('%r returned %d' % (argv, completed.returncode))
+    for line in completed.stdout.split('\n'):
+        if line.startswith('Chain %s ' % name):
             return True
-    rv = p.wait()
-    if rv:
-        raise Fatal('%r returned %d' % (argv, rv))
-
 
 def ipt(family, table, *args):
     if family == socket.AF_INET6:

**Comment by brianmay** [comment]
The call to `p.wait()` should wait for the process to die. Oh wait, we skip it if we find what we are looking for and return true immediately :-(. So yes, the process could still be running.

Good debugging effort.

I seem to remember people have complained about this error in the past, but the source of the problem was diagnosed to be outside sshuttles' control.

If you can please submit a pull request, I will merge this.

Thanks

**Comment by alext** [comment]
Thanks for the feedback. I've opened #293 as a starting point...
