### ISSUE TITLE
dns with tproxy not working

### ISSUE THREAD

**Issue by BlackDex** [sshuttle/sshuttle#294]
When trying to use tproxy together with DNS it doesn't seem to be working.
If i put the method on NAT DNS is working via the remote connection but no UDP for the rest.

**Comment by brianmay** [comment]
Can you provide debug logs? Also what do you mean by "doesn't seem to be working"? What results did you observe? What did you expect to see?

**Comment by BlackDex** [comment]
Well, there is not much to show in the debug log except that i do not see any DNS requests in there.
If i leave it at NAT i see DNS request when using -vv. If i use TPROXY i can do DNS requests but they will not go via the remote system and not ending up in the logs.

**Comment by brianmay** [comment]
Unfortunately there is nothing we can use here to diagnose the problem. TPROXY can rather be tricky at times, and I am not in a position to provide support when it doesn't work.

Having said that, it is possible a different Kernel version might help.

Closing.
