### ISSUE TITLE
Make not a fork

### ISSUE THREAD

**Issue by MatthewScholefield** [sshuttle/sshuttle#296]
It's a little confusing how this project is marked as a fork. @brianmay Can you contact GitHub support and ask them to remove the fork status? I've done it before and they normally have no problem doing this.

**Comment by brianmay** [comment]
How do I contact them?

**Comment by MatthewScholefield** [comment]
@brianmay You can just create [a support ticket](https://github.com/contact).

**Comment by brianmay** [comment]
Done.

**Comment by MatthewScholefield** [comment]
Awesome!
