### ISSUE TITLE
Python2.7 doesn't have subprocess.run()

### ISSUE THREAD

**Issue by igorpiazza** [sshuttle/sshuttle#301]
Hello,

I'm unable to use sshuttle with this setup:
client: ubuntu 18.04
python: 2.7.15rc1
shuttle: 0.78.5.dev25+g531a17c

I get this output (verbose)

$ sshuttle -r igor@us 192.168.123.0/24 -vv
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.15rc1
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: False
User enabled: False
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket._socketobject object at 0x7fa8b4f50910>.
Starting client with Python version 2.7.15rc1
c : connecting to server...
c : executing: ['ssh', 'igor@us', '--', 'exec /bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=2; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1082), "assembler.py", "exec"))\'"\'"\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
igor@us's password: 
server: assembling 'sshuttle' (7 bytes)
server: assembling 'sshuttle.cmdline_options' (61 bytes)
server: assembling 'sshuttle.helpers' (945 bytes)
server: assembling 'sshuttle.ssnet' (5654 bytes)
server: assembling 'sshuttle.hostwatch' (2386 bytes)
server: assembling 'sshuttle.server' (3781 bytes)
Starting server with Python version 3.5.2
 s: latency control setting = True
 s: available routes:
 s:   2/169.254.0.0/16
 s:   2/172.31.255.0/24
 s:   2/192.168.122.0/24
 s:   2/192.168.123.0/24
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s:  > channel=0 cmd=ROUTES len=73 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=80/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=80/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 81/81
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=80/0)
c : Connected.
c : Waiting: 2 r=[4, 8] w=[8] x=[] (fullness=7/0)
c :   Ready: 2 r=[8] w=[8] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=73
firewall manager: Got subnets: [(2, 24, False, '192.168.123.0', 0, 0), (2, 32, True, '127.0.0.1', 0, 0)]
firewall manager: Got nslist: []
firewall manager: Got ports: 0,12300,0,0
firewall manager: Got udp: False, user: None
firewall manager: setting up.
firewall manager: setting up IPv4.
firewall manager: undoing changes.
firewall manager: undoing IPv4 changes.
firewall manager: Error trying to undo IPv4 firewall.
firewall manager: ---> Traceback (most recent call last):
firewall manager: --->   File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.5.dev25+g531a17c-py2.7.egg/sshuttle/firewall.py", line 270, in main
firewall manager: --->     method.restore_firewall(port_v4, socket.AF_INET, udp, user)
firewall manager: --->   File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.5.dev25+g531a17c-py2.7.egg/sshuttle/methods/nat.py", line 99, in restore_firewall
firewall manager: --->     if ipt_chain_exists(family, table, chain):
firewall manager: --->   File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.5.dev25+g531a17c-py2.7.egg/sshuttle/linux.py", line 27, in ipt_chain_exists
firewall manager: --->     completed = ssubprocess.run(argv, stdout=ssubprocess.PIPE, env=env, encoding='ASCII')
firewall manager: ---> AttributeError: 'module' object has no attribute 'run'
firewall manager: undoing /etc/hosts changes.
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 11, in <module>
    load_entry_point('sshuttle==0.78.5.dev25+g531a17c', 'console_scripts', 'sshuttle')()
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.5.dev25+g531a17c-py2.7.egg/sshuttle/cmdline.py", line 26, in main
    return firewall.main(opt.method, opt.syslog)
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.5.dev25+g531a17c-py2.7.egg/sshuttle/firewall.py", line 219, in main
    user)
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.5.dev25+g531a17c-py2.7.egg/sshuttle/methods/nat.py", line 39, in setup_firewall
    self.restore_firewall(port, family, udp, user)
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.5.dev25+g531a17c-py2.7.egg/sshuttle/methods/nat.py", line 99, in restore_firewall
    if ipt_chain_exists(family, table, chain):
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.5.dev25+g531a17c-py2.7.egg/sshuttle/linux.py", line 27, in ipt_chain_exists
    completed = ssubprocess.run(argv, stdout=ssubprocess.PIPE, env=env, encoding='ASCII')
AttributeError: 'module' object has no attribute 'run'
c : fatal: cleanup: ['sudo', '-p', '[local sudo] Password: ', '/usr/bin/env', 'PYTHONPATH=/usr/local/lib/python2.7/dist-packages/sshuttle-0.78.5.dev25+g531a17c-py2.7.egg', '/usr/bin/python', '/usr/local/bin/sshuttle', '-v', '-v', '--method', 'auto', '--firewall'] returned 1
s:   Ready: 1 r=[4] w=[] x=[]

**Comment by brianmay** [comment]
What version of python do you have on the remove server? As far as I am aware all versions of python >= 2.7 should have the `subprocess.run` function.

**Comment by igorpiazza** [comment]
On the remote server (ubuntu 16.04):

igor@ubuntu-server:~$ python -V
Python 2.7.12

Thanks
Igor

**Comment by brianmay** [comment]
Oh, I see the problem. I am not sure how I concluded run is in Python 2.7, it is only available in Python >= 3.5

This function call needs to be replaced with `call(...)`, which does the same thing.

**Comment by igorpiazza** [comment]
Thanks in advance, wait fot the fix

**Comment by brianmay** [comment]
This should now be fixed.
