### ISSUE TITLE
shuttle stopped working on mojave (10.14.1) and python3.7

### ISSUE THREAD

**Issue by sargense** [sshuttle/sshuttle#304]
c : fatal: expected server init string b'SSHUTTLE0001'; got b''
Python3.7.1 on macos mojave 10.14.1
Python3.7.2 on linux host

**Comment by sargense** [comment]
an update on this error is an issue with the --ssh-cmd either on macos/the server/or python3.7. Removing resolved the error, but would still present an issue in cases where I was not using a key in my stored keyring.

**Comment by sargense** [comment]
update to the update:

the error disappeared and it appears to work, but is not forwarding.

**Comment by brianmay** [comment]
Can you provide any more information? "is not forwarding" is not much to go by.

**Comment by sargense** [comment]
I can grab some information from routing tables this weekend. However, sshuttle doesn’t seem to log much more information. Basically it runs and throws zero exceptions (once the ssh cmd above is removed, which that used to work, so that’s different) however I cannot connect to anything on the other side of the tunnel including IPs in routes printed by sshuttle. I do see changes to the routing table made by sshuttle and even with sshuttle whitelisted on the fire wall no connection is made. Any attempt just hangs as waiting for a response. So it really seems like it’s just not forwarding any traffic. What commands should I run and what information is needed to help debug?

**Comment by brianmay** [comment]
You are probably looking for the `-v` flag. `-vvv` for maximum verbosity (exact syntax may vary, this is from memory).

**Comment by andreaphsz** [comment]
same here

**Comment by jamshid** [comment]
FYI I was getting this `client: fatal: expected server init string b'SSHUTTLE0001'; got b''` error because my remote machine did not have **python3**. 

It was latest centos 7.8 which only has python 2.7.5 and previously worked. IDK if there is a patch coming in https://bugzilla.redhat.com/show_bug.cgi?id=1851622 to fix this.
