### ISSUE TITLE
sshuttle crashes if auto-hosts is used

### ISSUE THREAD

**Issue by drewib** [sshuttle/sshuttle#305]
Happening on os x and linux. I have two different sshuttle servers setup and only one of them is crashing. It just started happening and a server reboot does not resolve it. I am able to connect fine without auto-hosts.

Version: 0.78.4_1

Error
```
hostwatch: Traceback (most recent call last):
--->   File "sshuttle.server", line 144, in start_hostwatch
--->   File "sshuttle.hostwatch", line 294, in hw_main
--->   File "sshuttle.hostwatch", line 107, in _check_revdns
---> socket.gaierror: [Errno -2] Name or service not known
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 38, in <module>
  File "sshuttle.server", line 397, in main
  File "sshuttle.ssnet", line 596, in runonce
  File "sshuttle.server", line 328, in hostwatch_ready
sshuttle.helpers.Fatal: hostwatch process died
firewall manager: undoing changes.
>> iptables -t nat -D OUTPUT -j sshuttle-12300
>> iptables -t nat -D PREROUTING -j sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -X sshuttle-12300
c : fatal: server died with error code 1
```

This part likely isn't new, but hostwatch is finding 950 domains. Is there some limit to the number of domains located? Is there any workaround?

**Comment by brianmay** [comment]
Drew <notifications@github.com> writes:

> Happening on os x and linux. I have two different sshuttle servers
> setup and only one of them is crashing. It just started happening and
> a server reboot does not resolve it. I am able to connect fine without
> auto-hosts.

What version of sshuttle is this?
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by drewib** [comment]
I can't reproduce anymore. closing
