### ISSUE TITLE
Expected server init string b'SSHUTTLE0001'; got b'' error

### ISSUE THREAD

**Issue by crahan** [sshuttle/sshuttle#314]
This appears to be similar to issue #304. The version provided with Homebrew (0.78.5) does not exhibit this problem, but when I install the code directly from the repo and try to run `sshuttle -vvvv -r sshserver www.google.com` I get the following error message and debug output:

```Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.7.2
firewall manager: ready method name pf.
IPv6 enabled: True
UDP enabled: False
DNS enabled: False
User enabled: False
Binding redirector: 12300
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening with <socket.socket fd=7, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 12300, 0, 0)>.
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Starting client with Python version 3.7.2
c : connecting to server...
c : executing: ['ssh', 'sshserver', '--', 'exec /bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=4; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1107), "assembler.py", "exec"))\'"\'"\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
-c:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 5, in <module>
ModuleNotFoundError: No module named 'sshuttle'
c : fatal: expected server init string b'SSHUTTLE0001'; got b''
```

This is with a local Python 3.7.2 version and 2.7.15 on the SSH server. When running the same command using  a local 3.6.5 Python version the ModuleNotFoundError line changes to `ImportError: no module named sshuttle.helpers`. The issue seems to occur on both Ubuntu 16.04 and macOS 10.14.1 client systems.

**Comment by brianmay** [comment]
Weird. Have tried various versions of Python, but unfortunately it works every time for me. For the record, after that `DeprecationWarning` you are suppose to see:

```-c:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
server: assembling 'sshuttle' (7 bytes)
server: assembling 'sshuttle.cmdline_options' (66 bytes)
server: assembling 'sshuttle.helpers' (944 bytes)
server: assembling 'sshuttle.ssnet' (5653 bytes)
server: assembling 'sshuttle.hostwatch' (2386 bytes)
server: assembling 'sshuttle.server' (3830 bytes)
Starting server with Python version 3.7.2
```

**Comment by crahan** [comment]
I've tried with a different repo tag and found the following.

It does **not** work with the latest Github code (for me):
```
$ sshuttle --version
0.78.6.dev1+g3bfb975
```

It works as expected with tags/v0.78.5:
```
$ sshuttle --version
0.78.6.dev0+g752a953.d20190213
```

In the case of tags/v0.78.5 `python setup.py develop` and running sshuttle sets everything up as expected, including the lines you posted. I'm not entirely sure what specific change between `0.78.6.dev0+g752a953.d20190213` and `0.78.6.dev1+g3bfb975` is causing this for me at this time though.

**Comment by crahan** [comment]
Some more details. It appears to be related to this commit: https://github.com/sshuttle/sshuttle/commit/3bfb975ed9b4024cbc762324539868e901cf8a04#diff-540decd43e8cfa1b8bf41c3b81a8bbb6

As soon as I move those import lines back towards the end of the `assembler.py` file things start working as expected.

**Comment by brianmay** [comment]
Oh crap, yes, that is most definitely wrong. It didn't break for me, as I hadn't pulled in that change. Your understanding is correct.

The ordering does break PEP8 however. Wonder if it is possible to annotate so that flake8 will ignore this. A comment as to why this is needed would probably be very good to, to reduce risk of future mistakes.

**Comment by crahan** [comment]
Would a comment to explain why those import statements need to be where they are + `# noqa  E402` on those import lines fix the issue?

**Comment by brianmay** [comment]
I would think it should fix the problem. Please update the pull request.

Thanks for your work on solving this.

**Comment by crahan** [comment]
Happy to help! The updated pull request appears to pass all checks.
