### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by naevtamarkus** [sshuttle/sshuttle#32]
Hi!

What are the chances to run this from Windows? Can we encapsulate it inside Putty-or-the-like?
We have a few users that depend on VNC because they can't decently open a graphical session through an SSH tunnel (because of the TCP over TCP issue) and it would be REALLY great to make them use this instead.

Thanks!

**Comment by brianmay** [comment]
Yes, was wondering about windows support myself. Basically you need kernel support for:

* Intercepting incoming packets.
* Sending outgoing packets with a fake source IP address.

I have no idea if this is possible with Windows or not. If it is, it should in theory be possible to create a new method under sshuttle/methods to implement the required functionality.

**Comment by brianmay** [comment]
I am starting to think that this is going to be very difficult if not impossible under Windows.

With 3rd party software, it is possible to configure squid to use transparent proxy under Windows. However sshuttle has additional requirements over squid. e.g. we need to be able to find out the original destination before the packet was redirected. Also it wouldn't be possible to automatically configure redirection when sshuttle starts and stops.

Please feel free to write code and demonstrate I am wrong :-)

So for now I am closing this request.

**Comment by mrkschan** [comment]
Hey @naevtamarkus, I tried to setup sshuttle on Windows (via VM) and you can find my sharing at https://coderwall.com/p/adfxgw/sshuttle-on-windows.

**Comment by brianmay** [comment]
Fixed by #918.
