### ISSUE TITLE
Ubuntu 16.04.5 LTS/ fatal: expected server init string 'SSHUTTLE0001'; got ''

### ISSUE THREAD

**Issue by rasulovk** [sshuttle/sshuttle#321]
I'm using latest pull from git, and have following error:
fatal: expected server init string 'SSHUTTLE0001'; got ''

On version 0.78.5 error was : 
fatal: expected server init string 'SSHUTTLE0001'; got b''

What could be cause, please advise

**Comment by brianmay** [comment]
My initial thought was that this sounds like #314, which was closed in #319. However that can't be right, because 0.78.5 was released before the bug was introduced and it has already been fixed in git.

Can you please run sshuttle in verbose mode (-vvv) and past the entire log here? Thanks

**Comment by SamaneYaghoobi** [comment]
I got the same error and this is the log of sshuttle:

`
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.12
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: True
User enabled: False
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket._socketobject object at 0x7f1a8443b0c0>.
Binding DNS: 12300 12299
DNS listening on ('127.0.0.1', 12299).
DNS listening with <socket._socketobject object at 0x7f1a8443b130>.
Starting client with Python version 2.7.12
c : connecting to server...
c : executing: ['ssh', '-p', '1816', 'ashkan@188.40.90.61', '--', 'exec /bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=3; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1082), "assembler.py", "exec"))\'"\'"\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
`

**Comment by brianmay** [comment]
I am going to close this in favor of #328  for now, as there is not enough information in any of these cases to tell what is going wrong.

**Comment by ethode** [comment]
Same error, MacOS latest before big sur
