### ISSUE TITLE
Non-transparent mode

### ISSUE THREAD

**Issue by lars18th** [sshuttle/sshuttle#325]
Hi,

Perhaps this sounds "stupid", but I have this question: Can SSHuttle work in a non-transparent mode?

What's the non-transparent mode?
That's working as a regular SOCKS proxy, instead of a transparent TCP VPN.

And why we'll want to do this, if when can do it with the plain SSH client?
Because the SSHuttle has improved QoS capabilities for interactive sessions.

So, if anyone can comment on that, I'd appreciate it.
Thank you!

**Comment by brianmay** [comment]
Currently sshuttle has no socks support. A better solution might be to integrate QoS support into ssh?

If sshuttle - or something like sshuttle - could be designed to intercept requests (like sshuttle) and forward them to a SOCKS server, this could be really useful (assuming nothing like this already exists).

I have 0 time to write anything like this however.

**Comment by lars18th** [comment]
> Currently sshuttle has no socks support. A better solution might be to integrate QoS support into ssh?

I feel this is hard to do; and it's actually like remaking the wheel.

> If sshuttle - or something like sshuttle - could be designed to intercept requests (like sshuttle) and forward them to a SOCKS server, this could be really useful (assuming nothing like this already exists).

Well, in fact the only requirement about sshuttle is to have the functionality to work without the "transparent mode". If it can work in a "tunnel mode" then we can execute some Socks Proxy Server in the remote location, and forward the listening port to one local port.

So the question is: how to _disable_ the transparency.

> I have 0 time to write anything like this however.

Ok. Anyway, thanks for discussing it.

**Comment by brianmay** [comment]
Question answered - this is not supported at present; nothing more to do here; closing.
