### ISSUE TITLE
instructions to whitelist or blacklist interfaces

### ISSUE THREAD

**Issue by drewwells** [sshuttle/sshuttle#330]
sshuttle's mechanism for intercepting all traffic bound for destination IPs makes it challenging to circumvent. If I have two interfaces on a computer wlan0 and tun0. If I want `sshuttle` to only manipulate traffic going out on tun0, how would I do this? I think instructions outside of `sshuttle` would be fine for this, if it is possible.

**Comment by brianmay** [comment]
Unfortunately, I don't think there is any easy way to do this, as sshuttle is not provided any information from the firewall as to what port the packet will be routed to.
