### ISSUE TITLE
Unable to negotiate error

### ISSUE THREAD

**Issue by fuluel** [sshuttle/sshuttle#333]
I ran he sshuttle on a Mac 10.14. Once I tried to connect a server, it give me the following error: 

Unable to negotiate with [SERVER_IP] port 22: no matching cipher found. Their offer: aes128-cbc,aes256-cbc,3des-cbc,des-cbc
client: fatal: failed to establish ssh session (1)

I got the similar error during using ssh, but I can can connect it by use this command

ssh -vvv -c aes256-cbc admin@[SERVER_IP]

How should I use sshuttle to connect it?

**Comment by brianmay** [comment]
You should be able to use the `--ssh-cmd` option.

e.g.

```
sshuttle --ssh-cmd "ssh -c aes256-cbc" ...
```
