### ISSUE TITLE
Name cannot be resolved if it contains `-`

### ISSUE THREAD

**Issue by Dissem** [sshuttle/sshuttle#334]
If I try to set up sshuttle to connect to a subnet by a name containing a dash, it fails with the following error message:
```
# sshuttle -H -r user@ssh.example.com test-system.example.com

sshuttle: error: argument IP/MASK[:PORT[-PORT]]...: 'test-system.example.com' is not a valid address/mask:port format
```
I think sshuttle doesn-t recognize it as an url and then tries to parse it as an IP range.

**Comment by brianmay** [comment]
The subnet needs to match a [regular expression](https://github.com/sshuttle/sshuttle/blob/master/sshuttle/options.py#L35). It looks like this is failing. However I can't see the problem with a quick scan.

**Comment by brianmay** [comment]
I am not able to reproduce this on master. What version of sshuttle are you using?

**Comment by Dissem** [comment]
I'm terribly sorry, I checked the issues but did not try the latest version. I just noticed this was (most probably) fixed in this commit 3 months ago: [Hyphen in hostname fix](https://github.com/sshuttle/sshuttle/commit/4372c6c11739eb479ffb74f933699960686c9408).
It will probably still fail for punycode domain names, but I think this is not much of an issue.

**Comment by brianmay** [comment]
No problem. Thanks for the report.

**Comment by abelsalgadoromeroWD** [comment]
I am also hit by this issue on MacOs installed with brew. Any chance this could be released?
