### ISSUE TITLE
Route traffic traffic over proxy to another machine?

### ISSUE THREAD

**Issue by dominikheinz** [sshuttle/sshuttle#336]
Hello,
In my scenario I have 3 machines:

A local machine **A**
A remote machine **B** that can only be reached when connected to a VPN X.
A remote machine **C** that can only be reached when connected to a VPN X.
_(B and C are in the same network)_

All machines have their ssh ports open. My goal is to configure machine **B** in such a way when establishing a connection to **B** I automatically get proxied to **C**. So basically as a client, I only know the IP address of machine **B** and I get silently redirected to **C**. How can I do that?
How do I have to configure **B** that all incoming requests are redirected to **C**?

**Comment by RichardoC** [comment]
Couldn't you use something like this in your ssh config on A? Then connect sshuttle to 'C'?

Host C
    ForwardAgent yes
    ProxyCommand ssh B nc %h %p

I haven't tried it but let me know how it goes.

**Comment by brianmay** [comment]
Unfortunately this project doesn't have the resources to provide support, and no response was received to the previous suggestion. Closing.
