### ISSUE TITLE
Ignore end-of-line comments in multi-line command

### ISSUE THREAD

**Issue by smoyer64** [sshuttle/sshuttle#352]
I create shell scripts to launch ``sshuttle`` in a specific configuration for each of the environments I work with and it would be really convenient if this tool (which is awesome BTW) would ignore comments in these scripts.  For example, here's a (sanitized) example of one my my scripts:

```
shell#!/bin/bash

/usr/bin/sshuttle -Dr smoyer64@example.com \
    10.0.1.0/24 \ # Kubernetes develop
    10.0.2.0/24 \ # Kubernetes develop
    10.0.3.0/24 \ # Kubernetes develop
    10.0.4.0/24 \ # PG bouncer develop
    10.0.5.0/24 \ # PG bouncer test
    10.0.6.0/24 \ # PostgreSQL production
    10.0.7.0/24 \ # AMQ develop
    10.0.8.0/24 \ # AMQ acceptance
    10.0.9.0/24 \ # AMQ production
```

The bash shell will take care of the line wraps in this command but it will fail (as written) because the ``#`` character isn't part of a valid network specification.

**Comment by normanr** [comment]
Try this instead: https://unix.stackexchange.com/a/9810

**Comment by smoyer64** [comment]
@normanr That stackexchange page has nothing to do with my request.  I want to document my command which has nothing to do with commenting out unused lines (either between command lines or at the end).

**Comment by normanr** [comment]
yes, so try:

```
cmd=(
    /usr/bin/sshuttle -Dr smoyer64@example.com
    10.0.1.0/24 # Kubernetes develop
    10.0.2.0/24 # Kubernetes develop
    10.0.3.0/24 # Kubernetes develop
    10.0.4.0/24 # PG bouncer develop
    10.0.5.0/24 # PG bouncer test
    10.0.6.0/24 # PostgreSQL production
    10.0.7.0/24 # AMQ develop
    10.0.8.0/24 # AMQ acceptance
    10.0.9.0/24 # AMQ production
    )
"${cmd[@]}"
```

**Comment by normanr** [comment]
This is not a limitation of sshuttle, but rather a limitation of the shell that you are using to launch sshuttle.

**Comment by brianmay** [comment]
I tend to agree, it is the responsibility of the caller to filter out comments. It just happens that the most common program to do this - the shell - is rather bad at doing this. Not the above solution - while a good solution -u is bash specific. Closing...

**Comment by smoyer64** [comment]
@normanr that worked perfectly ... I don't know why I didn't blame it on the shell to begin with ;)
