### ISSUE TITLE
Does it leave any trace?

### ISSUE THREAD

**Issue by ftbarata** [sshuttle/sshuttle#369]
Hi, I work on a company where everything is monitored. The users are forced to use non-transparent proxy and all outgoing ports are blocked except port 80 and 443, but the servers network don't have any outgoing filtered port, and I have access to the servers.  So, sometimes I need to access my vps and I'm using the sshuttle to be able connect to my vps via ssh.
I ran the "last" command on the local server here and it seems that sshuttle does not leave login log, which is good.
So, I'd like to know if sshuttle leaves any kind of trace, except obviously the network traffic, that could be easily got with tcpdump for example.
If so, what trail does it leave?
Thanks in advance

**Comment by wmantly** [comment]
From a network point of view, it's just SSH. The people monitoring will be able to see what internal IP connected to what external IP and via what port/protocol. On the client computer, there would be logs as some IPtables rules are changed and unless you are running as root. some privileged access log depending on how the system is set up.

**Comment by ftbarata** [comment]
Hi @wmantly ,  I  use ubuntu on my workstation, I'm root too. It's interesting to know what happens on the client computer, but it's not a problem I wanted to know what can be tracked when I use the sshuttle. So, if it's just a ssh, why it doesn't produce login logs? Or it should but for some reason I didn't see it here?
Taking advantage of this opportunity, do you know some tool like sshuttle that avoid trail like ssh login sessions ?

**Comment by wmantly** [comment]
you could make LXC/docker container and sshutle from that

**Comment by ftbarata** [comment]
Well, I can't access anything outsite except using http or https. I'm behind a  firewall and  squid. I am using ssh-in-a-box, so I can access through web,but I'd love to use my own terminal, but avoiding trails... But thanks anyway
