### ISSUE TITLE
About safety

### ISSUE THREAD

**Issue by ohh-haolin** [sshuttle/sshuttle#370]
I've been using this tools for a while, and I think it's great.
I know it based on SSH tunnel. However, I wonder whether the TCP stream is encrypted by SSH.

Thanks.

**Comment by BenWiederhake** [comment]
If you read the code, you'll see that sshuttle calls ssh, and then interacts with it through pipes.  I don't think there is a way for ssh to *not* encrypt the connection; and if there is, the user probably knows it and does it intentionally.

**Comment by ohh-haolin** [comment]
Really thanks for your interpretation. 
I've tried to read the code, but I failed for I completely have no idea about the functions it uses. I am not familiar with the basis of web or web security.

Really thanks.

**Comment by brianmay** [comment]
I think we can close this now...
