### ISSUE TITLE
Status on implementing a socks proxy?

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [sshuttle/sshuttle#390]
I want to use this to help bypass firewalls, where right now I use ssh tunnels which are very slow. Is it possible to convert this into a socks or http proxy? Also, what's the UDP support?

**Comment by brianmay** [comment]
Not sure what you want exactly. Does "ssh -D 1050" meet your needs for a socks proxy?

sshuttle supports UDP using the tproxy method on Linux. This has not been extensively tested however.

**Comment by gidoBOSSftw5731** [comment]
I was hoping to use sshuttle to prevent TCP meltdown due to TCP over TCP
with openvpn

**Comment by brianmay** [comment]
sshuttle uses ssh which is TCP based. When it passes through streams however, it doesn't forward through the TCP layer. It forwards the data in the TCP layer, and then creates another TCP connection at the remote end. Does this make sense?

**Comment by gidoBOSSftw5731** [comment]
Ah, I see, I must've misinterpreted it, thanks for the clarification

**Comment by thegreathir** [comment]
> Not sure what you want exactly. Does "ssh -D 1050" meet your needs for a socks proxy?
> 
> sshuttle supports UDP using the tproxy method on Linux. This has not been extensively tested however.

I have some similar problem. "ssh -D 1050" does not meet my needs because it doesn't proxy dns queries!

**Comment by lars18th** [comment]
I feel this request is similar to #395 . From my point of view, the request has same. So please @brianmay  consider it.

Thank you!
