### ISSUE TITLE
nftables (nft) should detect when hooks and default policy already exists

### ISSUE THREAD

**Issue by hloeung** [sshuttle/sshuttle#392]
Hi,

For nftables/nft, sshuttle/methods/nft.py has the following:

`        _nft('add chain', 'prerouting',`
`             '{ type nat hook prerouting priority -100; policy accept; }')`
`        _nft('add chain', 'postrouting',`
`             '{ type nat hook postrouting priority 100; policy accept; }')`
`        _nft('add chain', 'output',`
`             '{ type nat hook output priority -100; policy accept; }')``

Unfortunately, when a host already has the chains configured with rules, this fails as such:

> Error: Could not process rule: Device or resource busy
> add chain ip nat postrouting { type nat hook postrouting priority 100; policy accept; }
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> fatal: ['nft', 'add chain', 'ip', 'nat', 'postrouting', '{ type nat hook postrouting priority 100; policy accept; }'] returned 1

It should really detect when these chains exist, with hooks into prerouting/postrouting/output, and then ignore and continue.

Commenting out just those three lines fixes it for me.

**Comment by brianmay** [comment]
Pull requests welcome!

**Comment by hloeung** [comment]
Alright! One PR coming right up...

**Comment by skuhl** [comment]
Looks like this issue should be closed?

**Comment by brianmay** [comment]
Probably. Thanks.
