### ISSUE TITLE
systemd notifications: NOTIFY_SOCKET env var missing

### ISSUE THREAD

**Issue by rjharmon** [sshuttle/sshuttle#402]
It appears that #192 broke systemd notifications, at least for me (Ubuntu 18 with method auto => nat)

Troubleshooting indicates that the NOTIFY_SOCKET variable, although found in the main sshuttle process, isn't making it into the --firewall process - probably due to sudo environment-variable hygeine behavior.

It seems like this should be easily fixed by moving the notification again, back to the main process after the firewall process says STARTED.  That, or by adding sudo's --preserve-env=NOTIFY_SOCKET option.  Any preference?

**Comment by skuhl** [comment]
It appears that pull request #403 resolved this issue? If so, perhaps this can be closed?
