### ISSUE TITLE
invalid reverse-lookup hostname triggering error

### ISSUE THREAD

**Issue by lordsutch** [sshuttle/sshuttle#404]
With the -H option enabled connecting to a remote host that gets a lot of traffic from miscellaneous IP addresses, after a few minutes the remote side crashes with the following traceback:

hostwatch: Found: : 109.201.137.30
hostwatch: Found: .: 109.201.137.30
hostwatch: Traceback (most recent call last):
--->   File "/usr/lib/python3.7/encodings/idna.py", line 165, in encode
--->     raise UnicodeError("label empty or too long")
---> UnicodeError: label empty or too long
--->
---> The above exception was the direct cause of the following exception:
--->
---> Traceback (most recent call last):
--->   File "sshuttle.server", line 144, in start_hostwatch
--->   File "sshuttle.hostwatch", line 294, in hw_main
--->   File "sshuttle.hostwatch", line 118, in _check_dns
---> UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 39, in <module>
  File "sshuttle.server", line 403, in main
  File "sshuttle.ssnet", line 598, in runonce
  File "sshuttle.server", line 334, in hostwatch_ready
sshuttle.helpers.Fatal: hostwatch process died

Apparently this IP address has an invalid reverse DNS lookup which is messing up the hostwatch process. It would probably be preferable to ignore bogus hostnames instead of crashing the connection.

**Comment by brianmay** [comment]
Pull requests welcome...

**Comment by lordsutch** [comment]
The pull request being merged would seem to fix this issue.
