### ISSUE TITLE
ssh authentification broken

### ISSUE THREAD

**Issue by drjbarker** [sshuttle/sshuttle#410]
I think the latest pull #401 has broken something with the ssh authentification. With my previously working configuration I now get asked to enter a password for:

`username@gateway.domain.com@gateway.domain.com's password:` 

i.e. the username has become mangled and ended up as `username@gateway.domain.com` rather than `username`. If I don't specify a username (i.e. fall back to .ssh/config) then I get a crash here the root cause is:

```
line 84, in parse_hostport
    host = "{}".format(re.split(r'\s*@', rhostport)[1])
IndexError: list index out of range
```

I'll take a look at this myself and see if I can fix.

**Comment by drjbarker** [comment]
Ah, just found all the comments in #401. I'll wait and see if @vBlackOut fixes this first.

**Comment by vBlackOut** [comment]
see pull #402

**Comment by brianmay** [comment]
Merged. Should be fixed now, I think.
