### ISSUE TITLE
How to add multiple remotes and subnets to config file? 

### ISSUE THREAD

**Issue by andloh** [sshuttle/sshuttle#427]
How to accomplish something like this? 
```
10.0.1.0/24 10.0.2.0/24
--remote
me@bastion1.com
10.0.3.0/24
--remote
me@bastion2.com
```

**Comment by PresGas** [comment]
Couldn't this be accomplished with multiple instances of sshuttle pointing to different config files? Could be wrong on that though...

These options would have to be worked on and I can't recall offhand if they are available to tweak:

`firewall manager: setting up.
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
`

...stuff like that.

**Comment by andloh** [comment]
Hi, running multiple instances of sshuttle works. I guess this will be my solution for now. But it would have been nice to have all config in one file, and managed by one process :)
