### ISSUE TITLE
Why hasn't there been a new build since jan 2019? 

### ISSUE THREAD

**Issue by andloh** [sshuttle/sshuttle#432]
Many fixes and features has been merged to master since jan 2019. Installing from ./setup.py throwing module errors when trying to run sshuttle ( ImportError: No module named ipaddress). (after installing the req's and python setuptools) 

Is it possible to get the debian/ubuntu repositories updated to the newest version ? :) 

Thanks!

**Comment by brianmay** [comment]
See #381

**Comment by andloh** [comment]
It seems like #381 has been "fixed" by dropping python27 support.
Will there be a new release now? :) @brianmay

**Comment by brianmay** [comment]
Version 1.0.1 now released.
