### ISSUE TITLE
[OSX] Firewall not being properly cleaned up on exit

### ISSUE THREAD

**Issue by vieira** [sshuttle/sshuttle#44]
It seems that on OSX 10.11.2 the rules are not being properly cleaned up when sshuttle exits. pfctl -sr still shows the sshuttle anchor. One way to reproduce this is to start sshuttle with some public ip. After sshuttle is terminated you no longer have access to that address as the firewall is still forwarding but sshuttle is no longer there.

**Comment by brianmay** [comment]
Can you please post the full debugging output from sshuttle using -vvv?

What commands do you need to run to clean up the firewall?

**Comment by vieira** [comment]
Sorry for the delay. I have tested again and can no longer reproduce the problem.
