### ISSUE TITLE
can i run it from windows 10

### ISSUE THREAD

**Issue by zefzafy** [sshuttle/sshuttle#448]
i have isolated linux server behind vpn, i need to create tunnel between my laptop "windows 10" and cantos.

Required linux machine to access internet through my labtop

**Comment by brianmay** [comment]
Windows is not supported. Some people have reported luck with running sshuttle from a VM however. See https://sshuttle.readthedocs.io/en/stable/windows.html

**Comment by brandonros** [comment]
What specifically about sshuttle does not work on Windows/what effort would it take to port it?

**Comment by brianmay** [comment]
Fixed by #918.
