### ISSUE TITLE
run sshuttle on Android as client and connect to the VPS server ?

### ISSUE THREAD

**Issue by ingnelson** [sshuttle/sshuttle#453]
Hello.

i want to run sshuttle on my android device to connect to internet via ssh tunnel like a VPN do.

### UBUNTU VPS:
i just install sshutle using this command on my Ubuntu VPS:
apt-get install sshuttle

can you give me the commnad to run sshuttle on 0.0.0.0 and port 80 and run as a server to create the tunnel like a VPN do ?
can you give me the commnad to  run sshuttle on 0.0.0.0 and port 80 and run as a server to create a DNS Tunnel too ?

### Android client:
If i use Termux application ( Termux is an Android terminal application and Linux environment ) what commad should i write to connect to the server  and tunnel all the device like a VPN do ?

i will wait your aswer.
because this way many people would use sshuttle to connect to internet.

**Comment by yash-ahir** [comment]
Same question, although I installed Arch on Termux and installed sshuttle, iptables just throws `iptables v1.8.6 (legacy): can't initialize iptables table 'nat': Permission denied (you must be root)`

My device is Samsung Galaxy S10+ (beyond2) running Android 10...

There seems no possible solution for this without obtaining root access on the Android device (which I know, is a requirement of the program), but there surely must be some alternative way?

**Comment by brianmay** [comment]
Unfortunately, sshuttle, as written, really does require root access.

I have no idea how VPNs get around this on Android. My guess is that Android must provide some sort of API for this purpose.

**Comment by jmthackett** [comment]
Hey, I've found this issue while wondering about the same thing. In the wireguard android client they seem to bundle Magisk, here:

https://github.com/WireGuard/wireguard-android/blob/master/tunnel/src/main/java/com/wireguard/android/util/RootShell.java

My understanding of magisk is it is "systemless root" so it'll include a 'su' binary but only within the scope of the application. 

Here they seem to just.. install the wireguads CLI tools:

https://github.com/WireGuard/wireguard-android/blob/master/tunnel/src/main/java/com/wireguard/android/util/ToolsInstaller.java

I'd guess sshuttle could do something very very similar.

I'm not claiming I could do it, but I do wonder if a fork of the wireguard client might be a relatively easy path for sshuttle on android.

**Comment by jmthackett** [comment]
Looking into it a little further, there is indeed an API that can be used:

https://developer.android.com/guide/topics/connectivity/vpn

There's also an example VPN app to work from:

https://android.googlesource.com/platform/development/+/master/samples/ToyVpn

And a real-life firewall type app which uses the same interface, thereby avoiding the need for root:

https://github.com/M66B/NetGuard

I'm not an android person, but I'm going to see if I can turn the ToyVPN into a _python_ ToyVPN that can let packets through. If I can do that, sshuttle might not be impossible to drop in. I'll try it with SL4A first.

I'll report back if I make any progress.

**Comment by jmthackett** [comment]
I think it is fair to say I forgot about this having made minimal progress, and I've no time to pursue it. I'd still suggest the above is a good starting point for anyone looking at it.

**Comment by Keyvantajfar** [comment]
> I think it is fair to say I forgot about this having made minimal progress, and I've no time to pursue it. I'd still suggest the above is a good starting point for anyone looking at it.

i know nothing about android but i know Python, a little bit C and a little bit of linux which is same as android. i Do not have any expertise in this but i need to build some VPN like client for my android devices to act like VPN to have access to the worldwide Open and Free internet. so i need to do it. give me a bit of help, show the path and i'll try to build that thing. just gimme a starting point. thanks.
