### ISSUE TITLE
Version 0.78.6.dev55+gec2018d+ Traceback for tunnel-in-tunnel

### ISSUE THREAD

**Issue by larrypl** [sshuttle/sshuttle#454]
Under version 0.78.6.dev50+g994ce07 I can create a second tunnel that goes through the first tunnel. With version 0.78.6.dev55+gec2018d and higher I get tracebacks:

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "assembler.py", line 41, in <module>
>   File "sshuttle.server", line 399, in main
>   File "sshuttle.ssnet", line 603, in runonce
>   File "sshuttle.ssnet", line 493, in callback
>   File "sshuttle.ssnet", line 442, in flush
> AttributeError: 'module' object has no attribute 'set_blocking'

for version 0.78.6.dev55+gec2018d, and

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "assembler.py", line 25, in <module>
>   File "sshuttle.server", line 9, in <module>
> ImportError: cannot import name which
> c : fatal: expected server init string b'SSHUTTLE0001'; got b''

for higher versions.

**Comment by brianmay** [comment]
What version of Python are you using? Sounds like you might be using
Python 2.7, which was dropped (was the only way to fix the Python 3.8
bug). See https://github.com/sshuttle/sshuttle/pull/431

**Comment by larrypl** [comment]
No, it's Python 3.8.3, unfortunately.

**Comment by larrypl** [comment]
Just for fun I tried Python 3.9 and got the `c : fatal: expected server init string b'SSHUTTLE0001'; got b''` message also.

**Comment by larrypl** [comment]
Not sure if I'm supposed to comment on this but yeah, having python3 on the targets allows tunnel-in-tunnel. I would be interested in seeing a solution for targets that don't have python3 natively installed.

**Comment by brianmay** [comment]
Closing in favor of #469 ; will reopen if required.
