### ISSUE TITLE
I keep getting the following error on python

### ISSUE THREAD

**Issue by hackedWifi** [sshuttle/sshuttle#455]
I have tried to test sshuttle on Gentoo and Pop_os and I keep getting the following error. Is anybody experiencing this?

`firewall manager: Starting firewall with Python version 3.7.7
firewall manager: ready method name nat.
IPv6 enabled: None
UDP enabled: False
DNS enabled: False
User enabled: False
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Starting client with Python version 3.7.7
c : connecting to server...
Traceback (most recent call last):
  File "/home/dzentu/.local/bin/sshuttle", line 8, in <module>
    sys.exit(main())
  File "/home/dzentu/.local/lib/python3.7/site-packages/sshuttle/cmdline.py", line 102, in main
    opt.sudo_pythonpath)
  File "/home/dzentu/.local/lib/python3.7/site-packages/sshuttle/client.py", line 795, in main
    seed_hosts, auto_hosts, auto_nets, daemon, to_nameserver)
  File "/home/dzentu/.local/lib/python3.7/site-packages/sshuttle/client.py", line 453, in _main
    auto_nets=auto_nets))
  File "/home/dzentu/.local/lib/python3.7/site-packages/sshuttle/ssh.py", line 113, in connect
    username, password, port, host = parse_hostport(rhostport)
  File "/home/dzentu/.local/lib/python3.7/site-packages/sshuttle/ssh.py", line 77, in parse_hostport
    if "@" in host:
TypeError: argument of type 'NoneType' is not iterable`

I am on the latest sshuttle 1.0.1 using python 3.8

**Comment by brianmay** [comment]
What happened here? Why did you close this?

**Comment by brianmay** [comment]
Oh I see, probably the same as #458.

**Comment by brianmay** [comment]
Augusto <notifications@github.com> writes:

>> What happened here? Why did you close this?
>
> Actually I made I mistake when closing this issue. On my client if I try to `sshuttle -v 0/0` to test it. I keep getting the above error. If I tried to sshutle into my remote server I get the error on #434. It only connect if I use the --exclude option.
> This is happening on Gentoo with kernel 5.4.38 and latest 20.04 Pop_OS

Can you please give the full command line you used with you get this
error? i.e. the "TypeError: argument of type 'NoneType' is not iterable"
error.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by hackedWifi** [comment]
> Augusto <notifications@github.com> writes:
> > What happened here? Why did you close this? Actually I made I mistake when closing this issue. On my client if I try to `sshuttle -v 0/0` to test it. I keep getting the above error. If I tried to sshutle into my remote server I get the error on #434. It only connect if I use the --exclude option. This is happening on Gentoo with kernel 5.4.38 and latest 20.04 Pop_OS
> Can you please give the full command line you used with you get this error? i.e. the "TypeError: argument of type 'NoneType' is not iterable" error. -- Brian May <brian@linuxpenguins.xyz> https://linuxpenguins.xyz/brian/

I used the `sshuttle -v 0/0` command to test locally

**Comment by brianmay** [comment]
Agreed. This is an issue. If you don't provide a remote host you will get this error. Pull requests welcome.

**Comment by joshuarli** [comment]
Ugh, just ran into this because I mistakenly put IP in `--ssh-cmd`, not `-r IP`.

PR: https://github.com/sshuttle/sshuttle/pull/502
