### ISSUE TITLE
invalid syntax if installing from git

### ISSUE THREAD

**Issue by accessone67** [sshuttle/sshuttle#462]
Hey

After git clone and then "sudo ./setup.py install" I get syntax error.

byte-compiling build/bdist.linux-x86_64/egg/sshuttle/client.py to client.pyc
  File "build/bdist.linux-x86_64/egg/sshuttle/client.py", line 302
    assert(not re.search(rb'[^-\w\.]', hostname))
                                    ^
SyntaxError: invalid syntax

Extracting sshuttle-1.0.2.dev8+ga53f026-py2.7.egg to /usr/local/lib/python2.7/dist-packages
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-1.0.2.dev8+ga53f026-py2.7.egg/sshuttle/client.py", line 302
    assert(not re.search(rb'[^-\w\.]', hostname))
                                    ^
SyntaxError: invalid syntax

**Comment by brianmay** [comment]
Radep <notifications@github.com> writes:

> After git clone and then "sudo ./setup.py install" I get syntax error.

What version of Python are you using?
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by accessone67** [comment]
python --version
Python 2.7.17

**Comment by brianmay** [comment]
Radep <notifications@github.com> writes:

> python --version
> Python 2.7.17

Sorry, as per all the docs, Python 2.7 is not supported anymore. You
need to use Python 3.5 or greater.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by accessone67** [comment]
Dohh. all good now :) :+1:  by bad.
