### ISSUE TITLE
SSH config Port value ignored in recent sshuttle

### ISSUE THREAD

**Issue by mksh** [sshuttle/sshuttle#463]
After this change https://github.com/sshuttle/sshuttle/commit/966fd0c5231d56c4f464752865d96f97bd3c0aac (sshuttle > `0.78.5`), sshuttle started to ignore Port value from SSH configuration, and now it always assumes the default 22 port.

When launched with `sshuttle -vvv <some_sshuttle_host> <subnet1> <subnet2>`, regardless of Port setting for `<some_sshuttle_host>` in `~/.ssh/config`, the following SSH connection string is executed:

```
c : connecting to server...
c : executing: ['ssh', '-p', '22', '<some_sshuttle_host>', '--', '/bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=3; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1275), "assembler.py", "exec"))\'"\'"\'\'']
```

The only way to change 22 port is to explicitly specify it on the command line

```
sshuttle -vvv <some_sshuttle_host>:<NEW_PORT_INTEGER> <subnet1> <subnet2>
```

I guess this behavior may break many integrations with automatically provisioned hosts. Could `sshuttle` somehow revert to honoring SSH configuration files ?

**Comment by brianmay** [comment]
mksh <notifications@github.com> writes:

> I guess this behavior may break many integrations with automatically provisioned hosts. Could `sshuttle` somehow revert to honoring SSH configuration files ?

Patches welcome :-)
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/
