### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by de-adshot** [sshuttle/sshuttle#464]
### kali@kali:~$ sshuttle -vr user@x.x.x.x x.y.y.0/24
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 11, in <module>
    load_entry_point('sshuttle==1.0.2.dev8+ga53f026', 'console_scripts', 'sshuttle')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-1.0.2.dev8+ga53f026-py2.7.egg/sshuttle/cmdline.py", line 5, in <module>
    import sshuttle.client as client
  File "/usr/local/lib/python2.7/dist-packages/sshuttle-1.0.2.dev8+ga53f026-py2.7.egg/sshuttle/client.py", line 302
    assert(not re.search(rb'[^-\w\.]', hostname))
                                    ^
SyntaxError: invalid syntax
kali@kali:~$ 

I'm using kali 2020.1 and i'm unable to fix this error.

**Comment by brianmay** [comment]
Avinash <notifications@github.com> writes:

> kali@kali:~$ sshuttle -vr user@x.x.x.x x.y.y.0/24
> Traceback (most recent call last):
>   File "/usr/local/bin/sshuttle", line 11, in <module>
>     load_entry_point('sshuttle==1.0.2.dev8+ga53f026', 'console_scripts', 'sshuttle')()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
>     return self.resolve()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/local/lib/python2.7/dist-packages/sshuttle-1.0.2.dev8+ga53f026-py2.7.egg/sshuttle/cmdline.py", line 5, in <module>
>     import sshuttle.client as client
>   File "/usr/local/lib/python2.7/dist-packages/sshuttle-1.0.2.dev8+ga53f026-py2.7.egg/sshuttle/client.py", line 302
>     assert(not re.search(rb'[^-\w\.]', hostname))
>                                     ^
> SyntaxError: invalid syntax
> kali@kali:~$ 

What version of Python are you using? It looks like you are using an
older version. sshuttle requires version >= 3.5
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by brianmay** [comment]
Closing, as this looks like an issue with an older version of Python.
