### ISSUE TITLE
Removing python2 support makes sshuttle fail with old remotes

### ISSUE THREAD

**Issue by leiserfg** [sshuttle/sshuttle#469]
I'm pretty fine with removing python2 support from the client-side of the code, no one should be using python2 locally, but one cannot force the python version a host has, so IMHO `sshuttle.server` should keep being backward compatible.

**Comment by brianmay** [comment]
If you can work out how to support all versions of Python, then please do create a PR...

**Comment by saucam** [comment]
+1 for this

**Comment by nirik** [comment]
Couldn't the remote end be made to use either python2 or python3? In the fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=1851622 there's someone who pasted some patches to try and do that: 

https://gist.github.com/ZaWertun/67e86106d503380d45ddb2ac80962c49
https://gist.github.com/ZaWertun/c587b0c3d9e2c2c4215b02a4efdda423

is that a workable solution?

**Comment by luckman212** [comment]
> Maybe the right course of action is to fork v0.78.5 into `sshuttle-legacy`

@damentz thank you for the idea.
see https://github.com/sshuttle/sshuttle/issues/328#issuecomment-657790878 where I used a virtualenv instead
```
mkvirtualenv sshuttle-legacy
pip install sshuttle==0.78.5
ln -s ~/.virtualenvs/sshuttle-legacy/bin/sshuttle /usr/local/bin/sshuttle-legacy
```

**Comment by brianmay** [comment]
Kevin Fenzi <notifications@github.com> writes:

> Couldn't the remote end be made to use either python2 or python3? In the fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=1851622 there's someone who pasted some patches to try and do that: 
>
> https://gist.github.com/ZaWertun/67e86106d503380d45ddb2ac80962c49
> https://gist.github.com/ZaWertun/c587b0c3d9e2c2c4215b02a4efdda423
>
> is that a workable solution? 

Unfortunately, maybe not.

* I can't see how that first patch does anything for Python 2 support.
  It looks purely a cosmetic change.

* I think this is incomplete. I am sure that there is a Regular
  Expression somewhere that needs to be changed also (based on the bug
  reports at least).

* Disabling the code that sets non-blocking makes me really nervous.
  Could cause deadlocks. Although in theory I don't think we should be
  making any calls to functions that block unless we already know that
  there is data available (from the select call). But still, I don't
  think these calls were inserted just for the fun of it. You might find
  it works most of the time until you get an unexpected corner case...

* This needs to be submitted in the form of a pull request.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by davama** [comment]
Thank you for this change!

I can confirm v1.0.5 with client py3 and server py2 works again!!
Thank you!
