### ISSUE TITLE
Remove Python2 compatibility on PyPI

### ISSUE THREAD

**Issue by wilsonehusin** [sshuttle/sshuttle#470]
sshuttle's entry on PyPI seem to mark 1.0.x releases as Python2 compatible when it's not. Can we get this removed on PyPI?

**Comment by brianmay** [comment]
Where does it say that? It looks OK to me... Did I miss something?

![image](https://user-images.githubusercontent.com/112729/84951754-3c853500-b134-11ea-9293-91595fa8ac7d.png)

**Comment by wilsonehusin** [comment]
Oh hmm that's odd. I was referring to the `whl` having `py2` and suspected it might be the discerning point of Python versions.

![image](https://user-images.githubusercontent.com/14004487/84954364-1ca92f00-b0aa-11ea-88fe-f68a44f221cd.png)

**Comment by wilsonehusin** [comment]
Sorry it's been a while since I last worked in Python environment. Looks like to prevent Python2 PIP from blindly running Python 3+ packages we'd have to [add `python_requires` in `setup.py`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires).

**Comment by brianmay** [comment]
I didn't know this either... Can you please create a PR?

**Comment by wilsonehusin** [comment]
I added #471, unfortunately Python 2 PIP might still pull in 1.0.0, 1.0.1, 1.0.2 releases.

I don't have a good suggestion than to re-upload the releases for 1.0.0-1.0.2 which doesn't sound ideal either.

**Comment by brianmay** [comment]
Unfortunately, I can't change existing releases. Apart from deleting them. But I can't reupload a deleted release (deliberate pypi limitation). I can delete the old releases though if required.

**Comment by wilsonehusin** [comment]
As a Python 2 user I personally lean towards removing to help myself :smile:, though current users of those versions might be surprised to see it missing in PyPI.

**Comment by joshuarli** [comment]
That change looks correct, nice one @wilsonehusin.
