### ISSUE TITLE
Is it possible to use sshuttle in windows 10 via its WSL2 ?

### ISSUE THREAD

**Issue by xiangnanscu** [sshuttle/sshuttle#473]
Hello, I already successfully run sshuttle in WSL2, but it seems the outer windows 10 doesn't use WSL2's shuttle. Is there anyway to solve this?

**Comment by Crypto-Spartan** [comment]
I've been wondering the exact same thing. So far, I can't get it to work. I can do normal SSH port forwarding on WSL2, but sshuttle won't actually tunnel the traffic on the specified remote network :/

**Comment by falcon03** [comment]
Interested as well!

**Comment by krish7919** [comment]
Any update on this?

If any of the maintainers can describe what changes are required to make this possible, it would be really helpful.

**Comment by brianmay** [comment]
Fixed by #918.
