### ISSUE TITLE
module 'importlib' has no attribute 'util'

### ISSUE THREAD

**Issue by spuck** [sshuttle/sshuttle#474]
Just downloaded and installed sshuttle 1.0.2 with pip on an Amazon Linux EC2.

Trying to run for the first time, I got this message and traceback:

    [ec2-user@ip-172-31-2-69 ~]$ sshuttle -Nvr ec2-user@<redacted IP>
    Starting sshuttle proxy.
    firewall manager: Starting firewall with Python version 3.7.6
    firewall manager: ready method name nat.
    IPv6 enabled: None
    UDP enabled: False
    DNS enabled: False
    User enabled: False
    TCP redirector listening on ('127.0.0.1', 12300).
    Starting client with Python version 3.7.6
    c : connecting to server...
    Traceback (most recent call last):
      File "/usr/local/bin/sshuttle", line 8, in <module>
        sys.exit(main())
      File "/usr/local/lib/python3.7/site-packages/sshuttle/cmdline.py", line 102, in main
        opt.sudo_pythonpath)
      File "/usr/local/lib/python3.7/site-packages/sshuttle/client.py", line 795, in main
        seed_hosts, auto_hosts, auto_nets, daemon, to_nameserver)
      File "/usr/local/lib/python3.7/site-packages/sshuttle/client.py", line 453, in _main
        auto_nets=auto_nets))
      File "/usr/local/lib/python3.7/site-packages/sshuttle/ssh.py", line 92, in connect
        content = get_module_source('sshuttle.assembler')
      File "/usr/local/lib/python3.7/site-packages/sshuttle/ssh.py", line 18, in get_module_source
        spec = importlib.util.find_spec(name)
    AttributeError: module 'importlib' has no attribute 'util'

I inserted this line on line 7 of site-packages/sshuttle/ssh.py:

    import importlib.util

(Gave this a try after finding this message: https://bugs.python.org/msg301085)

It appears to be working now. It's very possible that I missed some install step; Python is not my first language.

-Thanks,

 Travis

**Comment by brianmay** [comment]
spuck <notifications@github.com> writes:

> I inserted this line on line 7 of site-packages/sshuttle/ssh.py:
>
>     import importlib.util
>
> (Gave this a try after finding this message: https://bugs.python.org/msg301085)
>
> It appears to be working now. It's very possible that I missed some
> install step; Python is not my first language.

It looks like you got this right. Am a bit puzzled how this ever worked
though...

As always, PR to fix this appreciated.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by salotz** [comment]
Can confirm. Was going to submit same fix. It failed on 3.6.10, 3.7.6, and 3.8.1.

**Comment by spuck** [comment]
I was away for the weekend, and I see you beat me to a PR to fix this.

-Cheers
