### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by limingzhang513** [sshuttle/sshuttle#477]
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 5, in <module>
    from sshuttle.cmdline import main
  File "/usr/local/lib/python2.7/dist-packages/sshuttle/cmdline.py", line 5, in <module>
    import sshuttle.client as client
  File "/usr/local/lib/python2.7/dist-packages/sshuttle/client.py", line 302
    assert(not re.search(rb'[^-\w\.]', hostname))
                                    ^
SyntaxError: invalid syntax

**Comment by onsali** [comment]
I seem to be having the same issue, its really frustrating since its out of the kali repo now and installing from github is the only way

**Comment by brianmay** [comment]
Check what version of Python you are using. This is the error I would expect if you have an old version of Python. Python >= 3.5 is required now.

**Comment by onsali** [comment]
> 
> 
> Check what version of Python you are using. This is the error I would expect if you have an old version of Python. Python >= 3.5 is required now.

Resolved, thanks
