### ISSUE TITLE
Update auto sudoers documentation

### ISSUE THREAD

**Issue by pascencio** [sshuttle/sshuttle#478]
Hi guys!

I tried to create a sudoers file following the official [documentation](https://sshuttle.readthedocs.io/en/stable/installation.html).

When a I ran this command:

`sshuttle -sudoers`

Got this output:

```shell
usage: sshuttle [-l [ip:]port] [-r [user@]sshserver[:port]] <subnets...>
sshuttle: error: argument -s/--subnets: Unable to open subnet file: udoers
```

After read the message with detail I saw `Unable to open subnet file: udoers`.

Then try this:

`sshuttle --sudoers`

And tada!!

`Success, sudoers file update.`

Can you update the official documentation please?

Thanks in the advance!

**Comment by brianmay** [comment]
Patricio Ascencio Aravena <notifications@github.com> writes:

> Can you update the official documentation please?

Pull requests appreciated.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by pascencio** [comment]
> Patricio Ascencio Aravena <notifications@github.com> writes:
> Can you update the official documentation please?
> Pull requests appreciated. -- Brian May <brian@linuxpenguins.xyz> https://linuxpenguins.xyz/brian/

@brianmay Sorry, just now saw your message.
