### ISSUE TITLE
AttributeError: 'module' object has no attribute 'set_blocking'

### ISSUE THREAD

**Issue by vBlackOut** [sshuttle/sshuttle#479]
Error on Python 3.8.3

look like trackback:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 41, in <module>
  File "sshuttle.server", line 395, in main
  File "sshuttle.ssnet", line 600, in runonce
  File "sshuttle.ssnet", line 490, in callback
  File "sshuttle.ssnet", line 439, in flush
AttributeError: 'module' object has no attribute 'set_blocking'
c : Connected.
c : Waiting: 2 r=[5, 8] w=[8] x=[] (fullness=7/0)
c :   Ready: 2 r=[] w=[8] x=[]
c : mux wrote: 15/15
c : Waiting: 2 r=[5, 8] w=[] x=[] (fullness=7/0)
c :   Ready: 2 r=[8] w=[] x=[]
c : fatal: server died with error code 1
```
it's weird

**Comment by gdunstone** [comment]
this is the commit for the relevant bug:

https://github.com/sshuttle/sshuttle/commit/6c21addde97c4582b3dccb22bca64c33af3e5eff

what is odd is that on the client, os.set_blocking works. On server it does not.

it seems to me to be a requirement for the server to have at least Python 3.8.3

**Comment by vBlackOut** [comment]
humm, i use python 3.4.8

**Comment by vBlackOut** [comment]
thank for your reply :) i check for update this server thank you

**Comment by vBlackOut** [comment]
now other error with update python on 3.8

weird very weird this sshuttle it's work perfect after 

```
Traceback (most recent call last):
  File "/usr/bin/sshuttle", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/sshuttle/cmdline.py", line 85, in main
    return_code = client.main(ipport_v6, ipport_v4,
  File "/usr/lib/python3.8/site-packages/sshuttle/client.py", line 793, in main
    return _main(tcp_listener, udp_listener, fw, ssh_cmd, remotename,
  File "/usr/lib/python3.8/site-packages/sshuttle/client.py", line 447, in _main
    (serverproc, serversock) = ssh.connect(
  File "/usr/lib/python3.8/site-packages/sshuttle/ssh.py", line 92, in connect
    content = get_module_source('sshuttle.assembler')
  File "/usr/lib/python3.8/site-packages/sshuttle/ssh.py", line 18, in get_module_source
    spec = importlib.util.find_spec(name)
AttributeError: module 'importlib' has no attribute 'util'
```

**Comment by vBlackOut** [comment]
just use

replace: line 6 in ssh.py
import importlib 
to 
from importlib import util

and line 18 in ssh.py
replace: line 6 in  ssh.py
importlib.util(...)
to
util(...)

work now :)

**Comment by arking7** [comment]
I can confirm this bug on python 3.8.3 under Arch

AttributeError: 'module' object has no attribute 'set_blocking'

I had to comment out "os.set_blocking" stuff in ssnet.py, working fine without non-blocking though.

**Comment by frakman1** [comment]
I'm using a Mac (High Sierra) and sshuttle updated as part of installing something else completely (storm). Anyway, after the upgrade it would no longer even list the older version as a viable candidate using `brew info sshuttle`. I was able to locate the  file in `/usr/local/Cellar/sshuttle/1.0.3/libexec/lib/python3.8/site-packages/sshuttle/ssnet.py`. I had to comment out two lines (439 and 449) that mentioned `os.set_blocking`. After that, it worked.

```python
    def flush(self):
        #os.set_blocking(self.wfile.fileno(), False)                         <------- THIS LINE
        if self.outbuf and self.outbuf[0]:
            wrote = _nb_clean(os.write, self.wfile.fileno(), self.outbuf[0])
            debug2('mux wrote: %r/%d\n' % (wrote, len(self.outbuf[0])))
            if wrote:
                self.outbuf[0] = self.outbuf[0][wrote:]
        while self.outbuf and not self.outbuf[0]:
            self.outbuf[0:1] = []

    def fill(self):
        #os.set_blocking(self.rfile.fileno(), False)                         <------- THIS LINE
        try:
            read = _nb_clean(os.read, self.rfile.fileno(), LATENCY_BUFFER_SIZE)
```
