### ISSUE TITLE
sshuttle not properly handling unicode?

### ISSUE THREAD

**Issue by jasonboukheir** [sshuttle/sshuttle#481]
When I use

`sshuttle -r my-host -v 10.13.0.0/16`

with version `1.0.2`, I'm getting the follow error:

```
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.8.3
firewall manager: ready method name nat.
IPv6 enabled: None
UDP enabled: False
DNS enabled: False
User enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
Starting client with Python version 3.8.3
c : connecting to server...
All keys already loaded
Warning: Permanently added the ECDSA host key for IP address '18.213.216.154' to the list of known hosts.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 18, in <module>
TypeError: module.__init__() argument 1 must be string, not unicode
c : fatal: server died with error code 1
```

I wasn't having this issue in version `0.78.5`. Looking at that the history of `assembler.py`, that line was last changed in #449 . I wonder if something changed there that wasn't properly converting unicode to a string?

**Comment by adrianlzt** [comment]
#449 it is not compatible with py2

Python3.8:
```
sys.stdin.readline().strip() -> bytes
sys.stdin.readline().strip().decode("ASCII") -> str
```

Python2.7.5:
```
sys.stdin.readline().strip() -> str
sys.stdin.readline().strip().decode("ASCII") -> unicode
```

But as stated in the [changelog of version 1.0])https://sshuttle.readthedocs.io/en/stable/changes.html#id4), python 2.6 and 2.7 is not longer supported.

This is sad, because we cannot longer use "old" servers as remote servers.

**Comment by adrianlzt** [comment]
This error could be fixed easily, but then it breaks trying to import "which", _which_ is only py3.
And I guess that will continue to break.

**Comment by salt-mountain** [comment]
So what is the thought process about accepting that this breaks support to connect to older machines / machines that are still running Python2.7? This effectively broke how we tunnel into bastions for private networks running on AWS and we're now forced to pin sshuttle to 0.78.5.

**Comment by brianmay** [comment]
I don't think anybody needs convincing here.

But I simply don't have the time or motivation to try to come up with something that works with Python 2.7 and Python 3.8. Plus Python 2.7 is officially no longer supported.

If you want to produce a pull request that will mean sshuttle works with both Python 2.7 and Python 3.8, then please go ahead and do so.

**Comment by brianmay** [comment]
Closing in favor of #469 ; will reopen if required.

**Comment by ElijahLynn** [comment]
I am getting this same error with 3.6.10 and 3.8.3.

**Comment by brianmay** [comment]
@ElijahLynn What version of Python do you have running on the *server*?

**Comment by ElijahLynn** [comment]
> @ElijahLynn What version of Python do you have running on the _server_?

Looks like Python 2.7.18 is on the server. 

I also downgraded to my client side to sshuttle 1.0.2 which was working fine last week before I upgraded my system, which brought in the 1.0.3 update.

**Comment by johnchlorophyll** [comment]
I can't get it working too on my mac after upgrading to 1.0.3 (I'm using 0.78.5_2 before and brew upgrade it).
Looks like the new version won't automatically call python3 in the remote server thus I got the same error. 

One possible solution is to specify python path for remote server like:
sshuttle --dns -r <username>@<remote ip> 0/0 --python=/usr/local/bin/python3

PS. This is only tested on MacOS (Catalina) with client 1.0.3 with brew installed python 3.8 and remote server MacOS(Mojave) with only system preinstalled python 3.
Hope this can help for people who have such error.

**Comment by krrkrr** [comment]
Hi... I got this error on one of the macs I managed. The other ten, with the same version of sshuttle and python are doing fine but one mac is giving me the same error. I've reinstall python 3 on both mac (sshuttle client and server) with homebrew... I'm still having the error msg.... what can I do ?
