### ISSUE TITLE
Latest version not available via apt install

### ISSUE THREAD

**Issue by doktorjw** [sshuttle/sshuttle#482]
Following the install instructions, the latest I can get is 0.78.5. What repo would I have to add in order for an apt install to install latest version?

**Comment by PresGas** [comment]
@doktorjw , did you talk with the package maintainer for your package (not sure if you are running Debian/Ubuntu or another deb flavor)? They will have to pull the latest and package it for your distribution.
The right side of this page should help you a bit with Debian:
https://packages.debian.org/buster/sshuttle
Same for Ubuntu:
https://packages.ubuntu.com/eoan/sshuttle

**Comment by doktorjw** [comment]
Yeah, it's unbuntu that I'm using. I was hoping there's a repo the latest was in, and I could just add that repo to my list.

Of course, I could clone & build, too, as an alternative ... :/

**Comment by PresGas** [comment]
It has been tricky with the ending of python2 and some python 3.8 issues. You could look at using pip?

https://sshuttle.readthedocs.io/en/stable/installation.html

I did try it previously and had no issues. I do tend to like to stick with the packages too though.

**Comment by brianmay** [comment]
I just uploaded version 1.0.3 to Debian/unstable. I imagine Ubuntu will pick up on this soon.
