### ISSUE TITLE
SSHUTTLE not working

### ISSUE THREAD

**Issue by cauasiqueira** [sshuttle/sshuttle#485]
➜  ~ sshuttle -V
1.0.2

MacOS Catalina
10.15.3

Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.8.3
firewall manager: ready method name pf.
IPv6 enabled: True
UDP enabled: False
DNS enabled: True
User enabled: False
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening on ('127.0.0.1', 12300).
DNS listening on ('::1', 12299, 0, 0).
DNS listening on ('127.0.0.1', 12299).
Starting client with Python version 3.8.3 ===> Python 3.8 version
c : connecting to server...

        !!! Este servidor deve ser acessado somente por pessoas autorizadas !!!

Verification code:
Password:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 18, in <module>
TypeError: module.__init__() argument 1 must be string, not unicode
c : fatal: expected server init string b'SSHUTTLE0001'; got b''

**Comment by PresGas** [comment]
This looks similar to this:

https://github.com/sshuttle/sshuttle/issues/381

Is python 2 on your Mac and can you try the work around? Maybe 3.7.x would also work.

**Comment by brianmay** [comment]
What version of Python do you have on the server? Guessing it is only Python 2.7.

**Comment by brianmay** [comment]
Closing in favor of #469 ; will reopen if required.
