### ISSUE TITLE
fatal error on macOS when using --dns or --ns-hosts option

### ISSUE THREAD

**Issue by hth2** [sshuttle/sshuttle#491]
when running sshuttle on mac, I get the following error:

```
sshuttle -r remote-host --ns-hosts=abc 192.168.1.0/24
client: Connected.
fatal: ['pfctl', '-a', 'sshuttle-12300', '-f', '/dev/stdin'] returned 1
client: fatal: cleanup: ['sudo', '-p', '[local sudo] Password: ', '/usr/bin/env', 'PYTHONPATH=/usr/local/Cellar/sshuttle/1.0.3/libexec/lib/python3.8/site-packages', '/usr/local/Cellar/sshuttle/1.0.3/libexec/bin/python3.8', '/usr/local/bin/sshuttle', '--method', 'auto', '--firewall'] returned 99

```
I can sudo without password, but still sshuttle expects a password for sudo.

I also tried to run sshuttle as sudo, to get around the necessity to enter password. This time another error:

```
sudo sshuttle -e 'ssh -i /Users/xyz/.ssh/id_rsa' -r remote-host --ns-hosts=abc 192.168.1.0/24
client: Connected.
fatal: ['pfctl', '-a', 'sshuttle-12300', '-f', '/dev/stdin'] returned 1
client: fatal: cleanup: ['/usr/local/Cellar/sshuttle/1.0.3/libexec/bin/python3.8', '/usr/local/bin/sshuttle', '--method', 'auto', '--firewall'] returned 99

```

Any hint what else I can try? I am using sshuttle version 1.0.3, installed using homebrew

**Comment by danna2019** [comment]
Same as version 1.05.

**Comment by skuhl** [comment]
Does `abc` resolve to a hostname on the local machine (that you are running the sshuttle command on)? Setting `abc` to something that isn't resolvable is the only way I was able to reproduce this issue. 

If you are specifying the DNS server that should be used on the remote side, then you should use --to-ns.  --ns-hosts is used to specify the addresses of DNS servers you want sshuttle to intercept on the local machine.

Pull request #658, if merged, adds additional error reporting when pfctl fails to help with debugging this situation.

**Comment by hth2** [comment]
thank you @skuhl for the hint; indeed I should have used `--to-ns`. I have tested again with latest version of sshuttle, things seem to work as expected. Sorry for the noise.
