### ISSUE TITLE
how can I get a proxy remote ipv6?

### ISSUE THREAD

**Issue by Hurray0** [sshuttle/sshuttle#525]
My localhost only has an ipv4 support, and remote host has both ipv4+ipv6 support.
I wanna use `sshuttle` command to get a proxy to the remote host, and thus I can pass through the ipv6 website.
My current command has no use, which is:
```
sshtule -v -r --dns remote-host:port ::/0 0.0.0.0/0
```

**Comment by brianmay** [comment]
See https://sshuttle.readthedocs.io/en/stable/tproxy.html
