### ISSUE TITLE
Uses much memory when run with pypy3

### ISSUE THREAD

**Issue by mkesper** [sshuttle/sshuttle#530]
When run with pypy3, sshuttle uses much more memory.
With about 6400 entries in /etc/hosts,
- with Cpython, sshuttle claims about 20MB virtual and 15MB resident memory.
- with pypy3, sshuttle claims about 120MB virtual and 110MB resident memory.

OS: Debian testing

python3
Python 3.8.6 (default, Sep 25 2020, 09:36:53) 
[GCC 10.2.0] on linux

pypy3
Python 3.6.9 (7.3.2+dfsg-2, Sep 26 2020, 23:01:23)
[PyPy 7.3.2 with GCC 10.2.0] on linux

**Comment by skuhl** [comment]
It isn't clear to me that this is the fault of sshuttle. As far as I know, pypy usually consumes more memory than cpython. https://stackoverflow.com/q/29000279/474549

**Comment by mkesper** [comment]
Probably. Closing this.
