### ISSUE TITLE
Communication fails at random interval

### ISSUE THREAD

**Issue by rayjanoka** [sshuttle/sshuttle#532]
Hey, I'm new to sshuttle, but having some issues on Ubuntu 20.04. It works fine for a while maybe 5 to 20 minutes then communication stops, there is no error, all DNS queries fail, and I have to restart sshuttle. I haven't seen any issues with the ssh session running next to sshuttle.

I'm running it like this
➜ sshuttle --dns -vr ec2-user@PUBLIC_IP 10.0.0.0/8 --ssh-cmd 'ssh -i .private-dev-bastion-pem.pem'

Here are the logs from two different failures

https://gist.github.com/rayjanoka/0cf0cdcfaa79a6a839e3326b9414e14e

https://gist.github.com/rayjanoka/d3006df4455525b621659d73c113d94e

**Comment by rayjanoka** [comment]
thanks for answering @sudofox!

My sshuttle IP is a public IP and I'm using 10.x.x.x/8 as the routable subnet so should I really need to exclude localhost and my server's public IP since it doesn't fall in the routable subnet range?

**Comment by sudofox** [comment]
Good point. Maybe not in that case. Passing those flags are more for when you want to route everything through it so it doesn't get all wonky trying to route through itself :D

**Comment by rayjanoka** [comment]
I tried version `0.78.5` and a bleeding-edge `1.0.5.dev19+g9eaed73` and I have the same issue.

When it happens all communication fails, I can't query DNS or connect directly to IPs through sshuttle.

**Comment by rayjanoka** [comment]
Any thoughts on troubleshooting this? It doesn't seem like the logs are giving us anything...

**Comment by skuhl** [comment]
I found that similar issues occured for me when the underlying SSH process exited (but sshuttle didn't notice). sshuttle would continue to run and consume 100% of a cpu core. 

Can you confirm that the underlying ssh process is still running on your client machine when the problem occurs? Does sshuttle consume a lot of CPU when the problem occurs? If so, maybe this is related to issue #494 and merge #520 makes it so sshuttle exits in this case. Changing ServerAliveInterval or TCPKeepAlive settings in ssh might help if the ssh process id dying due idleness.

**Comment by rayjanoka** [comment]
hey @skuhl - thanks for this. I'll give this latest version a shot, but I'm not seeing a spike in CPU usage when mine stops working.
