### ISSUE TITLE
Cannot intercept DNS request when client using D-Bus based systemd-resolved interface

### ISSUE THREAD

**Issue by Flast** [sshuttle/sshuttle#535]
AFAK, sshuttle intercepts DNS request by filewall redirection. But some very recent applications uses D-Bus based systemd-resolved interface, thus no redirection will work.

e.g. In Fedora rawhide, `host` command issues DNS query via UDP and works, however 'ping' command do via D-Bus and failure.

I didn't try in other distribution, but I believe `resolvectl query <hostname>` or `systemd-resolve <hostname>` can be reproduce this issue.

Tested with `1.0.4-1.fc34` (fedora rawhide)

**Comment by brianmay** [comment]
Kohei Takahashi <notifications@github.com> writes:

> e.g. In Fedora rawhide, `host` command issues DNS query via UDP and
> works, however 'ping' command do via D-Bus and failure.

ping will never work, because sshuttle does not work with ICMP packets.
Only TCP and possibly UDP. Nothing to do with D-Bus here.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by Flast** [comment]
> Kohei Takahashi <notifications@github.com> writes:
> e.g. In Fedora rawhide, `host` command issues DNS query via UDP and works, however 'ping' command do via D-Bus and failure.
> ping will never work, because sshuttle does not work with ICMP packets. Only TCP and possibly UDP. Nothing to do with D-Bus here. -- Brian May <brian@linuxpenguins.xyz> https://linuxpenguins.xyz/brian/

True. But ping fails with `ping: ****: Name or service not known`, it means name resolution failure.

**Comment by rayjanoka** [comment]
I think I see this on Ubuntu 20.04...?

I get sshuttle going

```bash
$ sshuttle --dns -vr ec2-user@PUBLIC_IP 10.0.0.0/8 --ssh-cmd 'ssh -i .private-dev-bastion-pem.pem'
```

Query some domain within my sshuttle domain successfully with `nslookup`

```bash
$ nslookup argocd-admin.dev.domain.io
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
argocd-admin.dev.domain.io	canonical name = internal-dev-prometheus-t-x-bootstrap-adm-111.<region>.elb.amazonaws.com.
Name:	internal-dev-prometheus-t-x-bootstrap-adm-111.<region>.elb.amazonaws.com
Address: 10.12.89.51
Name:	internal-dev-prometheus-t-x-bootstrap-adm-111.<region>.elb.amazonaws.com
Address: 10.12.63.200
Name:	internal-dev-prometheus-t-x-bootstrap-adm-111.<region>.elb.amazonaws.com
Address: 10.12.67.17
```

The same query fails via `resolvectl query`

```bash
$ resolvectl query argocd-admin.dev.domain.io
argocd-admin.dev.domain.io: resolve call failed: 'argocd-admin.dev.domain.io' not found
```

**Comment by skuhl** [comment]
To correct this issue, I think we'd need to call "resolvectl dns" to save the original settings, then call "sudo resolvectl dns <iface> <dns1> <dns2> ..." and then later restore to the original values when sshuttle exits.

**Comment by skuhl** [comment]
I submitted a pull request that should fix this issue as long as we are talking about plain DNS requests that resolved generates to port 53. It uses a resolv.conf file that systemd stores outside of /etc to find the addresses to intercept. No need to tell resolved to use different servers as I suggested in my previous comment.

One remaining issue is that systemd-resolved can also use DNS over TLS which uses a different port than what sshuttle intercepts. We also don't yet do anything to intercept DNS over HTTPS traffic that might get sent to the servers. But, perhaps that is a separate issue.

**Comment by Flast** [comment]
> I submitted a pull request that should fix this issue as long as we are talking about plain DNS requests that resolved generates to port 53. It uses a resolv.conf file that systemd stores outside of /etc to find the addresses to intercept. No need to tell resolved to use different servers as I suggested in my previous comment.

I tried the patch and it seems that works fine.
 
> One remaining issue is that systemd-resolved can also use DNS over TLS which uses a different port than what sshuttle intercepts. We also don't yet do anything to intercept DNS over HTTPS traffic that might get sent to the servers. But, perhaps that is a separate issue.

Sounds reasonable.

**Comment by skuhl** [comment]
Pull request #552 was merged. This problem should be fixed.

**Comment by Flast** [comment]
Thanks!
