### ISSUE TITLE
method tproxy requires IPv6

### ISSUE THREAD

**Issue by juw** [sshuttle/sshuttle#54]
Hi,

I tried to use sshuttle with the tproxy method:
`sshuttle --method=tproxy --dns --daemon --pidfile=/run/sshuttle.pid --remote=x@xxx.xxx.xxx.xxx xxx.xxx.xxx.xxx/xx`
I got errors, that the ip6tables mangle module could not be loaded and therefore sshuttle did not work. Using the default method, sshuttle worked. I do not need IPv6, since the networks I am using are IPv4 only. Why does sshuttle with the tproxy method try to set up (and seems to require) IPv6 when it does not do this with the default NAT method?

Cheers.

**Comment by brianmay** [comment]
ipv6 support is enabled by default with tproxy. You should be able to disable it by providing a parameter like `--listen 127.0.0.1` to sshuttle.
