### ISSUE TITLE
[Question]: SSH proxy

### ISSUE THREAD

**Issue by dclong** [sshuttle/sshuttle#540]
Is it possible to specify a SSH proxy for a remote server (to SSH tunnel into)? For example, if I want to redirect all traffic through server A. However, server A can only be SSH tunnel into via another machine B. I know it's possible to configure machine B as the SSH proxy when visiting server A in the SSH config file. However, I want to know whether there is a way to configure this in sshuttle.

**Comment by skuhl** [comment]
Not that I know of. However, sshuttle should use the settings in the SSH config file, so I think you should be able to set it up that way.
