### ISSUE TITLE
[Question]: Can sshuttle use an existing SSH tunnel?

### ISSUE THREAD

**Issue by dclong** [sshuttle/sshuttle#542]
If server S can be visited through a bastion machine B and there's already a SSH tunnel from client C to the bastion server B, is there anyway for sshuttle use the existing SSH tunnel to connect the server S?

**Comment by skuhl** [comment]
Not in sshuttle directly. But doesn't ssh support something like this with ControlMaster? If you can get ssh to reuse a connection, I believe sshuttle will do so too since it calls ssh.

**Comment by dclong** [comment]
@skuhl That's a good idea. Will give it try.
