### ISSUE TITLE
[FreeBSD 12.2] sshuttle should be clearer about needing 'pf' to be enabled

### ISSUE THREAD

**Issue by willbprog127** [sshuttle/sshuttle#583]
Greetings!

I'm using FreeBSD 12.2 amd64 with sshuttle 1.0.5 installed from `pip`. It installed in `/home/will/.local/bin`.

When I first ran sshuttle, it displayed an error about `pfctl`.  FreeBSD currently does not enable the `pf` firewall by default.

Can you please display a clearer error message about sshuttle needing `pf` enabled?  

The following are necessary in `/etc/rc.conf`:
```
gateway_enable="yes"
pf_enable="yes"
pflog_enable="yes"
```
Thanks! :+1:

**Comment by skuhl** [comment]
If the pfctl command fails, pull request #658 adds code to print the output of the pfctl command (previously it only reported the exit status code, not the pfctl command output). Does that output help the user, in this case, figure out what the problem is?

**Comment by willbprog127** [comment]
@skuhl This seems like a reasonable compromise.  Since I don't use FreeBSD at this time, I can't test this out, but will go ahead and close.

Thanks! :+1:
