### ISSUE TITLE
Debian apt-get thinks version 0.78.5-1 is the newest version

### ISSUE THREAD

**Issue by Rob-Geebivi** [sshuttle/sshuttle#589]
Hi,

I'm new to sshuttle, so my apologies in advance if this is a mistake on my part...
After setting everything up for the first time, I ran into the "[Errno 88] Socket operation on non-socket" upon trying to start the server. After finding the issue in here from ~1yr ago and seeing it has since been resolved (#388), I realized my sshuttle version is out of date. Doing another "apt-get install sshuttle" repeats that "sshuttle is already the newest version (0.78.5-1)." ... which is obviously not true :)

I just wanted others to be aware so the new version can be uploaded on the back-end for easier updating.
Thank you!

**Comment by brianmay** [comment]
Debian unstable has the latest version:

https://packages.debian.org/search?keywords=sshuttle

You must be on buster. Unfortunately I cannot update buster to a new upstream version, due to Debian release rules.

**Comment by Rob-Geebivi** [comment]
How would I go about installing bullseye (1.0.5-1) then? I've already tried cloning from the github repo, but the install hangs on the "/setup.py install" command.
