### ISSUE TITLE
Using sshuttle on top of sshuttle to connect to reverse tunnels

### ISSUE THREAD

**Issue by awonderfulescapade** [sshuttle/sshuttle#597]
Hi all

I've used sshuttle for a long time in the inf pentesting domain. I'd been on 0.75 for ages, but upgraded to the latest today for a client test and ran into some issues.

We tend to deploy VMs to client sites which then create outbound connections to a cloud instance. A consultant will then connect to the cloud instance via ssh, then connect to a port on localhost which is where the client site machine has its ssh connection available.

I would use sshuttle in this scenario, as it automagically allows you to connect to the many systems you'd find on a client network without any messing around:

Terminal 1 - sshuttle -v --method tproxy -r consultant@cloudlinuxcom.com:22 127.0.0.1/32
Terminal 2 - sshuttle -v -r clientsiteuser@localhost:2201 -N

Except this doesn't work anymore, due to a check performed on lines 334-337 in client.py. I can see what it is trying to do and I've commented it out to allow sshuttle to work its magic, but if I might humbly make a suggestion, it would be amazing if this check was just an option rather than mandatory. I'm no developer, or I'd just do it and make a PR. :-)

Really grateful for this tool and feels awkward to point out that something that I benefit from for free doesn't quite work for my specific use case, but here it is all the same.

Either which way, thank you for this awesome swiss army knife of ssh-proxy-goodness.

**Comment by brianmay** [comment]
Can you please confirm that reference? I am not seeing anything relevant on line 334-337 of `client.py` https://github.com/sshuttle/sshuttle/blob/master/sshuttle/client.py#L334

**Comment by awonderfulescapade** [comment]
Sorry! My bad - too many late nights.

It is lines 369-372:

```
   if dstip[1] == sock.getsockname()[1] and islocal(dstip[0], sock.family):
        debug1("-- ignored: that's my address!")
        sock.close()
        return
```

**Comment by brianmay** [comment]
awonderfulescapade <notifications@github.com> writes:

> Except this doesn't work anymore, due to a check performed on lines
> 334-337 in client.py. I can see what it is trying to do and I've
> commented it out to allow sshuttle to work its magic, but if I might
> humbly make a suggestion, it would be amazing if this check was just
> an option rather than mandatory. I'm no developer, or I'd just do it
> and make a PR. :-)

That code has been there a long time. It was introduced in commit
651b9452998e210ba208ff9905095d7cc23683a7, in 2010.

Makes me wonder how ever this worked for you though.

The commit message "Prevent loopbacks caused by telnetting to the
transproxy port directly."

Possibly this would be better solved in the IP rules, then here. Not
sure.

Pull requests welcome. Unfortunately I don't have any time to look at
this myself.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by awonderfulescapade** [comment]
> That code has been there a long time. It was introduced in commit [651b945](https://github.com/sshuttle/sshuttle/commit/651b9452998e210ba208ff9905095d7cc23683a7), in 2010. Makes me wonder how ever this worked for you though. The commit message "Prevent loopbacks caused by telnetting to the transproxy port directly." Possibly this would be better solved in the IP rules, then here. Not sure. Pull requests welcome. Unfortunately I don't have any time to look at this myself. -- Brian May <brian@linuxpenguins.xyz> https://linuxpenguins.xyz/brian/

Wow - interesting. Appreciate the insight. Clearly my use of this in the described way is a bit of an outlier. And no, I have no idea how it worked at all if it has been there that long!

I'll set myself an open task for my next non-billable day and see if I can knock up an argument option to disable that check. It would be a nice small personal goal I suppose, having never submitted a PR to any project ever! :-)

Thanks again

**Comment by yamlCase** [comment]
This works for me when connecting through a useless temporary host to a shared "toolbox" host.

```
Terminal 1 - sshuttle -r consultant@useless-temporary-host <ip of toolboxhost>/32
Terminal 2 - sshuttle -r clientsiteuser@toolboxhost <target subnet>
```
