### ISSUE TITLE
sshuttle in daemon mode silently fails when it cannot create pidfile

### ISSUE THREAD

**Issue by Sh1ftry** [sshuttle/sshuttle#598]
When running sshuttle in daemon mode with pidfile flag set to a file in a directory, to which current user does not have write permissions, the command silently fails without proper exit code.

### Steps to reproduce
1. Create a directory to which only root has write access `sudo mkdir directory-for-pidfile`
2. Run sshuttle in daemon mode `sshuttle --daemon --pidfile="./directory-for-pidfile/pid" --remote <some-remote> <some-cidr>`
3. Check output of `echo $?`
4. Check output of `pgrep -f sshuttle`

### Expected results
Sshuttle does not start and the exit code of the `sshuttle` command is different than 0.

### Actual results
Sshuttle does not start, but the exit code of the `sshuttle` command is 0.

**Comment by brianmay** [comment]
Fix merged.
