### ISSUE TITLE
Allow sshuttle to support calling Teleport as a command ( using -e ‘tsh ssh’ ) without choking

### ISSUE THREAD

**Issue by scatat** [sshuttle/sshuttle#599]
I'm trying to get sshuttle to invoke Teleport ( https://github.com/gravitational/teleport ) - an example command would be : `sshuttle  -e ‘tsh ssh’   -r 192.168.0.1 10.0.0.0/23`. This would then allow me to use sshuttle over Teleport's ssh connection. ( reference - https://goteleport.com/teleport/docs/user-manual/ ).

The command almost works. The problem is that teleport's wrapper around ssh doesn't process/handle the "--" and passes it on to the shell when we login, resulting in the error below. 

Would it be possible to please implement something which will remove the "--" when running via Teleport? 

**Note: There are many ways of doing this and I think I could add something really hacky and send you a PR but I fear that my solution would probably not be elegant, so please be prepared to teach me some python - be gentle as I am not a programmer by trade.** 

`c : which() found 'tsh' at /usr/local/bin/tsh
c : executing: ['/usr/local/bin/tsh', 'ssh', 'stephen.tan@10.235.9.122', '--', '/bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=6; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1486), "assembler.py", "exec"))\'"\'"\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
/bin/bash: --: invalid option
Usage:	/bin/bash [GNU long option] [option] ...
	/bin/bash [GNU long option] [option] script-file ...
GNU long options:
	--debug
	--debugger
	--dump-po-strings
	--dump-strings
	--help
	--init-file
	--login
	--noediting
	--noprofile
	--norc
	--posix
	--rcfile
	--restricted
	--verbose
	--version
Shell options:
	-ilrsD or -c command or -O shopt_option		(invocation only)
	-abefhkmnptuvxBCHP or -o option
error: Process exited with status 2
c : fatal: c : server died with error code 2`

Reference: https://github.com/sshuttle/sshuttle/blob/master/sshuttle/ssh.py#L192

**Comment by sinh-tran-ts** [comment]
Add config ssh
`tsh config >> ~/.ssh/config`
Example Add end of line:
```
Host gcp-cloud-*
    Port 3022
    ProxyCommand "/usr/local/bin/tsh" proxy ssh --cluster=teleport.local --proxy=teleport.local:443 %r@%h:%p
Host gcp-cloud-compute01
   User centos
 Host gcp-cloud-compute02
   User centos
```

**Comment by scatat** [comment]
Problem is that we have Proxy Disabled in our envs for Security Reasons. Sad times
