### ISSUE TITLE
Probable User Error - sshuttle fails on DNS call

### ISSUE THREAD

**Issue by larrypl** [sshuttle/sshuttle#615]
This error occurs in MacOS probably based on permissions of the terminal emulator at the time of invocation. For example, currently this always fails in Terminal.app and xterm, but succeeds in extraterm; in the past it's worked on xterm but failed in Terminal.app. This only occurs with ` --dns` specified. I don't know if anything can be done about this, but thought I'd submit this in case there were a workaround.

sshuttle is great!

Here's the relevant (I hope) error messages and surrounds:

    c : Remaining DNS requests: 4
    c : Remaining UDP channels: 0
    c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[11] x=[] (fullness=152/0)
    c :   Ready: 3 r=[] w=[11] x=[]
    c : mux wrote: 47/47
    c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=152/0)
     s:   Ready: 1 r=[0] w=[] x=[]
     s: <  channel=1 cmd=DNS_REQ len=37
     s: Incoming DNS request channel=1.
     s: Found DNS servers in /etc/resolv.conf: ['10.210.130.101', '10.210.130.102']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "assembler.py", line 45, in <module>
      File "sshuttle.server", line 397, in main
      File "sshuttle.ssnet", line 616, in runonce
      File "sshuttle.ssnet", line 504, in callback
      File "sshuttle.ssnet", line 492, in handle
      File "sshuttle.ssnet", line 411, in got_packet
      File "sshuttle.server", line 353, in dns_req
      File "sshuttle.server", line 172, in __init__
      File "sshuttle.server", line 195, in try_send
    TypeError: a bytes-like object is required, not 'str'
    c :   Ready: 3 r=[11] w=[] x=[]
    c : Waiting: 2 r=[5, 7, 8, 9] w=[] x=[] (fullness=152/0)
    c :   Ready: 2 r=[9] w=[] x=[]
    c : Accept UDP using recvfrom.
    c : DNS request from ('192.168.50.242', 61502): 37 bytes
    c :  > channel=5 cmd=DNS_REQ len=37 (fullness=152)
    c : Remaining DNS requests: 5
    c : Remaining UDP channels: 0

**Comment by larrypl** [comment]
This may be caused by a python 3.9 upgrade - it seems to now occur in all terminals.

**Comment by patrislav1** [comment]
I got the same error on Linux with Python 3.8. Here's a workaround:

https://github.com/sshuttle/sshuttle/pull/618

**Comment by larrypl** [comment]
Thanks! Good to know it's not really my terminal emulation!
