### ISSUE TITLE
sshuttle for non-root user

### ISSUE THREAD

**Issue by vallard** [sshuttle/sshuttle#619]
I know the docs state the requirement for sudo/root access to make shuttle work, however, I'm wondering if there is anyway this can work for just a normal user.  In my environment I don't have root access and would love to just open up this VPN connection for this user only.  The environment is ubuntu.  

Thanks for this wonderful tool and all the work you do!

**Comment by patrislav1** [comment]
https://sshuttle.readthedocs.io/en/stable/usage.html#sudoers-file

**Comment by vallard** [comment]
*sigh*, yes, I understand sudoers.  I guess it won't work with my situation.  I'm using circle ci with a container so the container has no root privileges so even though I'm root on the container it won't let me modify the network stack.  I can make it work using circle ci VMs but not in containers.  I was hoping there was a way to generate the iptables or whatever networking rules for just the individual user.  Thanks for the great tool!
