### ISSUE TITLE
how can i create sshuttle connection in startup

### ISSUE THREAD

**Issue by hiradsajde** [sshuttle/sshuttle#628]
i need to create bash script for connecting to sshuttle. i use this command for connect to my server
```
sshuttle --dns -NHr user@ip 0/0
password : password
```
sshuttle read password. how can i enter password in my .sh file with out typing? (the file runned in startup)

**Comment by perfecto25** [comment]
I would suggest you create a sshuttle service, heres a guide,

it uses a dedicated 'sshuttle' user with a SSH keypair + systemd startup script that will run as service on startup.

you configure your connection mapping in a json file,

```
{
  "user@ip": ["0/0"]
}
```

https://perfecto25.medium.com/using-sshuttle-as-a-service-bec2684a65fe

**Comment by hiradsajde** [comment]
thanks

> I would suggest you create a sshuttle service, heres a guide,
> 
> it uses a dedicated 'sshuttle' user with a SSH keypair + systemd startup script that will run as service on startup.
> 
> you configure your connection mapping in a json file,
> 
> ```
> {
>   "user@ip": ["0/0"]
> }
> ```
> 
> https://perfecto25.medium.com/using-sshuttle-as-a-service-bec2684a65fe

thanks. my issue solved :+1:
