### ISSUE TITLE
Setup "on" Windows

### ISSUE THREAD

**Issue by mrkschan** [sshuttle/sshuttle#64]
I know that Windows won't easily get native support from sshuttle, though, we can use VM on Windows to do so. I have written a short tips on how to do so at https://coderwall.com/p/adfxgw/sshuttle-on-windows. Can we add a pointer on the docs here so that others can make use of sshuttle on Windows?

**Comment by thshdw** [comment]
@mrkschan As a user of shuttle I think your solution is very clever. I would suggest that a cmd script be made.. the script 
1.) takes start / stop as its switches. 
2.) Holds the ip of the VM has a variable 

win-sshuttle start create's your route.
win-shuttle stop removes the route.

**Comment by brianmay** [comment]
@mrkschan Do you have any objections if I copy from your website and include in the sshuttle documentation? I can acknowledge you or your website as the source if you want.

@thshdw Any tested contributions appreciated. Thanks.

**Comment by mrkschan** [comment]
@brianmay I don't really care about the attribution :) Just put the content in docs is great enough since it helps other :)

**Comment by mrkschan** [comment]
@thshdw I have some `.rb` scripts to bang things together but it's not reusable.

**Comment by brianmay** [comment]
Are you sure you need the -l parameter?

**Comment by mrkschan** [comment]
I'm not sure, if it just listen on local interface, would sshuttle handle the traffic from another IP?

I think I need `-l` when I share the tunnel to docker containers. http://stackoverflow.com/a/30837252/433662

**Comment by brianmay** [comment]
I note that in the stackoverflow question, that answer wasn't marked as accepted...

Looks like it might be correct. Odd.

Oh I see, from ``man iptables-extensions`` for the redirect target:

> It redirects the packet to the machine itself by changing the destination IP to the primary address of the incoming interface (locally-generated packets are mapped to the localhost address, 127.0.0.1 for IPv4 and ::1 for IPv6).

So, for example, if the packet comes in via eth0 and eth0 has an address of 192.168.2.13, then the packet will be directed to 192.168.2.13:12300, which implies that sshuttle must be listening on 192.168.2.13

**Comment by brianmay** [comment]
Fixed by #918.
