### ISSUE TITLE
--to-ns option is ignored because --dns was not used

### ISSUE THREAD

**Issue by brianjmurrell** [sshuttle/sshuttle#641]
I am running sshuttle as:

```
/usr/bin/sshuttle -e ssh --to-ns=10.8.0.10 --to-ns=10.8.0.23 --no-latency-control -l 12304 --ns-hosts 127.10.0.4 -Nr [redacted]@host.example.com 10.8.0.0/16 10.12.0.0/16
```

but it's telling me:

```
WARNING: --to-ns option is ignored because --dns was not used.
```

If I omit the `--to-ns=10.8.0.10 --to-ns=10.8.0.23` arguments, everything works as expected.  I am not sure I see why adding to that working configuration an instruction for sshuttle to ignore the remote `/etc/resolv.conf` and instead use the remote NSes that I tell it to should require `--dns` and therefore be incompatible with `--ns-hosts`.

**Comment by skuhl** [comment]
I think this was a bug introduced by an earlier commit I made. Does the code in pull request #643 fix this issue for you?

**Comment by skuhl** [comment]
Also, I believe if the --to-ns option is specified multiple times, the last one is used.
