### ISSUE TITLE
Adding a certain CIDR /16 address causes error

### ISSUE THREAD

**Issue by PresGas** [sshuttle/sshuttle#653]
I have tried adding a specific CIDER notation in my config and sshuttle fails with the following error.
`c : fatal: server died with error code 255`
I have put it in a couple of different areas in the config and added a couple of other arbitrary blocks with no impact. It seems that particular /16 causes a crash.
sshuttle version 1.0.4-1ubuntu4 (.deb)
Ubuntu 21.04
Python version 3.8.5

I have security concerns about putting the suspect CIDR address in a public forum. Please advise.

**Comment by skuhl** [comment]
Is the remote host in the /16 that causes the trouble? If so, you may need to exclude the remote host with -x if you use that address block.

In git, the error code 255 causes a message suggesting that adding the exclude may fix the problem. The examples in the man page have also been recently updated to remind people to do this. https://github.com/sshuttle/sshuttle/blob/master/docs/manpage.rst  So, if this is your problem, hopefully it won't be as confusing for others in the future.

**Comment by PresGas** [comment]
I confirm this works. I attempted to put the option in the .conf file, but that does not seem to work. Is there a syntax I am missing? I put in the following:

--exclude
xxx.xxx.xxx.xxx/32

**Comment by skuhl** [comment]
It works for if I put things in a config file or if I run it with the options on the command line. Do you get an error message when you put it in the config file? Are there significant differences in the output of sshuttle with -vvv when running with the config file vs without (for example, are the iptables rules that it sets the same?).

**Comment by PresGas** [comment]
@skuhl I was able to get it working with the config file. I wonder if I had an extra funky `/n` somewhere or an extra space? How sensitive is the config file to formatting? It seems to work now though!

**Comment by skuhl** [comment]
Glad it works. For config files, the code whitespace from the beginning and end of the line and removes lines that begin with '#'.

**Comment by PresGas** [comment]
Thanks so much for the review and help!
