### ISSUE TITLE
specify an alternate ssh key

### ISSUE THREAD

**Issue by thshdw** [sshuttle/sshuttle#67]
Is it possible to specify an alternate ssh key (_identity file_)
```
./sshuttle -i ~/.ssh/id_key5 --dns -H -vvr me@myserver.example.com 0/0
```

**Comment by brianmay** [comment]
Maybe the -e option? -e "ssh -i ~/.ssh/id_key5"

**Comment by thshdw** [comment]
Thanks, that worked!

**Comment by ElijahLynn** [comment]
Super helpful, this needs to be in the README!

**Comment by brianmay** [comment]
Pull requests appreciated :-)
