### ISSUE TITLE
Internet does not work if you are connected to Wireguard beforehand

### ISSUE THREAD

**Issue by DUOLabs333** [sshuttle/sshuttle#706]
I am on MacOS Big Sur and am connected to a Wireguard VPN. sshuttle connects, but now I can't connect to anything.

**Comment by GouravSardana** [comment]
Can you check you wiregaurd configurations ? There must be a flag (I don't remember) to make it work

**Comment by GouravSardana** [comment]
Change MTU to MTU = 1460

**Comment by DUOLabs333** [comment]
Didn't help -- same thing as before, with a lot of DNS requests showing up, but nothing resolving (though using IP addresses don't help either). I can still ping though.
