### ISSUE TITLE
0.77 release tarball broken: setuptools-scm was unable to detect version

### ISSUE THREAD

**Issue by jonathanunderwood** [sshuttle/sshuttle#71]
Building 0.77 on Fedora rawhide bails at:

```bash
+ CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic'
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'

Installed /builddir/build/BUILD/sshuttle-0.77/.eggs/setuptools_scm-1.10.1-py3.5.egg
Traceback (most recent call last):
  File "setup.py", line 60, in <module>
    keywords="ssh vpn",
  File "/usr/lib64/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.5/site-packages/setuptools/dist.py", line 272, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib64/python3.5/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/usr/lib/python3.5/site-packages/setuptools/dist.py", line 327, in finalize_options
    ep.load()(self, ep.name, value)
  File "/builddir/build/BUILD/sshuttle-0.77/.eggs/setuptools_scm-1.10.1-py3.5.egg/setuptools_scm/integration.py", line 19, in version_keyword
  File "/builddir/build/BUILD/sshuttle-0.77/.eggs/setuptools_scm-1.10.1-py3.5.egg/setuptools_scm/__init__.py", line 102, in get_version
  File "/builddir/build/BUILD/sshuttle-0.77/.eggs/setuptools_scm-1.10.1-py3.5.egg/setuptools_scm/__init__.py", line 80, in _do_parse
LookupError: setuptools-scm was unable to detect version for '/builddir/build/BUILD/sshuttle-0.77'.

Make sure you're not using GitHub's tarballs (or similar ones), as those don't contain the necessary metadata. Use PyPI's tarballs instead.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

**Comment by jonathanunderwood** [comment]
OK, so basically moving to using setuptools_scm means that the release tarballs created by github are broken. On the other hand, cloning the git repo and doing a python setup.py build sdist produces a tarball which works fine, by virtue of having the version information available in the PKG_INFO file.

**Comment by jonathanunderwood** [comment]
It seems to me the easiest way to fix this issue would be to make tarball releases available via PyPi as the canonical location for sources, rather than the github releases.

**Comment by brianmay** [comment]
Probably. The PyPi releases are also signed by me too, another advantage I think. Unfortunately I forgot to sign the 0.77 release, and it won't let me fix it up. I tried deleting version 0.77 and re-uploading it, however it won't let me upload this version anymore.

```
Submitting dist/sshuttle-0.77.tar.gz to https://pypi.python.org/pypi
Upload failed (400): This filename has previously been used, you should use a different version.
error: Upload failed (400): This filename has previously been used, you should use a different version.
```

So I suspect I will have to do a release of 0.78 to fix this. Will look at doing this tomorrow.

**Comment by jonathanunderwood** [comment]
Great. I don't know if you're aware, but the 0.77 tarball doesn't actually show up on the PyPi page as a download, as far as I can see.

**Comment by brianmay** [comment]
Yes, that was the result of me deleting it and not being able to upload it again :-(

**Comment by jonathanunderwood** [comment]
Ahh, right! 

On the bright side, I've now moved Fedora to this codebase (it was stuck on the 2012 old codebase due to lack of package maintenance), so hopefully that'll give the code some extra exposure.

**Comment by brianmay** [comment]
Great! Good to hear. Unfortunately this package was neglected for a while.

**Comment by brianmay** [comment]
Have released 0.77.1. PyPI should be fixed now. readthedocs has problems, am inclined to think that is readthedocs problem.

**Comment by brianmay** [comment]
Ok if I close this now?

**Comment by jonathanunderwood** [comment]
Yes, sorry, I meant to report back: I am now happily using the tarball from PyPi (0.77.2) which builds fine for the Fedora packages. Thanks for this.
