### ISSUE TITLE
Remove support for Python 3.6 and Python 3.7

### ISSUE THREAD

**Issue by brianmay** [sshuttle/sshuttle#716]
See  #713.

```
The conflict is caused by:
    sphinx 4.4.0 depends on importlib-metadata>=4.4; python_version < "3.10"
    pytest 6.2.5 depends on importlib-metadata>=0.12; python_version < "3.8"
    flake8 4.0.1 depends on importlib-metadata<4.3; python_version < "3.8"
```

If I am reading this correctly we won't have a problem should disappear with Python versions >= 3.8.

The failures occurred with Python 3.6 and Python 3.7, and the remaining tests were cancelled.

**Comment by brianmay** [comment]
Somehow this was resolved. Not sure how/why. Closing.

**Comment by brianmay** [comment]
Failure back again, changes reverted.

**Comment by Scherlac** [comment]
I have the same problem: 
> ERROR: Could not find a version that matches importlib-metadata<4.3,>=0.12,>=3.6,>=4.4 (from twine==3.8.0->-r /tmp/pipenvvpz84khsrequirements/pipenv-48uermxv-constraints.txt (line 8))
Tried: 0.0, 0.1, 0.1, 0.2, 0.2, 0.3, 0.3, 0.4, 0.4, 0.5, 0.5, 0.6, 0.6, 0.7, 0.7, 0.8, 0.8, 0.9, 0.9, 0.10, 0.10, 0.11, 0.11, 0.12, 0.12, 0.13, 0.13, 0.14, 0.14, 0.15, 0.15, 0.16, 0.16, 0.17, 0.17, 0.18, 0.18, 0.19, 0.19, 0.20, 0.20, 0.21, 0.21, 0.22, 0.22, 0.23, 0.23, 1.0.0, 1.0.0, 1.1.0, 1.1.0, 1.1.1, 1.1.1, 1.1.2, 1.1.2, 1.1.3, 1.1.3, 1.2.0, 1.2.0, 1.3.0, 1.3.0, 1.4.0, 1.4.0, 1.5.0, 1.5.0, 1.5.1, 1.5.1, 1.5.2, 1.5.2, 1.6.0, 1.6.0, 1.6.1, 1.6.1, 1.7.0, 1.7.0, 2.0.0, 2.0.0, 2.1.0, 2.1.0, 2.1.1, 2.1.1, 2.1.2, 2.1.2, 2.1.3, 2.1.3, 3.0.0, 3.0.0, 3.1.0, 3.1.0, 3.1.1, 3.1.1, 3.2.0, 3.2.0, 3.3.0, 3.3.0, 3.4.0, 3.4.0, 3.5.0, 3.5.0, 3.6.0, 3.6.0, 3.7.0, 3.7.0, 3.7.1, 3.7.1, 3.7.2, 3.7.2, 3.7.3, 3.7.3, 3.8.0, 3.8.0, 3.8.1, 3.8.1, 3.8.2, 3.8.2, 3.9.0, 3.9.0, 3.9.1, 3.9.1, 3.10.0, 3.10.0, 3.10.1, 3.10.1, 4.0.0, 4.0.0, 4.0.1, 4.0.1, 4.1.0, 4.1.0, 4.2.0, 4.2.0, 4.3.0, 4.3.0, 4.3.1, 4.3.1, 4.4.0, 4.4.0, 4.5.0, 4.5.0, 4.6.0, 4.6.0, 4.6.1, 4.6.1, 4.6.2, 4.6.2, 4.6.3, 4.6.3, 4.6.4, 4.6.4, 4.7.0, 4.7.0, 4.7.1, 4.7.1, 4.8.0, 4.8.0, 4.8.1, 4.8.1, 4.8.2, 4.8.2, 4.8.3, 4.8.3, 4.9.0, 4.9.0, 4.10.0, 4.10.0, 4.10.1, 4.10.1, 4.11.0, 4.11.0
There are incompatible versions in the resolved dependencies:
  importlib-metadata (from click==8.0.3->sphinx-click==3.1.0->-r /tmp/pipenvvpz84khsrequirements/pipenv-48uermxv-constraints.txt (line 10))
  importlib-metadata (from pre-commit==2.17.0->-r /tmp/pipenvvpz84khsrequirements/pipenv-48uermxv-constraints.txt (line 6))
  importlib-metadata<4.3 (from flake8==4.0.1->pytest-flake8==1.0.7->-r /tmp/pipenvvpz84khsrequirements/pipenv-48uermxv-constraints.txt (line 4))
  importlib-metadata>=0.12 (from pluggy==1.0.0->pytest==7.0.1->-r /tmp/pipenvvpz84khsrequirements/pipenv-48uermxv-constraints.txt (line 7))
  importlib-metadata>=0.12 (from pytest==7.0.1->-r /tmp/pipenvvpz84khsrequirements/pipenv-48uermxv-constraints.txt (line 7))
  importlib-metadata>=0.12 (from virtualenv==20.13.1->pre-commit==2.17.0->-r /tmp/pipenvvpz84khsrequirements/pipenv-48uermxv-constraints.txt (line 6))
  importlib-metadata>=3.6 (from keyring==23.5.0->twine==3.8.0->-r /tmp/pipenvvpz84khsrequirements/pipenv-48uermxv-constraints.txt (line 8))
  importlib-metadata>=3.6 (from twine==3.8.0->-r /tmp/pipenvvpz84khsrequirements/pipenv-48uermxv-constraints.txt (line 8))
  importlib-metadata>=4.4 (from sphinx==4.4.0->-r /tmp/pipenvvpz84khsrequirements/pipenv-48uermxv-constraints.txt (line 3))

**Comment by brianmay** [comment]
Python 3.9 should be fine I think. Just Python 3.6 and Python 3.7.

It probably would help if we moved the Sphinx requirement to `requirements-docs.txt` and have readthedocs use this file. That way we are not trying to install sphinx at the same time as pytest and flake8. It might just work.

Bad though, because we should really be testing that we can build the documentation in the CI, not being able to install the all the dependencies at the same time is likely to make this more tricky.

**Comment by brianmay** [comment]
If I am reading this correctly, pytest no longer supports also Python 3.6 https://blog.frankel.ch/start-rust/7/
