### ISSUE TITLE
sshuttle-1.1.0: unable to generate sudoers file on mac OS BigSur (11.6.4)

### ISSUE THREAD

**Issue by vishalwadhwa13** [sshuttle/sshuttle#740]
Hi,

I upgraded to the latest version of sshuttle and post that:
1. Existing sudoers file at `/private/etc/sudoers.d/sshuttle_auto` not being picked
2. Unable to generate new file - facing this error
  ```
[1] % sshuttle --sudoers

# WARNING: When you allow a user to run sshuttle as root,
# they can then use sshuttle's --ssh-cmd option to run any
# command as root.
Password:
Invalid sudoers filename: Final sudoers file location (/private/etc/sudoers.d/sshuttle_auto) does not begin with /etc/sudoers.d
Failed updating sudoers file.
```

**Comment by skuhl** [comment]
You can add the configuration to the sudo configuration yourself.  If you run sshuttle with  --sudoers-no-modify, you will see the configuration that --sudoers would use printed to the console.

However, be aware of the warning. Using this configuration means that the user can run sshuttle without a password, but with a little cleverness, the user can run any command without a password. See #631.

**Comment by vishalwadhwa13** [comment]
Understood. Thank you for the help.
