### ISSUE TITLE
command line option processing broken

### ISSUE THREAD

**Issue by brianmay** [sshuttle/sshuttle#75]
Looks like double dashed command line options do not work, they get completely ignored.

```
$ python -m sshuttle -vvvvr --eeeee=dddd 0/0
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.9
firewall manager: ready method name nat.
...
```

Seems to work under some circumstances:

```
$ python -m sshuttle --eeeee=dddd 0/0 
error: option --eeeee not recognized
```

Wonder if it is worth replacing sshuttle/options.py with something better.

**Comment by brianmay** [comment]
https://github.com/docopt/docopt might be a good choice.

**Comment by brianmay** [comment]
Would also consider argparse, if anybody wants to submit a patch :-)

**Comment by vieira** [comment]
I will take a look. I am more inclined to **argparse** as it is part of the standard library and using it instead of **docopt** would avoid the extra dependency.

I am also thinking of using **argparse** together with **configparser** so we could set some (or all or none) options in a configuration file. It would make life easier for people who use it as a daemon and would be more straightforward to package (?).

What do you think?

**Comment by brianmay** [comment]
Yes, I would prefer argparse, I think it will be the more flexible solution in the long run; It probably will be worth the effort. I have had a look at docopt, however think what I have is a mess - possibly because I have never used docopt before.

configparser does sound like a good idea. There use to be config file processing specific to the packaging stuff I removed in 974f9aee8165c7e93804f34da30e84c532d6ef93 - so you might want to look at that too (despite some rather strange quirks). I think the idea was you could configure multiple tunnels and have an init.d script automatically bring them up at system boot.

**Comment by vieira** [comment]
I have something working with argparse since last weekend but did not have the time this week to make any progress. Still needs testing, bug fixing and some polishing. I will probably leave configparser for another PR.

**Comment by brianmay** [comment]
Thanks for the update.

**Comment by brianmay** [comment]
Think I can close this now #82 merged.
