### ISSUE TITLE
excludes processing broken

### ISSUE THREAD

**Issue by brianmay** [sshuttle/sshuttle#779]
I might be mistaken, but when looking at the code, in particular:

https://github.com/sshuttle/sshuttle/blob/master/sshuttle/client.py#L337-L345

It looks like excludes are added to the tables after the includes. Which means they won't do anything.

As a result, I think this code doesn't do anything also:

https://github.com/sshuttle/sshuttle/blob/master/sshuttle/client.py#L889-L896

But I think most if not all firewalls exclude localhost traffic anyway, so this may not be required.

**Comment by skuhl** [comment]
I only looked at this for a moment, but isn't the include/exclude list sorted prior to use in each firewall method (with firewall.py's subnet_weight())? There still could be some kind of problem, but I haven't encountered issues yet.

**Comment by brianmay** [comment]
Yes, you are probably right. Reason I didn't notice when testing is probably because both subnets had the same weight.
