### ISSUE TITLE
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'

### ISSUE THREAD

**Issue by cy6erGn0m** [sshuttle/sshuttle#78]
sshuttle constantly crashes with

```
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.4.1
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
Starting client with Python version 3.4.1
c : connecting to server...
Traceback (most recent call last):
  File "/usr/bin/sshuttle", line 9, in <module>
    load_entry_point('sshuttle==0.77.2', 'console_scripts', 'sshuttle')()
  File "/usr/lib/python3.4/site-packages/sshuttle/cmdline.py", line 226, in main
    opt.daemon, opt.pidfile)
  File "/usr/lib/python3.4/site-packages/sshuttle/client.py", line 712, in main
    seed_hosts, auto_nets, daemon)
  File "/usr/lib/python3.4/site-packages/sshuttle/client.py", line 421, in _main
    options=dict(latency_control=latency_control))
  File "/usr/lib/python3.4/site-packages/sshuttle/ssh.py", line 88, in connect
    empackage(z, 'sshuttle.server') +
  File "/usr/lib/python3.4/site-packages/sshuttle/ssh.py", line 52, in empackage
    return b'%s\n%d\n%s' % (name.encode("ASCII"), len(content), content)
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'
cgmachine:/home/cy6ergn0m # 
```

**Comment by vieira** [comment]
You are using Python 3.4.x which is not supported. Try with either 2.7 or 3.5. I could fix that problem but likely there will be many others... On the client you have to be root anyway to run sshuttle, can you upgrade python?
For the server, where you don't necessarily have root there is #56.

**Comment by cy6erGn0m** [comment]
I see. Not sure it is safe to upgrade as it is distribution default version: possible damage is unpredictable, perhaps I can add some custom repository

**Comment by vieira** [comment]
@cy6erGn0m Fedora? Do you have 2.7 and 3.4 or just 3.4? I guess that at least in the situation where there is 2.7 and some unsupported 3.x as default we should fallback to 2.7.

I don't know if there is enough interest in making it work with 3.4 on the client. I did it for the server and I don't think it will ever get merged, which I kind of understand as it is painful to write code and test across all supported OSs and Python versions...

**Comment by brianmay** [comment]
It is possible #79 may not help here. It depends on if/how you are installing sshuttle (e.g. If you are installing it python 3.4 you may need to install it using python 2.7 instead) or if you are invoking it with the ./run command.

**Comment by cy6erGn0m** [comment]
@vieira opensuse. I have python 2.7 and 3.4 so fallback would help

**Comment by cy6erGn0m** [comment]
In fact I can install 3.5.1 from a "factory repo" but "factory" sounds like something may go wrong :)

**Comment by vieira** [comment]
Could you test #79?

**Comment by brianmay** [comment]
This was marked as fixed in #79, however there are not enough details given as to how sshuttle was started or why it tried to use Python 3.4; so the problem may not be fixed.

**Comment by CyberKiller40** [comment]
The issue still exists
OpenSUSE 13.2, having both python 2.7 and 3.4, sshuttle installed from pip

**Comment by brianmay** [comment]
@CyberKiller40 It sounds like you installed sshuttle using the Python 3.4 version of pip; sshuttle does not work with Python 3.4. You will need to install sshuttle using the Python 2.7 version of pip. I don't have a OpenSUSE box to test, however guessing it might be called "pip2.7".
