### ISSUE TITLE
Can't install in cPanel (non root)

### ISSUE THREAD

**Issue by animfahmy** [sshuttle/sshuttle#781]
sshuttle -r username@sshserver 0/0
fw: fatal: You must be root (or enable su/sudo) to set the firewall
c : fatal: All attempts to elevate privileges failed.

**Comment by yjftsjthsd-g** [comment]
sshuttle needs root in order to run (because it works by changing firewall rules); if you don't have a way to give it root (via su, sudo, doas, etc.) then it can't work.
