### ISSUE TITLE
Windows support 🤞

### ISSUE THREAD

**Issue by nom3ad** [sshuttle/sshuttle#794]
I have been using sshuttle for years from my Linux machine, and it works like a magic!  Thanks for this great project!
Recently, I had to switch to Windows for a  project and I wished to use sshuttle  as it was a part of my earlier workflow. 

So I looked into the documentation and found this [https://sshuttle.readthedocs.io/en/stable/windows.html#microsoft-windows](https://sshuttle.readthedocs.io/en/stable/windows.html#microsoft-windows).   
A VM  would be an overkill for just to run sshuttle.   It might be possible to have a similar setup using [WSL](https://docs.microsoft.com/en-us/windows/wsl/) which I haven't looked into yet.
  
 I am thinking  of a native support.  So, I researched a bit on how to achieve native Windows support for sshuttle.  Some options I could found are,

**1.  Method:  windivert**
Use [WinDivert](https://reqrypt.org/windivert.html) for packet capture & modify.     
There is a python wrapper for this library -  https://github.com/ffalcinelli/pydivert 
[mitmproxy](https://github.com/mitmproxy/mitmproxy)  uses pydivert for [it's windows support](https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/platform/windows.py#L17)
Windivert requires administrator privilege. 
It's easy to install `pydivert`  library using `pip install pydivert` -  prebuilt artifacts are bundled with PyPi package. 

**2.  Method:  ebpf**
Windows is about to get an official eBPF support - https://github.com/microsoft/ebpf-for-windows
In theory, it's possible to implement a NAT using eBPF.  That's something  https://github.com/cilium/cilium does for implementing CNI for Kubernetes (but only on Linux for now).
ebpf-for-windows requires administrator privilege and additional installation steps.
ebpf-for-windows is not GA yet.  Until then, [ it's not easy to consume it](https://github.com/microsoft/ebpf-for-windows/blob/main/docs/GettingStarted.md#installing-ebpf-for-windows) 
This method might be a good candidate for future, as we could have the same eBPF method working on both Windows and Linux.  

**So I was wondering if maintainers like the idea of supporting Windows with 'windivert' method.   If there is interest, I would love to try to implement it.** 

---
related issues
#32 #448
#742

**Comment by nom3ad** [comment]
@brianmay @skuhl  Any thoughts on this?

**Comment by brianmay** [comment]
If somebody is willing to do the work...

Seems like windivert wil be easier to implement, at least short term. ebpf might give better results long term, but isn't ready just yet.

Question is, will this fit into the existing methods abstraction for different firewalls. If not, this might require a redesign.

**Comment by nom3ad** [comment]
I think windivert method could be implemented without any redesign, but there would be some additional performance tradeoff  (anyways, windvert is inherently less performant as it involves userspace packet processing ).  

My Idea is:
  - implement windivert  packet capture/modify loop in the firewall process. 
  - firewall process will have a connection tracker implementation (only for TCP for now)
  - main process learns original connection destination address from the firewall process through IPC.
  
  And It would require some patches on various source files to work with many Windows quirks. 
  My goal is to make things work with the least changes in the existing code flow.

**Comment by brianmay** [comment]
Ideally this would not break existing platforms. And not require distributing windivert specific code throughout the project, Not sure if this is possible or not.

Other then that, it sounds fine to me.

**Comment by greatwolf** [comment]
Has there been any progress on this?

**Comment by nom3ad** [comment]
Last year, I had to use a Windows machine for a while, which made me to research on how to support sshuttle on Windows.  But then life happened, I couldn't find much free time to continue on that work.

But, I just started to working on it again, and I hope to wrap it up by a couple of days.

**Comment by greatwolf** [comment]
kewl, I look forward to trying it out and experimenting with it.

**Comment by nom3ad** [comment]
@greatwolf  It would be nice if could test it.
I have a draft PR  #918 

```powershell
PS C:\> pip install "git+https://github.com/nom3ad/sshuttle.git@windows-experimental-support"  -U --force
PS C:\> sshuttle --version
1.2.0
```

**Comment by mungujakisa** [comment]
Actually, I got a workaround years ago, hope it can help someone. 
On top of the connection command, add an exclusion option and exclude the host you are connecting to. For instance if you are connecting to a host called testhost.com, your command would look like this: `sshuttle -r user@testhost.com 0/0 -x testhost.com`
This allows you to connect.

**Comment by piernov** [comment]
Thanks for this great work.

For information, you can create a standalone Windows executable using this PyInstaller command:
```
pyinstaller.exe -F .\sshuttle\__main__.py --hidden-import sshuttle.assembler --hidden-import sshuttle.methods.windivert --add-data sshuttle/*.py:sshuttle/ -n sshuttle
```
after installing Python 3.12.10 using the official installer, and installing PyDivert and PyInstaller with pip.


I also tried with Nuitka using the following command:
```
nuitka --standalone .\sshuttle\__main__.py --include-module=sshuttle.assembler --include-package=sshuttle.methods --include-package-data=sshuttle:*.py --include-module=pydivert --include-package-data=pydivert:*.dll --include-package-data=pydivert:*.sys -o sshuttle.exe
```

but after connecting to the server, this error shows up:
```
c : fatal: other end: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)
