### ISSUE TITLE
How to use ssh alias?

### ISSUE THREAD

**Issue by simonleary-umass-edu** [sshuttle/sshuttle#798]
https://github.com/sshuttle/sshuttle/blob/9df7a0a053042c1b58d3f84fe088d77ca1e29b21/sshuttle/ssh.py
```
if only host is given, can be a hostname, IPv4/v6 address or a ssh alias from ~/.ssh/config
```
Can I have an example of correct syntax that uses an ssh alias?

**Comment by greatvovan** [comment]
I use alias when I need to enable an option not directly supported by sshuttle, for example, using parameters from SSH config file + an -o option:

```console
sshuttle --dns -r my.server.net -e "ssh -F $HOME/azsshconfig -o 'ServerAliveInterval=30'" 10.188.0.0/14
```

**Comment by simonleary-umass-edu** [comment]
I'm not sure what I was doing before when I made this ticket, but the syntax I must have been looking for was
```
ssh -r <alias> <subnet>
```
