### ISSUE TITLE
Doesn't encrypt data

### ISSUE THREAD

**Issue by SubhanSh** [sshuttle/sshuttle#805]
Actually I realized that the ISP can see the URL of any requests I send. for e.g. if I'm searching in google, my ISP can see I'm searching in google, but I don't expect it.

**Comment by skuhl** [comment]
Perhaps you are using sshuttle in a way where it only intercepts TCP traffic, but your browser is using UDP?  

For example, see #595 and #574.

**Comment by SubhanSh** [comment]
Thanks. I disabled QUIC in my browser and it worked.
