### ISSUE TITLE
How to pronounce sshuttle?

### ISSUE THREAD

**Issue by xor2k** [sshuttle/sshuttle#817]
Hi everybody,

sshuttle is a really cool project which I use for my projects, too. However, it is a little unclear to me how to actually pronounce it, can't even come up with a non-tounge-twisting pronunciation.

So how is sshuttle supposed to be pronounced?

Best, Michael

**Comment by brianmay** [comment]
I normally just say s + shuttle, but no idea if this is correct or not.
