### ISSUE TITLE
Bypassing Internet Censorship

### ISSUE THREAD

**Issue by donBarbos** [sshuttle/sshuttle#883]
i use the this command to start sshuttle:
```bash
sshuttle -vvvv -r root@server_ip -x server_ip 0/0
```
but still can't open blocked web resource. (my ip is changing but blocking can't be bypassed)

I found the following PR #232, but it has not been updated for a long time.

I would like to know how the work on this feature is progressing and how to bypass the blocking using sshuttle?

**Comment by TaradinAS** [comment]
Could you specify, how exactly web resource is blocked:
 by your ISP?
 by web resource itself?
Have you tested for DNS leaks, tested connection with `--dns` option?
