### ISSUE TITLE
How to stop sshuttle running in daemon mode?

### ISSUE THREAD

**Issue by nodje** [sshuttle/sshuttle#90]
I can't find a proper way to stop the daemon in the doc.
Kill it seems to create network problem (I guess routes are not reverted or something)

**Comment by vieira** [comment]
How are you killing it? kill -SIGTERM?

**Comment by nodje** [comment]
`kill -s TERM <pid> ` works on OSX
`kill-9 <pid>` lives the system without network access, as the firewall is not reverted to its original state I guess.
