### ISSUE TITLE
Support tunneling only specified ports.

### ISSUE THREAD

**Issue by vomout** [sshuttle/sshuttle#97]
It does not appear possible to tunnel over SSH only specific ports. I have the problem that my universities in its infinite wisdom blocks the email ports 587 and 465.  I have tried to get them opened, but they refuse. (This is in violation of RFC5068 and Eduroam policies, which state that these ports MUST BE open.) So I need to get those ports rerouted to the free outside world, so I can provide a hotspot for my devices and my visitors to access email. Sshuttle seems to be the tool, but it seems to forward all ports, which I don't want. Would it be possible to add an option to tunnel only specified ports?

**Comment by vieira** [comment]
Hello. I think this would be nice to have but to have a consistent implementation it will require some work, e.g., being able to specify a port range for a given subnet, being able to exclude some ports from that subnet-port range and making it work on Linux and all the supported BSDs/OSX.

- **Example** Use sshuttle for traffic going out to 188.0.0.0/8 on all ports from 80 to 85 and 443 excluding 80 on 188.113.88.193. Could look like this:
```
sshuttle -r user@server 188.0.0.0/8:80-85,443 -x 188.113.88.193:80
```
We can simplify things if we relax the problem a bit and assume that redirecting specific ports can be useful but port ranges rarely so. We might even go a step further a drop the requirement to exclude ports. Both of these can be added later without breaking the cli api.

If there is some more interest and @brianmay is OK with it I can try to come out with some implementation if no one else picks this up.

@vomout In the mean time maybe you can achieve this by adding some rule like the one below after starting sshuttle (I'm assuming you are running on Linux).
```
iptables -A sshuttle-12300 -t nat -j REDIRECT -p tcp --dport 587 --to-ports 12300 -m ttl ! --ttl 42
```

**Comment by brianmay** [comment]
@vieira I have no use case for this, so really don't know what the requirements for such a feature might be. Being able to specify the ports per subnet might look good, but is there an actual requirement (current or future) to support this? Depends how complicated this might be I guess.

No response from @vomout either...

**Comment by vomout** [comment]
> On 2 Jun 2016, at 23:39, João Vieira <notifications@github.com <mailto:notifications@github.com>> wrote:
> @vomout <https://github.com/vomout> In the mean time maybe you can achieve this by adding some rule like the one below after starting sshuttle (I'm assuming you are running on Linux).
> 
> iptables -A sshuttle-12300 -t nat -j REDIRECT -p tcp --dport 587 --to-ports 12300 -m ttl ! --ttl 42

Thanks. This seems to work on localhost, however devices connected to my hotspot do not seem to be caught by the rule. Would you happen to know how to do this? That’s the main use, to let my phone and laptop access email through the hotspot on my desktop, instead of using the crippled in-violation-of-ietf-and-eduroam-policy local eduroam implementation.

**Comment by vieira** [comment]
@vomout with your setup, is sshuttle working for you for a subnet or a single IP? For instance, `188.113.88.193` is the IP of `ifconfig.co`, a site that will show the IP from where you are connecting from. If you run something like `sshuttle -r <user>@<server> 188.113.88.193` and then open `ifconfig.co` from your phone or laptop do you see the IP of `<server>`?

If it is working then run `iptables-save` and take note of a rule with `sshuttle-12300` with destination `188.113.88.193`. Copy the rule and replace destination ip with dport port.

Sorry I can't help you more. Hope it helps.

**Comment by vomout** [comment]
I see the local IP.

**Comment by rsyncnet** [comment]
We (rsync.net) need this port-specific tunneling option as well - presumably you could add port ranges the -X option ...

We would like to sponsor this work by paying a developer to implement it - before we do that, can I get a quick confirmation that this function still does not exist and nobody is currently working on it ?

Thank you.

**Comment by vieira** [comment]
@rsyncnet Do you mean you would also want support for the exclusion of port ranges via -x?
Something like `sshuttle -r user@server 188.0.0.0/8:8000-9000,443 -x 188.113.88.193:8080-8090`?

I don't think I ever started working on this, don't know about @brianmay or someone else...

Thanks.

**Comment by rsyncnet** [comment]
Yes - we would like to be able to exclude *either* a port range globally (like -x 0.0.0.0:80) *or* a port range for a specific IP range:  -x 188.113.88.193:8080 ... and of course the port itself could also be a range ... 8000-9000, etc.

So ... no new command line options - just continue to use '-x' - but with expanded functionality.

We would be very happy to pay for a few hours of work to move this implementation up the priority list ... please email info at rsync dot net if you'd like to discuss details of that.

**Comment by brianmay** [comment]
I think this has been implemented. If I am mistaken, please let me know and I will reopen.
