### ISSUE TITLE
KeyError when running on Kali Linux

### ISSUE THREAD

**Issue by mcintst** [sshuttle/sshuttle#98]
After installing Django and txlib modules got the following error when running shuttle:

Traceback (most recent call last):
  File "/usr/local/bin/shuttle", line 9, in <module>
    load_entry_point('shuttle==0.1', 'console_scripts', 'shuttle')()
  File "/usr/local/lib/python2.7/dist-packages/shuttle/sync.py", line 512, in main
    HANDLERS[options.types](
KeyError: None

**Comment by brianmay** [comment]
What version of sshuttle is that? I don't know of any version of sshuttle that comes supplied with a ``sync.py`` file...

**Comment by mcintst** [comment]
sorry - looks like I was running 'shuttle' and not 'sshuttle' :-|
