### ISSUE TITLE
1.1.2 doesn't work on windows: ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by xiangnanscu** [sshuttle/sshuttle#997]
```
PS C:\WINDOWS\system32> pip install sshuttle
Collecting sshuttle
  Obtaining dependency information for sshuttle from https://files.pythonhosted.org/packages/61/b9/c540dd460d8da3bdea1d8b865d7c9d896a1b0761ffc01378ca7a3fa0abf2/sshuttle-1.1.2-py3-none-any.whl.metadata
  Using cached sshuttle-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Using cached sshuttle-1.1.2-py3-none-any.whl (68 kB)
Installing collected packages: sshuttle
Successfully installed sshuttle-1.1.2

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip
PS C:\WINDOWS\system32> sshuttle --dns -r root@xxx.xx 0.0.0.0/0 -x xxx.xx
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\sshuttle.exe\__main__.py", line 4, in <module>
  File "C:\Python312\Lib\site-packages\sshuttle\cmdline.py", line 7, in <module>
    import sshuttle.client as client
  File "C:\Python312\Lib\site-packages\sshuttle\client.py", line 11, in <module>
    import sshuttle.ssnet as ssnet
  File "C:\Python312\Lib\site-packages\sshuttle\ssnet.py", line 7, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

**Comment by daniillavr** [comment]
"Currently there is no built in support for running sshuttle directly on Microsoft Windows." - https://sshuttle.readthedocs.io/en/stable/windows.html

**Comment by xiangnanscu** [comment]
@daniillavr I thougt this commit means it support windows. 
https://github.com/sshuttle/sshuttle/commit/dff6950c4c178b7612555bf6f9c02d0f397f4bc4

**Comment by xiangnanscu** [comment]
@daniillavr also here: 
https://github.com/sshuttle/sshuttle/issues/473#issuecomment-2301187321

**Comment by daniillavr** [comment]
> @daniillavr also here: [#473 (comment)](https://github.com/sshuttle/sshuttle/issues/473#issuecomment-2301187321)

it is impossible coz of fnctl. It is linux lib so there is no way to port it easy. Anyway u can check code and if u will find only functions thats for only working with files, u can use this hack: https://stackoverflow.com/a/25471508 . Anyway u can use virtualbox it will take not a lot of time.

**Comment by brianmay** [comment]
1.1.2 was released **before** Windows support was introduced. If you want to try the Windows version you will need to use git master.

**Comment by daniillavr** [comment]
> 1.1.2 was released **before** Windows support was introduced. If you want to try the Windows version you will need to use git master.

I tried it too, compile under Cygwin, it wont compile, but i made changes in code and it compiled, but does not work, coz sockets undet Cygwin does not support DGRAM

**Comment by xiangnanscu** [comment]
Got it
